### ISSUE TITLE
FOQUS Cloud SLM Configuration 

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/FOQUS#1008]
# Description
Appears the SML server is not accessible to the FOQUS Workers on the cloud.  Investigate and fix.

```
2022-02-11 23:12:05,091 - ERROR - foqus.foqus_lib.framework.graph.node - Error while motoring job: 3, Ex: 350 - Job failed, Results: {'Id': 3, 'Guid': '81b9a6cd-86a2-4a08-978e-df6dbe2cf3e6', 'Simulation': 'BFB_v11_FBS_01_26_2018', 'State': 'error', 'Messages': ['event=setup,consumer=5de5e54a-1c68-4349-bf16-f349b6076273', 'working directory setup finished', 'Failed to open Simulation (1: Could not open ACM: Retrieving the COM class factory for component with CLSID {FDE14674-8E3D-0360-878A-2E97C127D967} failed due to the following error: 80080005 Server execution failed (Exception from HRESULT: 0x80080005 (CO_E_SERVER_EXEC_FAILURE)).', 'Failed to open Simulation (2: Could not open ACM: Retrieving the COM class factory for component with CLSID {FDE14674-8E3D-0360-878A-2E97C127D967} failed due to the following error: 80080005 Server execution failed (Exception from HRESULT: 0x80080005 (CO_E_SERVER_EXEC_FAILURE)).', 'Failed to open Simulation (3: Could not open ACM: Retrieving the COM class factory for component with CLSID {FDE14674-8E3D-0360-878A-2E97C127D967} failed due to the following error: 80080005 Server execution failed (Exception from HRESULT: 0x80080005 (CO_E_SERVER_EXEC_FAILURE)).', 'Failed to open Simulation (4: Could not open ACM: Retrieving the COM class factory for component with CLSID {FDE14674-8E3D-0360-878A-2E97C127D967} failed due to the following error: 80080005 Server execution failed (Exception from HRESULT: 0x80080005 (CO_E_SERVER_EXEC_FAILURE)).', 'event=error,consumer=5de5e54a-1c68-4349-bf16-f349b6076273,msg="Failed to open Simulation (5: Could not open ACM: Retrieving the COM class factory for component with CLSID {FDE14674-8E3D-0360-878A-2E97C127D967} failed due to the following error: 80080005 Server execution failed (Exception from HRESULT: 0x80080005 (CO_E_SERVER_EXEC_FAILURE))."'], 'Input': {'BFBRGN.Cr': 1.0, 'BFBRGN.Dt': 9.041, 'BFBRGN.Lb': 8.886, 'BFBRGNTop.Cr': 1.0, 'BFBRGNTop.Dt': 9.195, 'BFBRGNTop.Lb': 7.1926, 'BFBadsB.Cr': 1.0, 'BFBadsB.Dt': 11.897, 'BFBadsB.Lb': 2.085, 'BFBadsB.dx': 0.0127, 'BFBadsM.Cr': 1.0, 'BFBadsM.Dt': 15.0, 'BFBadsM.Lb': 1.972, 'BFBadsM.dx': 0.06695, 'BFBadsT.Cr': 1.0, 'BFBadsT.Dt': 15.0, 'BFBadsT.Lb': 2.203, 'BFBadsT.dx': 0.062397, 'GHXfg.A_exch': 16358.0, 'GHXfg.GasIn.P': 1.01325, 'GHXfg.GasIn.T': 54.0, 'Kd': 100.0, 'MinStepSize': 0.001, 'RunMode': 'Steady State', 'Script': 'Run_Steady', 'Snapshot': '', 'TimeSeries': [0.0], 'TimeUnits': 'Hours', 'dp': 0.00015, 'fg_flow': 100377.0, 'homotopy': 0, 'printlevel': 0}, 'Output': None, 'Errors': [], 'Status': 0, 'Session': 'a54e55f0-691e-449f-ad35-d7e7cd8d8fe8', 'Initialize': False, 'Reset': False, 'Visible': False, 'Consumer': '5de5e54a-1c68-4349-bf16-f349b6076273', 'Create': '2022-02-11T23:01:41.7330000', 'Submit': '2022-02-11T23:01:41.7800000', 'Setup': '2022-02-11T23:01:45.2200000', 'Finished': '2022-02-11T23:12:00.5600000'}
line: 3 file: <string> 
   
line: 497 file: c:\users\administrator\desktop\foqus\foqus_lib\framework\graph\node.py 
   self.runTurbineCalc(retry=self.options["Retry"].value)
line: 718 file: c:\users\administrator\desktop\foqus\foqus_lib\framework\graph\node.py 
   checkConsumer=localRun,
line: 1162 file: c:\users\administrator\desktop\foqus\foqus_lib\framework\sim\turbineConfiguration.py 
   msg = "".join(["Results: ", str(res)]))
line: 52 file: c:\users\administrator\desktop\foqus\foqus_lib\framework\sim\turbineConfiguration.py 
   foqusException.__init__(self, code=code, msg=msg, tb=tb)

2022-02-11 23:12:05,091 - INFO - foqus.foqus_lib.framework.graph.node - Job failed, stopping consumer for BFB_v11_FBS_01_26_2018
2022-02-11 23:12:05,107 - INFO - foqus.foqus_lib.framework.sim.turbineConfiguration - Terminating Consumer {5DE5E54A-1C68-4349-BF16-F349B6076273} posting to http://localhost:8000/TurbineLite/Consumer/{5DE5E54A-1C68-4349-BF16-F349B6076273}/stop
2022-02-11 23:12:07,138 - DEBUG - foqus.foqus_lib.framework.sim.process_management - Found Process: []
2022-02-11 23:12:07,138 - INFO - foqus.foqus_lib.framework.graph.node - Job 3 Failed will not retry
2022-02-11 23:12:07,138 - DEBUG - foqus.foqus_lib.framework.graph.node - Job 3 Results:
{"Id": 3, "Guid": "81b9a6cd-86a2-4a08-978e-df6dbe2cf3e6", "Simulation": "BFB_v11_FBS_01_26_2018", "State": "error", "Messages": ["event=setup,consumer=5de5e54a-1c68-4349-bf16-f349b6076273", "working directory setup finished", "Failed to open Simulation (1: Could not open ACM: Retrieving the COM class factory for component with CLSID {FDE14674-8E3D-0360-878A-2E97C127D967} failed due to the following error: 80080005 Server execution failed (Exception from HRESULT: 0x80080005 (CO_E_SERVER_EXEC_FAILURE)).", "Failed to open Simulation (2: Could not open ACM: Retrieving the COM class factory for component with CLSID {FDE14674-8E3D-0360-878A-2E97C127D967} failed due to the following error: 80080005 Server execution failed (Exception from HRESULT: 0x80080005 (CO_E_SERVER_EXEC_FAILURE)).", "Failed to open Simulation (3: Could not open ACM: Retrieving the COM class factory for component with CLSID {FDE14674-8E3D-0360-878A-2E97C127D967} failed due to the following error: 80080005 Server execution failed (Exception from HRESULT: 0x80080005 (CO_E_SERVER_EXEC_FAILURE)).", "Failed to open Simulation (4: Could not open ACM: Retrieving the COM class factory for component with CLSID {FDE14674-8E3D-0360-878A-2E97C127D967} failed due to the following error: 80080005 Server execution failed (Exception from HRESULT: 0x80080005 (CO_E_SERVER_EXEC_FAILURE)).", "event=error,consumer=5de5e54a-1c68-4349-bf16-f349b6076273,msg=\"Failed to open Simulation (5: Could not open ACM: Retrieving the COM class factory for component with CLSID {FDE14674-8E3D-0360-878A-2E97C127D967} failed due to the following error: 80080005 Server execution failed (Exception from HRESULT: 0x80080005 (CO_E_SERVER_EXEC_FAILURE)).\""], "Input": {"BFBRGN.Cr": 1.0, "BFBRGN.Dt": 9.041, "BFBRGN.Lb": 8.886, "BFBRGNTop.Cr": 1.0, "BFBRGNTop.Dt": 9.195, "BFBRGNTop.Lb": 7.1926, "BFBadsB.Cr": 1.0, "BFBadsB.Dt": 11.897, "BFBadsB.Lb": 2.085, "BFBadsB.dx": 0.0127, "BFBadsM.Cr": 1.0, "BFBadsM.Dt": 15.0, "BFBadsM.Lb": 1.972, "BFBadsM.dx": 0.06695, "BFBadsT.Cr": 1.0, "BFBadsT.Dt": 15.0, "BFBadsT.Lb": 2.203, "BFBadsT.dx": 0.062397, "GHXfg.A_exch": 16358.0, "GHXfg.GasIn.P": 1.01325, "GHXfg.GasIn.T": 54.0, "Kd": 100.0, "MinStepSize": 0.001, "RunMode": "Steady State", "Script": "Run_Steady", "Snapshot": "", "TimeSeries": [0.0], "TimeUnits": "Hours", "dp": 0.00015, "fg_flow": 100377.0, "homotopy": 0, "printlevel": 0}, "Output": null, "Errors": [], "Status": 0, "Session": "a54e55f0-691e-449f-ad35-d7e7cd8d8fe8", "Initialize": false, "Reset": false, "Visible": false, "Consumer": "5de5e54a-1c68-4349-bf16-f349b6076273", "Create": "2022-02-11T23:01:41.7330000", "Submit": "2022-02-11T23:01:41.7800000", "Setup": "2022-02-11T23:01:45.2200000", "Finished": "2022-02-11T23:12:00.5600000"}
2022-02-11 23:12:07,138 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - turbine configuration application url="http://localhost:8000/TurbineLite/application/"
2022-02-11 23:12:07,138 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - turbine configuration url="http://localhost:8000/TurbineLite"
2022-02-11 23:12:07,138 - ERROR - foqus.foqus_lib.framework.graph.node - Error in node python code
Traceback (most recent call last):
  File "c:\users\administrator\desktop\foqus\foqus_lib\framework\graph\node.py", line 558, in runPython
    exec(self.pythonCode)
  File "<string>", line 5, in <module>
Exception: Steady state homotopy failed
```

**Comment by boverhof** [comment]
@anujad95 and @sotorrio1 It appears I forgot to install the license a few weeks ago after upgrading the the AWS SLM to the v12.  So the worker was just hanging and timing out because it could find a license. 

The run took `1:49` 

It is working now.
![Screen Shot 2022-02-11 at 3 46 09 PM](https://user-images.githubusercontent.com/738295/153685618-e50426b2-4b2b-418b-8650-689aee979de7.png)

**Comment by sotorrio1** [comment]
@boverhof thanks for looking into this. It works for me as well.
