### ISSUE TITLE
FOQUS Cloud:  UQ tab, OUU BFB Aspen Test

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/FOQUS#1009]
# Description
- UQ tab
```
2022-02-15 18:31:29,327 - INFO - foqus.foqus_lib.service.flowsheet - TurbineLiteDB.consumer_status
2022-02-15 18:31:31,827 - ERROR - foqus.foqus_lib.framework.graph.node - Error while motoring job: 2, Ex: 350 - Job failed, Results: {'Id': 2, 'Guid': '75a60524-18e5-41d2-be06-e767c41602fc', 'Simulation': 'BFB_v11_FBS_01_26_2018', 'State': 'error', 'Messages': ['event=setup,consumer=57ab06df-bc4d-4828-b084-48a8bf843c84', 'working directory setup finished', 'sinter read setup finished', 'event=running,consumer=57ab06df-bc4d-4828-b084-48a8bf843c84', 'sinter inputs sent, running simulation', 'Real Run failed, runStatus=si_SIMULATION_ERROR', 'event=error,consumer=57ab06df-bc4d-4828-b084-48a8bf843c84,msg="Error: si_SIMULATION_ERROR:  >>       HX0=  0.9274685D+00  DHX= 0.44741654D-04\r,Properties >>   *   WARNING IN PHYSICAL PROPERTY SYSTEM\r,Properties >>       TRAPP TRANSPORT MODEL, DENSITY OF REFERENCE FLUID DID NOT CONVERGE\r,Properties >>       FX0=  0.6863400D+00  DFX= 0.35371714D-03\r,Properties >>       HX0=  0.9274685D+00  DHX= 0.44502344D-04\r,Properties >>   *   WARNING IN PHYSICAL PROPERTY SYSTEM\r,Properties >>       TRAPP TRANSPORT PROPERTIES MODEL, REFERENCE FLUID DENSITY DID NOT CONVERGE\r,Properties >>       FX0=  0.6863400D+00  DFX= 0.35610467D-03\r,Properties >>       HX0=  0.9274685D+00  DHX= 0.44741654D-04\r,Properties >>   *   WARNING IN PHYSICAL PROPERTY SYSTEM\r,Properties >>       TRAPP TRANSPORT PROPERTIES MODEL, REFERENCE FLUID DENSITY DID NOT CONVERGE\r,Properties >>       FX0=  0.6870163D+00  DFX= 0.36711426D-03\r,Properties >>       HX0=  0.9276036D+00  DHX= 0.46020762D-04\r,Properties >>   *   WARNING IN PHYSICAL PROPERTY SYSTEM\r,Properties >>       TRAPP TRANSPORT MODEL, DENSITY OF REFERENCE FLUID DID NOT CONVERGE\r,Properties >>       FX0=  0.6870163D+00  DFX= 0.36465840D-03\r,Properties >>       HX0=  0.9276036D+00  DHX= 0.45778740D-04\r,Properties >>   *   WARNING IN PHYSICAL PROPERTY SYSTEM\r,Properties >>       TRAPP TRANSPORT PROPERTIES MODEL, REFERENCE FLUID DENSITY DID NOT CONVERGE\r,Properties >>       FX0=  0.6870163D+00  DFX= 0.36711426D-03\r,Properties >>       HX0=  0.9276036D+00  DHX= 0.46020762D-04\r,Properties >>   *   WARNING IN PHYSICAL PROPERTY SYSTEM\r,Properties >>       TRAPP TRANSPORT PROPERTIES MODEL, REFERENCE FLUID DENSITY DID NOT CONVERGE\r,Properties >>       FX0=  0.6870163D+00  DFX= 0.36711426D-03\r,Properties >>       HX0=  0.9276036D+00  DHX= 0.46020762D-04\r,Properties >>   *   WARNING IN PHYSICAL PROPERTY SYSTEM\r,Properties >>       TRAPP TRANSPORT MODEL, DENSITY OF REFERENCE FLUID DID NOT CONVERGE\r,Properties >>       FX0=  0.6870163D+00  DFX= 0.36465840D-03\r,Properties >>       HX0=  0.9276036D+00  DHX= 0.45778740D-04\r,Properties >>   *   WARNING IN PHYSICAL PROPERTY SYSTEM\r,Properties >>       TRAPP TRANSPORT PROPERTIES MODEL, REFERENCE FLUID DENSITY DID NOT CONVERGE\r,Properties >>       FX0=  0.6870163D+00  DFX= 0.36711426D-03\r,Properties >>       HX0=  0.9276036D+00  DHX= 0.46020762D-04\r,Properties >>   *   WARNING IN PHYSICAL PROPERTY SYSTEM\r,Properties >>       TRAPP TRANSPORT PROPERTIES MODEL, REFERENCE FLUID DENSITY DID NOT CONVERGE\r,Properties >>       FX0=  0.6853315D+00  DFX= 0.45054046D-03\r,Properties >>       HX0=  0.9281837D+00  DHX= 0.56674749D-04\r,Properties >>   *   WARNING IN PHYSICAL PROPERTY SYSTEM\r,Properties >>       TRAPP TRANSPORT MODEL, DENSITY OF REFERENCE FLUID DID NOT CONVERGE\r,Properties >>       FX0=  0.6853315D+00  DFX= 0.44751023D-03\r,Properties >>       HX0=  0.9281837D+00  DHX= 0.56363324D-04\r,Properties >>   *   WARNING IN PHYSICAL PROPERTY SYSTEM\r,Properties >>       TRAPP TRANSPORT PROPERTIES MODEL, REFERENCE FLUID DENSITY DID NOT CONVERGE\r,Properties >>       FX0=  0.6853315D+00  DFX= 0.45054046D-03\r,Properties >>       HX0=  0.9281837D+00  DHX= 0.56674749D-04\r,Properties >>   *   WARNING IN PHYSICAL PROPERTY SYSTEM\r,Properties >>       TRAPP TRANSPORT PROPERTIES MODEL, REFERENCE FLUID DENSITY DID NOT CONVERGE\r,Properties >>       FX0=  0.6853315D+00  DFX= 0.45054046D-03\r,Properties >>       HX0=  0.9281837D+00  DHX= 0.56674749D-04\r,Properties >>   *   WARNING IN PHYSICAL PROPERTY SYSTEM\r,Properties >>       TRAPP TRANSPORT MODEL, DENSITY OF REFERENCE FLUID DID NOT CONVERGE\r,Properties >>       FX0=  0.6853315D+00  DFX= 0.44751023D-03\r,Properties >>       HX0=  0.9281837D+00  DHX= 0.56363324D-04\r,Properties >>   *   WARNING IN PHYSICAL PROPERTY SYSTEM\r,Properties >>       TRAPP TRANSPORT PROPERTIES MODEL, REFERENCE FLUID DENSITY DID NOT CONVERGE\r,Proper"'], 'Input': {'BFBRGN.Cr': 1.0, 'BFBRGN.Dt': 10.0, 'BFBRGN.Lb': 0.075, 'BFBRGNTop.Cr': 1.0, 'BFBRGNTop.Dt': 2.5, 'BFBRGNTop.Lb': 7.1926, 'BFBadsB.Cr': 1.0, 'BFBadsB.Dt': 11.897, 'BFBadsB.Lb': 0.075, 'BFBadsB.dx': 10.0, 'BFBadsM.Cr': 1.0, 'BFBadsM.Dt': 2.5, 'BFBadsM.Lb': 10.0, 'BFBadsM.dx': 0.06695, 'BFBadsT.Cr': 1.0, 'BFBadsT.Dt': 0.075, 'BFBadsT.Lb': 2.203, 'BFBadsT.dx': 0.75, 'GHXfg.A_exch': 16358.0, 'GHXfg.GasIn.P': 1.01325, 'GHXfg.GasIn.T': 54.0, 'Kd': 100.0, 'MinStepSize': 0.001, 'RunMode': 'Steady State', 'Script': 'Run_Steady', 'Snapshot': '', 'TimeSeries': [0.0], 'TimeUnits': 'Hours', 'dp': 0.00015, 'fg_flow': 100377.0, 'homotopy': 0, 'printlevel': 0}, 'Output': None, 'Errors': [], 'Status': 1, 'Session': '35f06ba4-dbb7-4037-8d6c-3da47b2efa78', 'Initialize': False, 'Reset': False, 'Visible': False, 'Consumer': '57ab06df-bc4d-4828-b084-48a8bf843c84', 'Create': '2022-02-15T18:27:53.2370000', 'Submit': '2022-02-15T18:27:53.3300000', 'Setup': '2022-02-15T18:27:57.4230000', 'Running': '2022-02-15T18:28:46.3300000', 'Finished': '2022-02-15T18:31:29.9370000'}
line: 3 file: <string> 
   
line: 497 file: c:\users\administrator\desktop\foqus\foqus_lib\framework\graph\node.py 
   self.runTurbineCalc(retry=self.options["Retry"].value)
line: 718 file: c:\users\administrator\desktop\foqus\foqus_lib\framework\graph\node.py 
   checkConsumer=localRun,
line: 1162 file: c:\users\administrator\desktop\foqus\foqus_lib\framework\sim\turbineConfiguration.py 
   msg = "".join(["Results: ", str(res)]))
line: 52 file: c:\users\administrator\desktop\foqus\foqus_lib\framework\sim\turbineConfiguration.py 
   foqusException.__init__(self, code=code, msg=msg, tb=tb)

2022-02-15 18:31:31,827 - INFO - foqus.foqus_lib.framework.graph.node - Job failed, stopping consumer for BFB_v11_FBS_01_26_2018
2022-02-15 18:31:31,843 - INFO - foqus.foqus_lib.framework.sim.turbineConfiguration - Terminating Consumer {57AB06DF-BC4D-4828-B084-48A8BF843C84} posting to http://localhost:8000/TurbineLite/Consumer/{57AB06DF-BC4D-4828-B084-48A8BF843C84}/stop
2022-02-15 18:31:34,889 - DEBUG - foqus.foqus_lib.framework.sim.process_management - Found Process: []
2022-02-15 18:31:34,889 - INFO - foqus.foqus_lib.framework.graph.node - Job 2 Failed will not retry
2022-02-15 18:31:34,889 - DEBUG - foqus.foqus_lib.framework.graph.node - Job 2 Results:
{"Id": 2, "Guid": "75a60524-18e5-41d2-be06-e767c41602fc", "Simulation": "BFB_v11_FBS_01_26_2018", "State": "error", "Messages": ["event=setup,consumer=57ab06df-bc4d-4828-b084-48a8bf843c84", "working directory setup finished", "sinter read setup finished", "event=running,consumer=57ab06df-bc4d-4828-b084-48a8bf843c84", "sinter inputs sent, running simulation", "Real Run failed, runStatus=si_SIMULATION_ERROR", "event=error,consumer=57ab06df-bc4d-4828-b084-48a8bf843c84,msg=\"Error: si_SIMULATION_ERROR:  >>       HX0=  0.9274685D+00  DHX= 0.44741654D-04\r,Properties >>   *   WARNING IN PHYSICAL PROPERTY SYSTEM\r,Properties >>       TRAPP TRANSPORT MODEL, DENSITY OF REFERENCE FLUID DID NOT CONVERGE\r,Properties >>       FX0=  0.6863400D+00  DFX= 0.35371714D-03\r,Properties >>       HX0=  0.9274685D+00  DHX= 0.44502344D-04\r,Properties >>   *   WARNING IN PHYSICAL PROPERTY SYSTEM\r,Properties >>       TRAPP TRANSPORT PROPERTIES MODEL, REFERENCE FLUID DENSITY DID NOT CONVERGE\r,Properties >>       FX0=  0.6863400D+00  DFX= 0.35610467D-03\r,Properties >>       HX0=  0.9274685D+00  DHX= 0.44741654D-04\r,Properties >>   *   WARNING IN PHYSICAL PROPERTY SYSTEM\r,Properties >>       TRAPP TRANSPORT PROPERTIES MODEL, REFERENCE FLUID DENSITY DID NOT CONVERGE\r,Properties >>       FX0=  0.6870163D+00  DFX= 0.36711426D-03\r,Properties >>       HX0=  0.9276036D+00  DHX= 0.46020762D-04\r,Properties >>   *   WARNING IN PHYSICAL PROPERTY SYSTEM\r,Properties >>       TRAPP TRANSPORT MODEL, DENSITY OF REFERENCE FLUID DID NOT CONVERGE\r,Properties >>       FX0=  0.6870163D+00  DFX= 0.36465840D-03\r,Properties >>       HX0=  0.9276036D+00  DHX= 0.45778740D-04\r,Properties >>   *   WARNING IN PHYSICAL PROPERTY SYSTEM\r,Properties >>       TRAPP TRANSPORT PROPERTIES MODEL, REFERENCE FLUID DENSITY DID NOT CONVERGE\r,Properties >>       FX0=  0.6870163D+00  DFX= 0.36711426D-03\r,Properties >>       HX0=  0.9276036D+00  DHX= 0.46020762D-04\r,Properties >>   *   WARNING IN PHYSICAL PROPERTY SYSTEM\r,Properties >>       TRAPP TRANSPORT PROPERTIES MODEL, REFERENCE FLUID DENSITY DID NOT CONVERGE\r,Properties >>       FX0=  0.6870163D+00  DFX= 0.36711426D-03\r,Properties >>       HX0=  0.9276036D+00  DHX= 0.46020762D-04\r,Properties >>   *   WARNING IN PHYSICAL PROPERTY SYSTEM\r,Properties >>       TRAPP TRANSPORT MODEL, DENSITY OF REFERENCE FLUID DID NOT CONVERGE\r,Properties >>       FX0=  0.6870163D+00  DFX= 0.36465840D-03\r,Properties >>       HX0=  0.9276036D+00  DHX= 0.45778740D-04\r,Properties >>   *   WARNING IN PHYSICAL PROPERTY SYSTEM\r,Properties >>       TRAPP TRANSPORT PROPERTIES MODEL, REFERENCE FLUID DENSITY DID NOT CONVERGE\r,Properties >>       FX0=  0.6870163D+00  DFX= 0.36711426D-03\r,Properties >>       HX0=  0.9276036D+00  DHX= 0.46020762D-04\r,Properties >>   *   WARNING IN PHYSICAL PROPERTY SYSTEM\r,Properties >>       TRAPP TRANSPORT PROPERTIES MODEL, REFERENCE FLUID DENSITY DID NOT CONVERGE\r,Properties >>       FX0=  0.6853315D+00  DFX= 0.45054046D-03\r,Properties >>       HX0=  0.9281837D+00  DHX= 0.56674749D-04\r,Properties >>   *   WARNING IN PHYSICAL PROPERTY SYSTEM\r,Properties >>       TRAPP TRANSPORT MODEL, DENSITY OF REFERENCE FLUID DID NOT CONVERGE\r,Properties >>       FX0=  0.6853315D+00  DFX= 0.44751023D-03\r,Properties >>       HX0=  0.9281837D+00  DHX= 0.56363324D-04\r,Properties >>   *   WARNING IN PHYSICAL PROPERTY SYSTEM\r,Properties >>       TRAPP TRANSPORT PROPERTIES MODEL, REFERENCE FLUID DENSITY DID NOT CONVERGE\r,Properties >>       FX0=  0.6853315D+00  DFX= 0.45054046D-03\r,Properties >>       HX0=  0.9281837D+00  DHX= 0.56674749D-04\r,Properties >>   *   WARNING IN PHYSICAL PROPERTY SYSTEM\r,Properties >>       TRAPP TRANSPORT PROPERTIES MODEL, REFERENCE FLUID DENSITY DID NOT CONVERGE\r,Properties >>       FX0=  0.6853315D+00  DFX= 0.45054046D-03\r,Properties >>       HX0=  0.9281837D+00  DHX= 0.56674749D-04\r,Properties >>   *   WARNING IN PHYSICAL PROPERTY SYSTEM\r,Properties >>       TRAPP TRANSPORT MODEL, DENSITY OF REFERENCE FLUID DID NOT CONVERGE\r,Properties >>       FX0=  0.6853315D+00  DFX= 0.44751023D-03\r,Properties >>       HX0=  0.9281837D+00  DHX= 0.56363324D-04\r,Properties >>   *   WARNING IN PHYSICAL PROPERTY SYSTEM\r,Properties >>       TRAPP TRANSPORT PROPERTIES MODEL, REFERENCE FLUID DENSITY DID NOT CONVERGE\r,Proper\""], "Input": {"BFBRGN.Cr": 1.0, "BFBRGN.Dt": 10.0, "BFBRGN.Lb": 0.075, "BFBRGNTop.Cr": 1.0, "BFBRGNTop.Dt": 2.5, "BFBRGNTop.Lb": 7.1926, "BFBadsB.Cr": 1.0, "BFBadsB.Dt": 11.897, "BFBadsB.Lb": 0.075, "BFBadsB.dx": 10.0, "BFBadsM.Cr": 1.0, "BFBadsM.Dt": 2.5, "BFBadsM.Lb": 10.0, "BFBadsM.dx": 0.06695, "BFBadsT.Cr": 1.0, "BFBadsT.Dt": 0.075, "BFBadsT.Lb": 2.203, "BFBadsT.dx": 0.75, "GHXfg.A_exch": 16358.0, "GHXfg.GasIn.P": 1.01325, "GHXfg.GasIn.T": 54.0, "Kd": 100.0, "MinStepSize": 0.001, "RunMode": "Steady State", "Script": "Run_Steady", "Snapshot": "", "TimeSeries": [0.0], "TimeUnits": "Hours", "dp": 0.00015, "fg_flow": 100377.0, "homotopy": 0, "printlevel": 0}, "Output": null, "Errors": [], "Status": 1, "Session": "35f06ba4-dbb7-4037-8d6c-3da47b2efa78", "Initialize": false, "Reset": false, "Visible": false, "Consumer": "57ab06df-bc4d-4828-b084-48a8bf843c84", "Create": "2022-02-15T18:27:53.2370000", "Submit": "2022-02-15T18:27:53.3300000", "Setup": "2022-02-15T18:27:57.4230000", "Running": "2022-02-15T18:28:46.3300000", "Finished": "2022-02-15T18:31:29.9370000"}
2022-02-15 18:31:34,889 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - turbine configuration application url="http://localhost:8000/TurbineLite/application/"
2022-02-15 18:31:34,889 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - turbine configuration url="http://localhost:8000/TurbineLite"
2022-02-15 18:31:34,889 - ERROR - foqus.foqus_lib.framework.graph.node - Error in node python code
Traceback (most recent call last):
  File "c:\users\administrator\desktop\foqus\foqus_lib\framework\graph\node.py", line 558, in runPython
    exec(self.pythonCode)
  File "<string>", line 5, in <module>
Exception: Steady state homotopy failed
```

**Comment by sotorrio1** [comment]
### How to setup OUU problem (BFB_OUU_06_09_2020.foqus)

1. Choose Flowsheet Node: Full
2. Setup Variable Types:
All variables with **.Dt**, **.dx** and **.Lb** are **Z1** type. **BFB.GHXfg.A_exch** is also **Z1** type. **BFB.dp** and **BFB.fg_flow** are **Z3** type. The rest you can leave as **Fixed**.
3. Outputs tab: 
Select **BFB.Cost_coe_obj** as the **Objective Function**
4. UQ Setup tab: 
Load **z3sample.smp** for **Z3** variables.
5. Launch/Progress tab: **Run OUU**

**Comment by ksbeattie** [comment]
This is related to #1004

**Comment by boverhof** [comment]
# Reduced Problem Set
I set this problem up with two Optimization Z1 variables and one Z3 UQ variable and it completed in a few hours successfully and it appears like all Aspen jobs succeeded with no errors.

### Optimization:  Primary Continuous Z1
- BFBadsB.Cr
- BFBadsB.Dt
- BFBadsB.dx
### UQ:   Discrete Z3
- BFB.fg_flow 

<img width="1225" alt="Screen Shot 2022-05-17 at 10 24 20 PM" src="https://user-images.githubusercontent.com/738295/168963726-fb68ab0b-3693-44c2-ad35-f4e599aa7d2f.png">

**Comment by sotorrio1** [comment]
@boverhof That's great news!

**Comment by ksbeattie** [comment]
@boverhof can this be closed now?

**Comment by boverhof** [comment]
[z3Samples.smp.txt](https://github.com/CCSI-Toolset/FOQUS/files/11326089/z3Samples.smp.txt)
