### ISSUE TITLE
FOQUS adodbapi import error

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/FOQUS#1012]
# Description
Good morning! I am running into a Turbine issue, and would appreciate assistance troubleshooting the cause. When I load a session and attempt to open a node containing a Turbine/Aspen model, I see a dialog box with "The Turbine model specified for this node is not available from Turbine. Model: [the name of my JSON file without the extension]". I have the file outside of my FOQUS-WD, so it may be as simple as moving it to correct location.
I see the message below when launching FOQUS and tried re-installing PSUADE-LITE, restarting the Turbine AWS service and upgrading adodbapi, none of which resolved the issue below or added the module I am missing. It's unclear if this is causing the issue above:

## Traceback
```
(ccsi-foqus) C:\Users\bpaul\GitHub\CCSI-Toolset\FOQUS>foqus
Problem importing turbineLiteDB
Traceback (most recent call last):
  File "c:\users\bpaul\github\ccsi-toolset\foqus\foqus_lib\framework\sim\turbineConfiguration.py", line 50, in <module>
    from . import turbineLiteDB
  File "c:\users\bpaul\github\ccsi-toolset\foqus\foqus_lib\framework\sim\turbineLiteDB.py", line 25, in <module>
    import adodbapi
  File "C:\Users\bpaul\Miniconda3\envs\ccsi-foqus\lib\site-packages\adodbapi\__init__.py", line 16, in <module>
    from .apibase import apilevel, threadsafety, paramstyle
ModuleNotFoundError: No module named 'adodbapi.apibase'
```

## System Details
```
(ccsi-foqus) C:\Users\bpaul>conda info
     active environment : ccsi-foqus
    active env location : C:\Users\bpaul\Miniconda3\envs\ccsi-foqus
            shell level : 2
       user config file : C:\Users\bpaul\.condarc
 populated config files :
          conda version : 4.11.0
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\bpaul\Miniconda3  (writable)
      conda av data dir : C:\Users\bpaul\Miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\bpaul\Miniconda3\pkgs
                          C:\Users\bpaul\.conda\pkgs
                          C:\Users\bpaul\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\bpaul\Miniconda3\envs
                          C:\Users\bpaul\.conda\envs
                          C:\Users\bpaul\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.11.0 requests/2.24.0 CPython/3.8.5 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by boverhof** [comment]
# Test Environment
- Windows 2016 Server Base AMI
- https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe

**Comment by boverhof** [comment]
# SUCCEDE in importing
```
(base) C:\Users\Administrator>conda create --name ccsi-foqus python=3.8
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\ProgramData\Miniconda3\envs\ccsi-foqus

  added / updated specs:
    - python=3.8


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2021.10.26 |       haa95532_4         116 KB
    certifi-2021.10.8          |   py38haa95532_2         152 KB
    pip-21.2.2                 |   py38haa95532_0         1.9 MB
    python-3.8.12              |       h6244533_0        16.0 MB
    setuptools-58.0.4          |   py38haa95532_0         779 KB
    sqlite-3.37.2              |       h2bbff1b_0         799 KB
    wincertstore-0.2           |   py38haa95532_2          15 KB
    ------------------------------------------------------------
                                           Total:        19.7 MB

The following NEW packages will be INSTALLED:

  ca-certificates    pkgs/main/win-64::ca-certificates-2021.10.26-haa95532_4
  certifi            pkgs/main/win-64::certifi-2021.10.8-py38haa95532_2
  openssl            pkgs/main/win-64::openssl-1.1.1m-h2bbff1b_0
  pip                pkgs/main/win-64::pip-21.2.2-py38haa95532_0
  python             pkgs/main/win-64::python-3.8.12-h6244533_0
  setuptools         pkgs/main/win-64::setuptools-58.0.4-py38haa95532_0
  sqlite             pkgs/main/win-64::sqlite-3.37.2-h2bbff1b_0
  vc                 pkgs/main/win-64::vc-14.2-h21ff451_1
  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.27.29016-h5e58377_2
  wheel              pkgs/main/noarch::wheel-0.37.1-pyhd3eb1b0_0
  wincertstore       pkgs/main/win-64::wincertstore-0.2-py38haa95532_2


Proceed ([y]/n)? y


Downloading and Extracting Packages
wincertstore-0.2     | 15 KB     | ############################################################################ | 100%
certifi-2021.10.8    | 152 KB    | ############################################################################ | 100%
setuptools-58.0.4    | 779 KB    | ############################################################################ | 100%
pip-21.2.2           | 1.9 MB    | ############################################################################ | 100%
ca-certificates-2021 | 116 KB    | ############################################################################ | 100%
sqlite-3.37.2        | 799 KB    | ############################################################################ | 100%
python-3.8.12        | 16.0 MB   | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate ccsi-foqus
#
# To deactivate an active environment, use
#
#     $ conda deactivate


(base) C:\Users\Administrator>conda activate ccsi-foqus

(ccsi-foqus) C:\Users\Administrator>pip install ccsi-foqus
Collecting ccsi-foqus
  Downloading ccsi_foqus-3.12.0-py3-none-any.whl (1.0 MB)
     |████████████████████████████████| 1.0 MB ...
Collecting requests
  Downloading requests-2.27.1-py2.py3-none-any.whl (63 kB)
     |████████████████████████████████| 63 kB 740 kB/s
Collecting websocket-client>=1.1.0
  Downloading websocket_client-1.2.3-py3-none-any.whl (53 kB)
     |████████████████████████████████| 53 kB 914 kB/s
Collecting adodbapi>=2.6.0.7
  Downloading adodbapi-2.6.2.0.zip (297 kB)
     |████████████████████████████████| 297 kB ...
Collecting PyQt5==5.13
  Downloading PyQt5-5.13.0-5.13.0-cp35.cp36.cp37.cp38-none-win_amd64.whl (49.7 MB)
     |████████████████████████████████| 49.7 MB 159 kB/s
Collecting mplcursors
  Downloading mplcursors-0.5.1.tar.gz (88 kB)
     |████████████████████████████████| 88 kB 3.8 MB/s
Collecting cma
  Downloading cma-3.1.0-py2.py3-none-any.whl (269 kB)
     |████████████████████████████████| 269 kB ...
Collecting mlrose-hiive==2.1.3
  Downloading mlrose_hiive-2.1.3.tar.gz (48 kB)
     |████████████████████████████████| 48 kB 3.2 MB/s
Collecting psutil
  Downloading psutil-5.9.0-cp38-cp38-win_amd64.whl (246 kB)
     |████████████████████████████████| 246 kB 6.4 MB/s
Collecting tqdm
  Downloading tqdm-4.62.3-py2.py3-none-any.whl (76 kB)
     |████████████████████████████████| 76 kB 5.5 MB/s
Collecting TurbineClient
  Downloading TurbineClient-3.1.0-py3-none-any.whl (45 kB)
     |████████████████████████████████| 45 kB 1.4 MB/s
Collecting winshell
  Downloading winshell-0.6.zip (10 kB)
Collecting pywin32==225
  Downloading pywin32-225-cp38-cp38-win_amd64.whl (9.1 MB)
     |████████████████████████████████| 9.1 MB ...
Collecting boto3
  Downloading boto3-1.21.6-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB ...
Collecting numpy
  Downloading numpy-1.22.2-cp38-cp38-win_amd64.whl (14.7 MB)
     |████████████████████████████████| 14.7 MB ...
Collecting scipy
  Downloading scipy-1.8.0-cp38-cp38-win_amd64.whl (36.9 MB)
     |████████████████████████████████| 36.9 MB 6.4 MB/s
Collecting pandas
  Downloading pandas-1.4.1-cp38-cp38-win_amd64.whl (10.6 MB)
     |████████████████████████████████| 10.6 MB ...
Collecting matplotlib
  Downloading matplotlib-3.5.1-cp38-cp38-win_amd64.whl (7.2 MB)
     |████████████████████████████████| 7.2 MB 6.8 MB/s
Collecting scikit-learn
  Downloading scikit_learn-1.0.2-cp38-cp38-win_amd64.whl (7.2 MB)
     |████████████████████████████████| 7.2 MB ...
Collecting networkx
  Downloading networkx-2.6.3-py3-none-any.whl (1.9 MB)
     |████████████████████████████████| 1.9 MB ...
Collecting joblib
  Downloading joblib-1.1.0-py2.py3-none-any.whl (306 kB)
     |████████████████████████████████| 306 kB ...
Collecting PyQt5_sip<13,>=4.19.14
  Downloading PyQt5_sip-12.9.1-cp38-cp38-win_amd64.whl (77 kB)
     |████████████████████████████████| 77 kB 2.9 MB/s
Collecting botocore<1.25.0,>=1.24.6
  Downloading botocore-1.24.6-py3-none-any.whl (8.5 MB)
     |████████████████████████████████| 8.5 MB 6.8 MB/s
Collecting jmespath<1.0.0,>=0.7.1
  Downloading jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
Collecting s3transfer<0.6.0,>=0.5.0
  Downloading s3transfer-0.5.1-py3-none-any.whl (79 kB)
     |████████████████████████████████| 79 kB 5.5 MB/s
Collecting python-dateutil<3.0.0,>=2.1
  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
     |████████████████████████████████| 247 kB 6.4 MB/s
Collecting urllib3<1.27,>=1.25.4
  Downloading urllib3-1.26.8-py2.py3-none-any.whl (138 kB)
     |████████████████████████████████| 138 kB ...
Collecting six>=1.5
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting packaging>=20.0
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting cycler>=0.10
  Downloading cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting pyparsing>=2.2.1
  Using cached pyparsing-3.0.7-py3-none-any.whl (98 kB)
Collecting pillow>=6.2.0
  Downloading Pillow-9.0.1-cp38-cp38-win_amd64.whl (3.2 MB)
     |████████████████████████████████| 3.2 MB ...
Collecting fonttools>=4.22.0
  Downloading fonttools-4.29.1-py3-none-any.whl (895 kB)
     |████████████████████████████████| 895 kB ...
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.3.2-cp38-cp38-win_amd64.whl (52 kB)
     |████████████████████████████████| 52 kB 355 kB/s
Collecting pytz>=2020.1
  Downloading pytz-2021.3-py2.py3-none-any.whl (503 kB)
     |████████████████████████████████| 503 kB ...
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\miniconda3\envs\ccsi-foqus\lib\site-packages (from requests->ccsi-foqus) (2021.10.8)
Collecting charset-normalizer~=2.0.0
  Downloading charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Collecting idna<4,>=2.5
  Downloading idna-3.3-py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 3.8 MB/s
Collecting threadpoolctl>=2.0.0
  Downloading threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
Collecting colorama
  Downloading colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Building wheels for collected packages: mlrose-hiive, adodbapi, mplcursors, winshell
  Building wheel for mlrose-hiive (setup.py) ... done
  Created wheel for mlrose-hiive: filename=mlrose_hiive-2.1.3-py3-none-any.whl size=96601 sha256=59d90a62e4051c4f2ea1db8cc8dfa1dd47d73ec7607e8517df14033897db8ac0
  Stored in directory: c:\users\administrator\appdata\local\pip\cache\wheels\93\f3\c0\60599df28d11062ae335202ec9455299c5a55df29d37beb4a6
  Building wheel for adodbapi (setup.py) ... done
  Created wheel for adodbapi: filename=adodbapi-2.6.2.0-py3-none-any.whl size=48464 sha256=409695c202bf81d81038fb7a5e67f92f0d366d43f66c17aee11d4d34afd7dcff
  Stored in directory: c:\users\administrator\appdata\local\pip\cache\wheels\a3\cd\89\948e4155c3135512f658fd1e0a785cee73946653c94bcd1707
  Building wheel for mplcursors (setup.py) ... done
  Created wheel for mplcursors: filename=mplcursors-0.5.1-py3-none-any.whl size=20815 sha256=f7045b4d7f2fe42aab5f25eb3c69cf1f0ca638da62badf193ed59afe48391edd
  Stored in directory: c:\users\administrator\appdata\local\pip\cache\wheels\90\5e\db\c20b4c1dd6ac92b9cc8aa11f7221f648c23883dc2e3a5d2408
  Building wheel for winshell (setup.py) ... done
  Created wheel for winshell: filename=winshell-0.6-py3-none-any.whl size=9415 sha256=df3ace77ff23c0c8daacef17cf0274bc2734e597f171e366107766139ba9e488
  Stored in directory: c:\users\administrator\appdata\local\pip\cache\wheels\9a\a6\54\ea888ff725d735d65c1e552f28c528291e30ee7afbbd599a81
Successfully built mlrose-hiive adodbapi mplcursors winshell
Installing collected packages: six, urllib3, python-dateutil, pyparsing, numpy, jmespath, threadpoolctl, scipy, pytz, pillow, packaging, kiwisolver, joblib, fonttools, cycler, botocore, scikit-learn, s3transfer, PyQt5-sip, pandas, networkx, matplotlib, idna, colorama, charset-normalizer, winshell, websocket-client, TurbineClient, tqdm, requests, pywin32, PyQt5, psutil, mplcursors, mlrose-hiive, cma, boto3, adodbapi, ccsi-foqus
Successfully installed PyQt5-5.13.0 PyQt5-sip-12.9.1 TurbineClient-3.1.0 adodbapi-2.6.2.0 boto3-1.21.6 botocore-1.24.6 ccsi-foqus-3.12.0 charset-normalizer-2.0.12 cma-3.1.0 colorama-0.4.4 cycler-0.11.0 fonttools-4.29.1 idna-3.3 jmespath-0.10.0 joblib-1.1.0 kiwisolver-1.3.2 matplotlib-3.5.1 mlrose-hiive-2.1.3 mplcursors-0.5.1 networkx-2.6.3 numpy-1.22.2 packaging-21.3 pandas-1.4.1 pillow-9.0.1 psutil-5.9.0 pyparsing-3.0.7 python-dateutil-2.8.2 pytz-2021.3 pywin32-225 requests-2.27.1 s3transfer-0.5.1 scikit-learn-1.0.2 scipy-1.8.0 six-1.16.0 threadpoolctl-3.1.0 tqdm-4.62.3 urllib3-1.26.8 websocket-client-1.2.3 winshell-0.6

(ccsi-foqus) C:\Users\Administrator>python
Python 3.8.12 (default, Oct 12 2021, 03:01:40) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import adodbapi
>>>
```

**Comment by boverhof** [comment]
@bpaul4 So there are a couple differences between the environments
- Windows 2016 Server vs Windows 10
- You installed for a user, I installed for all users

**Comment by bpaul4** [comment]
@boverhof Thank you for investigating this. I looked in my environment folder, and found that my `adodbapi` package was missing the module `apibase`. An extraneous metadata folder for an old `numpy` version was blocking new package installation, and removing this folder, uninstalling and reinstalling `adodbapi` resolved the issue.

**Comment by ksbeattie** [comment]
@bpaul4 can this issue be closed now?  If so, please go ahead and close it.
