### ISSUE TITLE
ImportError: DLL load failed while importing win32process:

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/FOQUS#1024]
# Description
Problem finding a DLL when running foqus, maybe a path problem.

```
(base) C:\Users\Administrator>conda env list
# conda environments:
#
base                  *  C:\tools\Anaconda3
foqus                    C:\tools\Anaconda3\envs\foqus




(base) C:\Users\Administrator>conda activate foqus

(foqus) C:\Users\Administrator>echo %PATH%
C:\tools\Anaconda3\envs\foqus;C:\tools\Anaconda3\envs\foqus\Library\mingw-w64\bin;C:\tools\Anaconda3\envs\foqus\Library\usr\bin;C:\tools\Anaconda3\envs\foqus\Library\bin;C:\tools\Anaconda3\envs\foqus\Scripts;C:\tools\Anaconda3\envs\foqus\bin;C:\tools\Anaconda3\envs\foqus;C:\tools\Anaconda3\envs\foqus\Library\mingw-w64\bin;C:\tools\Anaconda3\envs\foqus\Library\usr\bin;C:\tools\Anaconda3\envs\foqus\Library\bin;C:\tools\Anaconda3\envs\foqus\Scripts;C:\tools\Anaconda3\envs\foqus\bin;C:\tools\Anaconda3\envs\foqus\condabin;C:\tools\Anaconda3;C:\tools\Anaconda3\Library\mingw-w64\bin;C:\tools\Anaconda3\Library\usr\bin;C:\tools\Anaconda3\Library\bin;C:\tools\Anaconda3\Scripts;C:\tools\Anaconda3\bin;C:\tools\Anaconda3\condabin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files\Amazon\cfn-bootstrap;C:\ProgramData\chocolatey\bin;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64_win\compiler;C:\Program Files (x86)\Common Files\AspenTech Shared;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Common Files\AspenTech Shared

(foqus) C:\Users\Administrator>

(foqus) C:\Users\Administrator>foqus
Traceback (most recent call last):
  File "C:\tools\Anaconda3\envs\foqus\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\tools\Anaconda3\envs\foqus\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\tools\Anaconda3\envs\foqus\Scripts\foqus.exe\__main__.py", line 4, in <module>
  File "C:\tools\Anaconda3\envs\foqus\lib\site-packages\foqus_lib\foqus.py", line 35, in <module>
    from foqus_lib.framework.session.session import *
  File "C:\tools\Anaconda3\envs\foqus\lib\site-packages\foqus_lib\framework\session\session.py", line 31, in <module>
    from foqus_lib.framework.graph.graph import *
  File "C:\tools\Anaconda3\envs\foqus\lib\site-packages\foqus_lib\framework\graph\graph.py", line 37, in <module>
    from foqus_lib.framework.graph.node import *  # Node, input var and output var classes
  File "C:\tools\Anaconda3\envs\foqus\lib\site-packages\foqus_lib\framework\graph\node.py", line 37, in <module>
    from foqus_lib.framework.sim.turbineConfiguration import TurbineInterfaceEx
  File "C:\tools\Anaconda3\envs\foqus\lib\site-packages\foqus_lib\framework\sim\turbineConfiguration.py", line 47, in <module>
    import win32process
ImportError: DLL load failed while importing win32process: The specified module could not be found.

(foqus) C:\Users\Administrator>
```

**Comment by boverhof** [comment]
# FIX
- https://github.com/mhammond/pywin32
- details similar problem, run this script to fix issue

```
(foqus) C:\Users\Administrator\Desktop\FOQUS>python C:\tools\Anaconda3\envs\foqus\Scripts\pywin32_postinstall.py -install
Parsed arguments are: Namespace(destination='C:\\tools\\Anaconda3\\envs\\foqus\\Lib\\site-packages', install=True, quiet=False, remove=False, silent=False, wait=None)
Copied pythoncom38.dll to C:\Windows\system32\pythoncom38.dll
Copied pywintypes38.dll to C:\Windows\system32\pywintypes38.dll
Registered: Python.Interpreter
Registered: Python.Dictionary
Registered: Python
-> Software\Python\PythonCore\3.8\Help[None]=None
-> Software\Python\PythonCore\3.8\Help\Pythonwin Reference[None]='C:\\tools\\Anaconda3\\envs\\foqus\\Lib\\site-packages\\PyWin32.chm'
Registered help file
Pythonwin has been registered in context menu
Creating directory C:\tools\Anaconda3\envs\foqus\Lib\site-packages\win32com\gen_py
Can't install shortcuts - 'C:\\Users\\Administrator\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Python 3.8' is not a folder
The pywin32 extensions were successfully installed.

(foqus) C:\Users\Administrator\Desktop\FOQUS>
(foqus) C:\Users\Administrator\Desktop\FOQUS>
(foqus) C:\Users\Administrator\Desktop\FOQUS>python -c "import win32process as p ; print(p)"
<module 'win32process' from 'C:\\tools\\Anaconda3\\envs\\foqus\\lib\\site-packages\\win32\\win32process.pyd'>

(foqus) C:\Users\Administrator\Desktop\FOQUS>
```

**Comment by boverhof** [comment]
# Appears base ENV still works 
```
(base) C:\Users\Administrator>python -c "import win32process as p; print(p)"
<module 'win32process' from 'C:\\tools\\Anaconda3\\lib\\site-packages\\win32\\win32process.pyd'>

(base) C:\Users\Administrator>
(base) C:\Users\Administrator>
```

**Comment by boverhof** [comment]
# New Path
- not sure this is the reason
```
(foqus) C:\Users\Administrator>echo %PATH%
C:\tools\Anaconda3\envs\foqus;C:\tools\Anaconda3\envs\foqus\Library\mingw-w64\bin;C:\tools\Anaconda3\envs\foqus\Library\usr\bin;C:\tools\Anaconda3\envs\foqus\Library\bin;C:\tools\Anaconda3\envs\foqus\Scripts;C:\tools\Anaconda3\envs\foqus\bin;C:\tools\Anaconda3\condabin;C:\Program Files\Microsoft MPI\Bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn;C:\Program Files\Microsoft SQL Server\130\DTS\Binn;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio;C:\Program Files\Amazon\cfn-bootstrap;C:\ProgramData\chocolatey\bin;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;.
```
