### ISSUE TITLE
AWS Aspen12 VM

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/FOQUS#1025]
# Description
VM deployed on AWS us-west-2 region with installers.

You’ll need to install Aspenv12, the ZIP installer is on the VM but I didn’t set it up.  Currently what is there is all automatically deployed so I can destroy and create an identical one in about 30 minutes, so don’t worry about messing it up.

Let me know all the options you use for AspenV12. It would be great if you can tell me if this setup will work for you and validate it so I can use it as the base image for the cloud.

RDP
Host: 54.68.151.113
Username:  Administrator

## SLM server
- 3.217.145.177
* Note if this doesn't work I may need to make an entry in the hosts file

```
(base) C:\Users\Administrator>conda env list
# conda environments:
#
base                  *  C:\tools\Anaconda3
foqus                    C:\tools\Anaconda3\envs\foqus


(base) C:\Users\Administrator>conda activate foqus

(foqus) C:\Users\Administrator>python -c "import win32process as p ; print(p)
<module 'win32process' from 'C:\\tools\\Anaconda3\\envs\\foqus\\lib\\site-packages\\win32\\win32process.pyd'>

(foqus) C:\Users\Administrator>python -c "import foqus_lib as f; print(f)"
<module 'foqus_lib' from 'C:\\tools\\Anaconda3\\envs\\foqus\\lib\\site-packages\\foqus_lib\\__init__.py'>

(foqus) C:\Users\Administrator>dir Desktop\foqus2-cloud-files
 Volume in drive C has no label.
 Volume Serial Number is 64C6-219C

 Directory of C:\Users\Administrator\Desktop\foqus2-cloud-files

04/22/2022  02:25 PM    <DIR>          .
04/22/2022  02:25 PM    <DIR>          ..
04/22/2022  02:25 PM     9,224,912,428 Aspen-V12-ENG.zip
04/22/2022  02:20 PM           382,249 CompactView_1.4.16.0_Installer.exe
04/22/2022  02:25 PM         2,621,240 SSCERuntime_x64-ENU.exe
               3 File(s)  9,227,915,917 bytes
               2 Dir(s)  58,568,826,880 bytes free
```

**Comment by boverhof** [comment]
Is this right @sotorrio1?
# Add to VM/AMI image/build process
- https://anaconda.org/CCSI-Toolset/psuade-lite 
`conda install -c ccsi-toolset psuade-lite`

**Comment by sotorrio1** [comment]
@boverhof yes, that's correct

**Comment by sotorrio1** [comment]
I've been trying to test the BFB_OUU_06_09_2020.foqus simulation in OUU. I haven't hit any error mesages yet (like @anujad95 did before) but there are several exceptions thrown from the node's python script (see below).

```
#run steady state init
self.options["Script"].value = "Run_Steady"
self.runModel()
if self.calcError != -1:
    raise(Exception("Steady state homotopy failed"))
#Run optimization
self.options["Script"].value = "Init_Opt"
self.runModel()
if self.calcError != -1:
    raise(Exception("Optimization failed"))
# Update the x and f dicts from the node output
# f gets copied to the node outputs so need this 
# for now x doesn't get copied back
x, fnew = self.getValues()
for v in f:
	f[v] = fnew[v]
```

The exception "Steady state homotopy failed" gets thrown every run but still OUU manages to retrieve a value for the objective and plot up to 225 iterations. I'm re-running as of now.

**Comment by boverhof** [comment]
# Backup Database and Logs to S3 for posterity

` #
# Logs C:\ProgramData\Amazon\EC2-Windows\Launch\Log
#
$ErrorActionPreference = "Stop"
$DESKTOP = "$home\Desktop"
$BUCKET_NAME = "foqus2-vm-test-records"
$D=Get-DAte -Format "yyyy.MM.dd"
$T=Get-Date -Format "HH.mm"
function CollectLogsS3() {
  Write-Host "==== Copy TurbineLite DB"
  #Write-S3Object -BucketName $BUCKET_NAME -File 'C:\Program Files (x86)\Turbine\Lite\Data\TurbineCompactDatabase.sdf' -Key "$D/$T/TurbineCompactDatabase.sdf"
  Write-S3Object -BucketName $BUCKET_NAME -File  'C:\Users\Administrator\Desktop\test_working_dir\logs\foquscopy.log'  -Key "$D/$T/foqus.log"
}
CollectLogsS3`

**Comment by boverhof** [comment]
![Screen Shot 2022-04-28 at 6 16 45 PM](https://user-images.githubusercontent.com/738295/165871487-ca38e04c-f175-4eff-86cf-2e7d978cd9eb.png)

**Comment by boverhof** [comment]
@sotorrio1 Looks like in the "focus_lib.framework.graph.node" code it considers -1 a success. 

Seems counter-intuitive, but obviously this should be tightened up and defined better.

```
    def runTurbineCalc(self, retry=False):
       ....
        if self.calcError == -1:
            _logger.info("Job " + str(jobID) + " Finished Successfully")
       ....

```

**Comment by boverhof** [comment]
# Test Error:  Missing AspenTech 
- Run the OUU flowsheet once 
- Clearly see Turbine reporting can't open simulation
- Flowsheet interprets all calcError incorrectly
- Now sure if calcError is clearly defined
```
2022-04-29 20:17:38,958 - DEBUG - foqus.foqus_lib.framework.sim.process_management - Found Process: []
2022-04-29 20:17:38,958 - INFO - foqus.foqus_lib.framework.graph.node - Job 1 Failed will not retry
2022-04-29 20:17:38,958 - DEBUG - foqus.foqus_lib.framework.graph.node - Job 1 Results:
{"Id": 1, "Guid": "4a9c0ce0-b463-492a-860d-dc966a37e41b", "Simulation": "BFB_v11_FBS_01_26_2018", "State": "error", "Messages": ["event=setup,consumer=92fe720b-e8ae-40b8-abd5-8e1213d80069", "working directory setup finished", "Failed to open Simulation (1: Could not find Aspen Custom Modeler.  Is it installed?", "Failed to open Simulation (2: Could not find Aspen Custom Modeler.  Is it installed?", "Failed to open Simulation (3: Could not find Aspen Custom Modeler.  Is it installed?", "Failed to open Simulation (4: Could not find Aspen Custom Modeler.  Is it installed?", "event=error,consumer=92fe720b-e8ae-40b8-abd5-8e1213d80069,msg=\"Failed to open Simulation (5: Could not find Aspen Custom Modeler.  Is it installed?\""], "Input": {"BFBRGN.Cr": 1.0, "BFBRGN.Dt": 9.041, "BFBRGN.Lb": 8.886, "BFBRGNTop.Cr": 1.0, "BFBRGNTop.Dt": 9.195, "BFBRGNTop.Lb": 7.1926, "BFBadsB.Cr": 1.0, "BFBadsB.Dt": 11.897, "BFBadsB.Lb": 2.085, "BFBadsB.dx": 0.0127, "BFBadsM.Cr": 1.0, "BFBadsM.Dt": 15.0, "BFBadsM.Lb": 1.972, "BFBadsM.dx": 0.06695, "BFBadsT.Cr": 1.0, "BFBadsT.Dt": 15.0, "BFBadsT.Lb": 2.203, "BFBadsT.dx": 0.062397, "GHXfg.A_exch": 16358.0, "GHXfg.GasIn.P": 1.01325, "GHXfg.GasIn.T": 54.0, "Kd": 100.0, "MinStepSize": 0.001, "RunMode": "Steady State", "Script": "Run_Steady", "Snapshot": "", "TimeSeries": [0.0], "TimeUnits": "Hours", "dp": 0.00015, "fg_flow": 100377.0, "homotopy": 0, "printlevel": 0}, "Output": null, "Errors": [], "Status": 0, "Session": "e9cf9350-36ff-4010-8615-3516116e18aa", "Initialize": false, "Reset": false, "Visible": false, "Consumer": "92fe720b-e8ae-40b8-abd5-8e1213d80069", "Create": "2022-04-29T20:17:09.2970000", "Submit": "2022-04-29T20:17:09.4730000", "Setup": "2022-04-29T20:17:12.7830000", "Finished": "2022-04-29T20:17:30.4470000"}
2022-04-29 20:17:38,958 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - turbine configuration application url="http://localhost:8000/TurbineLite/application/"
2022-04-29 20:17:38,958 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - turbine configuration url="http://localhost:8000/TurbineLite"
2022-04-29 20:17:38,958 - ERROR - foqus.foqus_lib.framework.graph.node - Error in node python code
Traceback (most recent call last):
  File "C:\tools\Anaconda3\envs\foqus\lib\site-packages\foqus_lib\framework\graph\node.py", line 831, in runPython
    exec(self.pythonCode)
  File "<string>", line 5, in <module>
Exception: Steady state homotopy failed
```
![Screen Shot 2022-04-29 at 1 19 24 PM](https://user-images.githubusercontent.com/738295/166064202-96813190-510b-4186-9381-ef869032e0e2.png)
