### ISSUE TITLE
AWS Cloud Small Issue Log

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/FOQUS#1042]
# Description
List of small issues that would be nice to clean up

## Testing Models
Check under the process models bundle for others.
- [x] BFB OUU

### foqus-cdk-deploy ( Cloud Development Kit )
- [x] Split up into multiple stacks
- [x] Stack AWS Gateway/Lambda Rest API
- [x] Stack EC2 VM FOQUS Worker
- [x] Stack User/Queue: queue per user fanout from SNS Job Topic

## Backend
- [x] VM metadata tags ( replace User-data )
- [x]  Alerts when foqus_service exits ( publish message to SNS Alert )

## FrontEnd
node lambda and HTTP API
### foqus-sns-update: 
- [ ]  output mapping to Output
- [x] add kill or terminate functionality
- [ ] terminate create jobs, delete S3 files
- [x] SNS session.stop and session.start 
### post-session-stop
- [x] Add hook in cloud to stop all submitted jobs in queue
### post-session-start
- [x] Send session.start message to SNS Topic
## CloudWatch Metrics ( namespace: foqus-cloud-lambda )
- [ ] sns-job-event: dimensions based on embedded JSON Request dont' work
## fake-job lambda processors
- [x] create set of lambdas that process submitted jobs for testing

**Comment by boverhof** [comment]
# CloudWatch Metrics
## Metric Filter
```
[foqus-sns-requests](https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logsV2:log-groups/log-group/$252Faws$252Flambda$252FFoqusCloudStack-foqussnsupdateD515E28D-QYAyZYqk5Adf/edit-metric-filter/foqus-sns-requests)

Filter pattern
{ $.Records[0].Sns.MessageAttributes.event.Value = "job.*" }
Metric
[foqus-cloud-lambda](https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#metricsV2:namespace=foqus-cloud-lambda)
 / [sns_job_event](https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#metricsV2:query=sns_job_event)
Metric value
1
Default value
-
Unit
Count
Dimensions
event:$.Records[0].Sns.MessageAttributes.event.Value, job:$.Records[0].Sns.MessageAttributes.jobid.Value, username:$.Records[0].Sns.MessageAttributes.username.Value
Alarms
None.
```
## Log Record

```
2022-06-29T12:23:04.244-07:00

Copy
2022-06-29T19:23:04.243Z	142a91d7-5dd4-4bdf-bafa-83f7fbb6cc03	INFO	EVENT: 
```
```json
{
    "Records": [
        {
            "EventSource": "aws:sns",
            "EventVersion": "1.0",
            "EventSubscriptionArn": "arn:aws:sns:us-west-2:387057575688:FoqusCloudStack-bluesnstopicid42AA00AE-3VTWKS4FPMKW:731ca541-7fcb-418d-a72c-905a6c7a000f",
            "Sns": {
                "Type": "Notification",
                "MessageId": "172d673a-7a94-546b-8e5f-3c0cd24397a6",
                "TopicArn": "arn:aws:sns:us-west-2:387057575688:FoqusCloudStack-bluesnstopicid42AA00AE-3VTWKS4FPMKW",
                "Subject": null,
                "Message": "{\"resource\":\"job\",\"event\":\"status\",\"status\":\"setup\",\"jobid\":\"75a07a6c-7c06-43ad-b386-c651140c0e09\",\"consumer\":\"00000000-0000-0000-0000-000000000000\",\"sessionid\":\"9409a599-c600-4a53-8d5d-2e3f266b9bae\",\"Initialize\":false,\"Input\":{},\"Reset\":false,\"Simulation\":\"OUU\",\"Visible\":false}",
                "Timestamp": "2022-06-29T19:23:03.542Z",
                "SignatureVersion": "1",
                "Signature": "QMaqkYMrAPOELN6rO5rZs3Jub14R15ZCwQkCvmynJxDtdzUh6XyQRFIYYjSqfQLg8xMWCvSov3QO/XyPbiyVNBQ/in8KvE4Dn/Hu4Zt5qfTPPETKPNbOZC5D1pgCjoWZ4Ru+lQnsXyTj2G+O+FgrshFe3dDOpuYz8+Qns/X8K/8jZzZe6zYAs2CKTy1sqomod7YxK9dhqHflCzZjNKksBRAyyBS40yWdCNlNhzeUbsNjW7ajCKzQel2slW6IG+WV5LOyD3H8Yoeeznbkb+NWs7T60bvY74cDJ49XzTP3hpzPkmlqwoO6cMqCWof8oxpQQ9sEWbTikbw0F2u2YHoqwQ==",
                "SigningCertUrl": "https://sns.us-west-2.amazonaws.com/SimpleNotificationService-7ff5318490ec183fbaddaa2a969abfda.pem",
                "UnsubscribeUrl": "https://sns.us-west-2.amazonaws.com/?Action=Unsubscribe&SubscriptionArn=arn:aws:sns:us-west-2:387057575688:FoqusCloudStack-bluesnstopicid42AA00AE-3VTWKS4FPMKW:731ca541-7fcb-418d-a72c-905a6c7a000f",
                "MessageAttributes": {
                    "event": {
                        "Type": "String",
                        "Value": "job.setup"
                    },
                    "username": {
                        "Type": "String",
                        "Value": "boverhof"
                    }
                }
            }
        }
    ]
}
```

**Comment by boverhof** [comment]
# Deploy
## Stack VM
Specify Queue in user-data 
```
PS C:\Users\Administrator> $response = Invoke-WebRequest -Uri "http://169.254.169.254/latest/user-data"
PS C:\Users\Administrator> $response.RawContent
HTTP/1.1 200 OK
Connection: close
Accept-Ranges: none
Content-Length: 471
Content-Type: application/octet-stream
Date: Mon, 01 Aug 2022 18:46:03 GMT
Last-Modified: Mon, 01 Aug 2022 18:29:24 GMT
Server: EC2ws

{
  "FOQUS-Update-Topic-Arn": "arn:aws:sns:us-west-2:387057575688:FoqusCloudStack-bluejobtopicidA63AF7BE-NY5APVGJL24B",
  "FOQUS-Message-Topic-Arn": "arn:aws:sns:us-west-2:387057575688:FoqusCloudStack-bluelogtopicid50E21335-PBVQAP0RYZ5D",
  "FOQUS-Job-Queue-Url": "arn:aws:sqs:us-west-2:387057575688:FoqusCloudUserStack-blueboverhofqueueidEDBC6161-zgo4wkNousq
m",
  "FOQUS-Simulation-Bucket-Name": "arn:aws:s3:::foquscloudstack-bluefoqussimulation99ec6532-170r4pwindi5n"
}
PS C:\Users\Administrator>
```

**Comment by boverhof** [comment]
# Tags
![Uploading Screen Shot 2022-08-01 at 3.29.54 PM.png…]()

**Comment by boverhof** [comment]
# FOQUS Backend Metrics
- count of queue peeks
- dimensions:  empty (nothing in queue returned none), or start ( reset count to zero or found job) )
![Screen Shot 2022-08-02 at 10 20 08 AM](https://user-images.githubusercontent.com/738295/182435796-407ba21b-e933-4fb7-81dc-2f9492d55567.png)

**Comment by boverhof** [comment]
# TAG: FOQUS-Alert-Topic-Arn
- foqus_service exists send message to this topic, which emails alert
<img width="910" alt="Screen Shot 2022-08-03 at 12 41 42 PM" src="https://user-images.githubusercontent.com/738295/182695226-325acac4-f0cb-41af-a6ca-a79e0159eed7.png">

**Comment by boverhof** [comment]
# Bad Flowsheet
```
2022-08-03 19:44:12,856 - INFO - foqus.foqus_lib.service.flowsheet - TurbineLiteDB.consumer_status
2022-08-03 19:44:12,856 - DEBUG - foqus.foqus_lib.framework.graph.nodeVars - Cannot load variable node not in flowsheet, node: BFB not in []
2022-08-03 19:44:12,856 - ERROR - foqus.foqus_lib.service.flowsheet - run_foqus Exception
Traceback (most recent call last):
  File "c:\users\administrator\desktop\foqus\foqus_lib\service\flowsheet.py", line 849, in _run
    self.run_foqus(db, job_desc)
  File "c:\users\administrator\desktop\foqus\foqus_lib\service\flowsheet.py", line 1186, in run_foqus
    dat.flowsheet.loadValues(gt.res[0])
  File "c:\users\administrator\desktop\foqus\foqus_lib\framework\graph\graph.py", line 393, in loadValues
    self.input_vectorlist.loadValues(o)
  File "c:\users\administrator\desktop\foqus\foqus_lib\framework\graph\nodeVars.py", line 412, in loadValues
    raise NodeVarListEx(2, msg=node)
foqus_lib.framework.graph.nodeVars.NodeVarListEx: 2 - Node does not exist, BFB
line: 705 file: c:\users\administrator\desktop\foqus\foqus_lib\service\flowsheet.py
   self._run()
line: 849 file: c:\users\administrator\desktop\foqus\foqus_lib\service\flowsheet.py
   self.run_foqus(db, job_desc)
line: 1186 file: c:\users\administrator\desktop\foqus\foqus_lib\service\flowsheet.py
   dat.flowsheet.loadValues(gt.res[0])
line: 393 file: c:\users\administrator\desktop\foqus\foqus_lib\framework\graph\graph.py
   self.input_vectorlist.loadValues(o)
line: 412 file: c:\users\administrator\desktop\foqus\foqus_lib\framework\graph\nodeVars.py
   raise NodeVarListEx(2, msg=node)

2022-08-03 19:44:12,856 - DEBUG - foqus.foqus_lib.service.flowsheet - FOQUSAWSConfig._get: FOQUS-User = boverhof
2022-08-03 19:44:12,919 - INFO - foqus.foqus_lib.framework.sim.turbineConfiguration - Terminating Consumer {7CC29DBE-A35F-4380-B30A-19381E89400B} posting to http://localhost:8000/TurbineLite/Consumer/{7CC29DBE-A35F-4380-B30A-19381E89400B}/stop
2022-08-03 19:44:16,968 - DEBUG - foqus.foqus_lib.framework.sim.process_management - Found Process: [psutil.Process(pid=4732, name='sim_server.exe', status='running', started='19:43:08')]
2022-08-03 19:44:16,968 - DEBUG - foqus.foqus_lib.framework.sim.process_management - Terminate process PID=4732 Name=sim_server.exe Username=NT AUTHORITY\SYSTEM
2022-08-03 19:44:16,999 - DEBUG - foqus.foqus_lib.framework.sim.process_management - process psutil.Process(pid=4732, name='sim_server.exe', status='terminated', exitcode=15, started='19:43:08') terminated with exit code 15
2022-08-03 19:44:16,999 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - Stopped all running consumers
2022-08-03 19:44:17,030 - DEBUG - foqus.foqus_lib.framework.sim.process_management - Found Process: []
2022-08-03 19:44:17,030 - ERROR - foqus.foqus_lib.service.flowsheet - exit: foqus_service unhandled exception
Traceback (most recent call last):
  File "c:\users\administrator\desktop\foqus\foqus_lib\service\flowsheet.py", line 705, in run
    self._run()
  File "c:\users\administrator\desktop\foqus\foqus_lib\service\flowsheet.py", line 849, in _run
    self.run_foqus(db, job_desc)
  File "c:\users\administrator\desktop\foqus\foqus_lib\service\flowsheet.py", line 1186, in run_foqus
    dat.flowsheet.loadValues(gt.res[0])
  File "c:\users\administrator\desktop\foqus\foqus_lib\framework\graph\graph.py", line 393, in loadValues
    self.input_vectorlist.loadValues(o)
  File "c:\users\administrator\desktop\foqus\foqus_lib\framework\graph\nodeVars.py", line 412, in loadValues
    raise NodeVarListEx(2, msg=node)
foqus_lib.framework.graph.nodeVars.NodeVarListEx: 2 - Node does not exist, BFB
line: 705 file: c:\users\administrator\desktop\foqus\foqus_lib\service\flowsheet.py
   self._run()
line: 849 file: c:\users\administrator\desktop\foqus\foqus_lib\service\flowsheet.py
   self.run_foqus(db, job_desc)
line: 1186 file: c:\users\administrator\desktop\foqus\foqus_lib\service\flowsheet.py
   dat.flowsheet.loadValues(gt.res[0])
line: 393 file: c:\users\administrator\desktop\foqus\foqus_lib\framework\graph\graph.py
   self.input_vectorlist.loadValues(o)
line: 412 file: c:\users\administrator\desktop\foqus\foqus_lib\framework\graph\nodeVars.py
   raise NodeVarListEx(2, msg=node)

2022-08-03 19:44:17,030 - DEBUG - foqus.foqus_lib.service.flowsheet - FOQUSAWSConfig._get: FOQUS-Alert-Topic-Arn = arn:aws:sns:us-west-2:387057575688:FoqusCloudWatchAlarmTopic
2022-08-03 19:44:17,030 - ERROR - foqus.foqus_lib.service.flowsheet - publish(arn:aws:sns:us-west-2:387057575688:FoqusCloudWatchAlarmTopic) service error: NodeVarListEx(2)
2022-08-03 19:44:17,109 - INFO - foqus.foqus_lib.service.flowsheet - published
```

**Comment by boverhof** [comment]
# VM Contextualization:  Changed from UserData to Tags
- Previously used UserData to dump in information to the VM, but wanted to use that UserData for running arbitrary scripts via Cloud-Init to make it possible to add runtime dependencies when a VM is started ( example python ideas module )
- Now this is represented via Tags of the Instance.

```


FOQUS-Update-Topic-Arn | arn:aws:sns:us-west-1:ACCOUNT_NUMBER:FoqusCloudStack-green-greenjobtopicidD0B6AB05-w0NwjR3KWM9m
-- | --
Name | FoqusCloudWorker
aws:cloudformation:stack-id | arn:aws:cloudformation:us-west-1:ACCOUNT_NUMBER:stack/FoqusCloudWorkerStack-green-boverhof/d1910dd0-4445-11ed-bae3-0201a4ac5bcd
FOQUS-Session-Bucket-Name | foquscloudstack-green-greenfoqussession06d3597f-1l0s609d4i037
FOQUS-Message-Topic-Arn | arn:aws:sns:us-west-1:ACCOUNT_NUMBER:FoqusCloudStack-green-greenlogtopicidF0952794-UVEhpadkYozZ
FOQUS-Job-Queue-Url | https://sqs.us-west-1.amazonaws.com/ACCOUNT_NUMBER/FoqusCloudUserStack-green-boverhof-boverhofjobqueueid270A2608-Kvxg7NReO2BY
FOQUS-Stack | Worker
FOQUS-User | boverhof
aws:cloudformation:stack-name | FoqusCloudWorkerStack-green-boverhof
aws:cloudformation:logical-id | InstanceC1063A87


```

**Comment by ksbeattie** [comment]
@boverhof, looks like this is, at least partly, complete.  Can we close it and/or move existing items to a new issue for the Dec release board?
