### ISSUE TITLE
Turbine Upload Error

### ISSUE THREAD

**Issue by LNemetz** [CCSI-Toolset/FOQUS#1052]
When I go to add/update model to turbine I get the following error:

![image](https://user-images.githubusercontent.com/76179027/187772015-8b13858b-e579-4206-9d3b-02acf75731ad.png)

And when I try to open pervious sessions I get The following messages:

![image](https://user-images.githubusercontent.com/76179027/187772448-32b0c70d-b26d-4c45-b5b1-ebc51828723d.png)

**Comment by ksbeattie** [comment]
Can you paste the debug log when this happens?  You can find that in the Help section, under the debug tab.  This should help us better understand the problem.

**Comment by LNemetz** [comment]
Opening add/update model to turbine 
![image](https://user-images.githubusercontent.com/76179027/189159688-7e82b5e3-c53b-4c60-a1f2-6b2e546b3454.png)
Add model fails This shows:
![image](https://user-images.githubusercontent.com/76179027/189159766-8934f417-0fb9-4e52-9126-6051b516ebf9.png)

**Comment by LNemetz** [comment]
I have stopping and started Turbine WEB API service but doing this made no change. 
I have used both the foqus built in stop/start buttons in settings and going to the service window directly. 
I have also tried restarting Turbine WEB API service and nothing changed.

**Comment by LNemetz** [comment]
When I open a recent file I get:
2022-09-12 13:29:22,085 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - turbine configuration application url="http://localhost:8000/TurbineLite/application/"
2022-09-12 13:29:22,086 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - turbine configuration url="http://localhost:8000/TurbineLite"
2022-09-12 15:00:32,287 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - Stopped all running consumers
2022-09-12 15:00:32,766 - DEBUG - foqus.foqus_lib.framework.sim.process_management - Found Process: [psutil.Process(pid=16084, name='sim_server.exe', status='running', started='10:30:42'), psutil.Process(pid=25192, name='am_task_server.exe', status='running', started='10:30:42')]
2022-09-12 15:00:32,767 - DEBUG - foqus.foqus_lib.framework.sim.process_management - Terminate process PID=16084 Name=sim_server.exe Username=UTAD\lnemetz
2022-09-12 15:00:32,768 - DEBUG - foqus.foqus_lib.framework.sim.process_management - Terminate process PID=25192 Name=am_task_server.exe Username=UTAD\lnemetz
2022-09-12 15:00:32,821 - DEBUG - foqus.foqus_lib.framework.sim.process_management - process psutil.Process(pid=16084, name='sim_server.exe', status='terminated', exitcode=15, started='10:30:42') terminated with exit code 15
2022-09-12 15:00:32,832 - DEBUG - foqus.foqus_lib.framework.sim.process_management - process psutil.Process(pid=25192, name='am_task_server.exe', status='terminated', exitcode=15, started='10:30:42') terminated with exit code 15
2022-09-12 15:00:32,838 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - turbine configuration application url="http://localhost:8000/TurbineLite/application/"
2022-09-12 15:00:32,838 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - turbine configuration url="http://localhost:8000/TurbineLite"

**Comment by LNemetz** [comment]
2022-09-12 15:03:21,149 - ERROR - foqus.foqus_lib.framework.sim.turbineConfiguration - Error getting list of simulation from Turbine
Traceback (most recent call last):
File "C:\Anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\sim\turbineConfiguration.py", line 668, in getSimulationList
main_list([self.getFile()], None)
File "C:\Anaconda3\envs\ccsi-foqus\lib\site-packages\turbine\commands\turbine_simulation_script.py", line 207, in main_list
data = load_pages_json([content])
File "C:\Anaconda3\envs\ccsi-foqus\lib\site-packages\turbine\commands\__init__.py", line 536, in load_pages_json
data += json.loads(p)
File "C:\Anaconda3\envs\ccsi-foqus\lib\json\__init__.py", line 348, in loads
return _default_decoder.decode(s)
File "C:\Anaconda3\envs\ccsi-foqus\lib\json\decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "C:\Anaconda3\envs\ccsi-foqus\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022-09-12 15:03:21,150 - DEBUG - foqus.foqus_lib.gui.flowsheet.nodePanel - Could not connect to Turbine in checkSim() Is the Turbine web service running?
2022-09-12 15:03:22,470 - ERROR - foqus.foqus_lib.framework.sim.turbineConfiguration - Error getting list of simulation from Turbine
Traceback (most recent call last):
File "C:\Anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\sim\turbineConfiguration.py", line 668, in getSimulationList
main_list([self.getFile()], None)
File "C:\Anaconda3\envs\ccsi-foqus\lib\site-packages\turbine\commands\turbine_simulation_script.py", line 207, in main_list
data = load_pages_json([content])
File "C:\Anaconda3\envs\ccsi-foqus\lib\site-packages\turbine\commands\__init__.py", line 536, in load_pages_json
data += json.loads(p)
File "C:\Anaconda3\envs\ccsi-foqus\lib\json\__init__.py", line 348, in loads
return _default_decoder.decode(s)
File "C:\Anaconda3\envs\ccsi-foqus\lib\json\decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "C:\Anaconda3\envs\ccsi-foqus\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022-09-12 15:03:22,471 - DEBUG - foqus.foqus_lib.gui.flowsheet.nodePanel - Could not connect to Turbine in checkSim() Is the Turbine web service running?

**Comment by boverhof** [comment]
@LNemetz I'm not sure what the root cause is of the problems.  One thing to check is what the Web Service is returning.  So if you open a browser and go to 
`http://localhost:8000/TurbineLite/simulation/`
Should give you an empty list or JSON array.  
`[]`

Maybe it's sending an HTTP Error and that isn't being understood or handled correctly..

**Comment by LNemetz** [comment]
I used google chrome and pasted: http://localhost:8000/TurbineLite/simulation/ and got:
![image](https://user-images.githubusercontent.com/76179027/190003803-8f0ccc4e-5f70-4235-b0bb-ad7441ffb437.png)

The server encountered an error processing the request. The exception message is 'An error occurred while reading from the store provider's data reader. See the inner exception for details.'. See server logs for more details. The exception stack trace is:

at System.Data.Entity.Core.Common.Internal.Materialization.Shaper`1.HandleReaderException(Exception e) at System.Data.Entity.Core.Common.Internal.Materialization.Shaper`1.StoreRead() at System.Data.Entity.Core.Common.Internal.Materialization.Shaper`1.SimpleEnumerator.MoveNext() at Turbine.Lite.Web.Resources.Contracts.DataMarshal.GetSimulations(Boolean allSimulations) in c:\Users\boverhof\Documents\Visual Studio 2012\Projects\turb_sci_gate\Master\Turbine.Lite.Web.Resources\Contracts\DataMarshall.cs:line 108 at Turbine.Lite.Web.Resources.SimulationResource.GetSimulations() in c:\Users\boverhof\Documents\Visual Studio 2012\Projects\turb_sci_gate\Master\Turbine.Lite.Web.Resources\SimulationResource.cs:line 51 at SyncInvokeGetSimulations(Object , Object[] , Object[] ) at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs) at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc) at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc& rpc) at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage11(MessageRpc& rpc) at System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet)

**Comment by LNemetz** [comment]
I uninstalled turbine and Simsinter. Then reinstalled them both following the direction from the Read the doc page.
This fixed the issue I was having. 
I am able to upload models to turbine and open previous sessions.
