### ISSUE TITLE
Documenting Turbine "Node Error 8 - Fail to start" Solution

### ISSUE THREAD

**Issue by bpaul4** [CCSI-Toolset/FOQUS#1073]
The error below occurred when attempting to run Tutorial 2 with `ccsi-foqus 3.15` and `TurbineClient 4.0.2`.

Reinstalling FOQUS via
```
pip uninstall --yes ccsi-foqus
pip install ccsi-foqus==3.15
```
resolved the issue, as `TurbineClient 4.0.2` is only compatible with the 3.15 release of FOQUS.

The FOQUS log:

```
2022-10-12 16:21:43,854 - ERROR - foqus.foqus_lib.framework.graph.node - Failed to check for existence of session while creating session, Exception:
Traceback (most recent call last):
File "C:\Users\katherine.hedrick\Anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\sim\turbineConfiguration.py", line 753, in getSessionList
l = turbine.commands.turbine_session_script.main_list(
TypeError: main_list() takes from 0 to 1 positional arguments but 2 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\katherine.hedrick\Anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\graph\node.py", line 1450, in createTurbineSession
if self.gr.turbConfig.sessionExists(self.turbSession):
File "C:\Users\katherine.hedrick\Anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\sim\turbineConfiguration.py", line 837, in sessionExists
l = self.getSessionList()
File "C:\Users\katherine.hedrick\Anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\sim\turbineConfiguration.py", line 758, in getSessionList
raise TurbineInterfaceEx(
foqus_lib.framework.sim.turbineConfiguration.TurbineInterfaceEx: 0 - Unknown Error, Error getting session list.
Traceback (most recent call last):
File "C:\Users\katherine.hedrick\Anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\sim\turbineConfiguration.py", line 753, in getSessionList
l = turbine.commands.turbine_session_script.main_list(
TypeError: main_list() takes from 0 to 1 positional arguments but 2 were given


2022-10-12 16:21:43,855 - WARNING - foqus.foqus_lib.framework.graph.graph - Problem getting session id for node: BFB
2022-10-12 16:21:43,860 - ERROR - foqus.foqus_lib.framework.graph.node - Failed to check for existence of session while creating session, Exception:
Traceback (most recent call last):
File "C:\Users\katherine.hedrick\Anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\sim\turbineConfiguration.py", line 753, in getSessionList
l = turbine.commands.turbine_session_script.main_list(
TypeError: main_list() takes from 0 to 1 positional arguments but 2 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\katherine.hedrick\Anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\graph\node.py", line 1450, in createTurbineSession
if self.gr.turbConfig.sessionExists(self.turbSession):
File "C:\Users\katherine.hedrick\Anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\sim\turbineConfiguration.py", line 837, in sessionExists
l = self.getSessionList()
File "C:\Users\katherine.hedrick\Anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\sim\turbineConfiguration.py", line 758, in getSessionList
raise TurbineInterfaceEx(
foqus_lib.framework.sim.turbineConfiguration.TurbineInterfaceEx: 0 - Unknown Error, Error getting session list.
Traceback (most recent call last):
File "C:\Users\katherine.hedrick\Anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\sim\turbineConfiguration.py", line 753, in getSessionList
l = turbine.commands.turbine_session_script.main_list(
TypeError: main_list() takes from 0 to 1 positional arguments but 2 were given


2022-10-12 16:21:43,861 - WARNING - foqus.foqus_lib.framework.graph.graph - Problem getting session id for node: Cost
2022-10-12 16:21:43,873 - DEBUG - foqus.foqus_lib.framework.graph.graph - run: Running flowsheet(s) locally
2022-10-12 16:21:43,877 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - turbine configuration application url="http://localhost:8000/TurbineLite/application/"
2022-10-12 16:21:43,881 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - turbine configuration url="http://localhost:8000/TurbineLite"
2022-10-12 16:21:43,887 - ERROR - foqus.foqus_lib.framework.graph.node - Failed to check for existence of session while creating session, Exception:
Traceback (most recent call last):
File "C:\Users\katherine.hedrick\Anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\sim\turbineConfiguration.py", line 753, in getSessionList
l = turbine.commands.turbine_session_script.main_list(
TypeError: main_list() takes from 0 to 1 positional arguments but 2 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\katherine.hedrick\Anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\graph\node.py", line 1450, in createTurbineSession
if self.gr.turbConfig.sessionExists(self.turbSession):
File "C:\Users\katherine.hedrick\Anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\sim\turbineConfiguration.py", line 837, in sessionExists
l = self.getSessionList()
File "C:\Users\katherine.hedrick\Anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\sim\turbineConfiguration.py", line 758, in getSessionList
raise TurbineInterfaceEx(
foqus_lib.framework.sim.turbineConfiguration.TurbineInterfaceEx: 0 - Unknown Error, Error getting session list.
Traceback (most recent call last):
File "C:\Users\katherine.hedrick\Anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\sim\turbineConfiguration.py", line 753, in getSessionList
l = turbine.commands.turbine_session_script.main_list(
TypeError: main_list() takes from 0 to 1 positional arguments but 2 were given


2022-10-12 16:21:43,888 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - Starting simulation consumer...
2022-10-12 16:21:43,889 - DEBUG - foqus.foqus_lib.framework.graph.node - Generated Job JSON:
[
{
"ConsumerId": "{980ACD19-D395-4A08-B414-A60161423ECB}",
"Initialize": false,
"Input": {
"BFBadsB.Lb": 4.2,
"BFBadsM.Lb": 4.2,
"BFBadsT.Lb": 4.2,
"BFBrgnB.Lb": 4.2,
"BFBrgnT.Lb": 4.2,
"GHXfg.GasOut.T": 40.0,
"MinStepSize": 0.001,
"RunMode": "Steady State",
"Script": "",
"Snapshot": "",
"SolidIn.Fm": 600000.0,
"TimeSeries": [
0.0
],
"TimeUnits": "Hours",
"adsDt": 15.0,
"adsN": 15.0,
"adsdx": 0.0275,
"adslhx": 0.4,
"homotopy": 1,
"printlevel": 0,
"rgnDt": 12.0,
"rgnN": 15.0,
"rgnSF": 0.3,
"rgndx": 0.0225,
"rgnlhx": 0.08,
"steam.F": 800.0
},
"Reset": false,
"Simulation": "BFB_v6_2",
"Visible": false
}
]
2022-10-12 16:21:43,968 - ERROR - foqus.foqus_lib.framework.sim.turbineConfiguration - Error starting session
Traceback (most recent call last):
File "C:\Users\katherine.hedrick\Anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\sim\turbineConfiguration.py", line 820, in startSession
output = turbine.commands.turbine_session_script.start_jobs(
File "C:\Users\katherine.hedrick\Anaconda3\envs\ccsi-foqus\lib\site-packages\turbine\commands\turbine_session_script.py", line 255, in start_jobs
return post_page(
File "C:\Users\katherine.hedrick\Anaconda3\envs\ccsi-foqus\lib\site-packages\turbine\commands\requests_base.py", line 173, in post_page
raise HTTPStatusCode(r)
turbine.commands.requests_base.HTTPStatusCode: (HTTPStatusCode(...), 'HTTP(400) - b\'\\xef\\xbb\\xbf<?xml version="1.0" encoding="utf-8"?>\\r\\n<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\\r\\n<html xmlns="http://www.w3.org/1999/xhtml">\\r\\n  <head>\\r\\n    <title>Request Error</title>\\r\\n    <style>BODY { color: #000000; background-color: white; font-family: Verdana; margin-left: 0px; margin-top: 0px; } #content { margin-left: 30px; font-size: .70em; padding-bottom: 2em; } A:link { color: #336699; font-weight: bold; text-decoration: underline; } A:visited { color: #6699cc; font-weight: bold; text-decoration: underline; } A:active { color: #336699; font-weight: bold; text-decoration: underline; } .heading1 { background-color: #003366; border-bottom: #336699 6px solid; color: #ffffff; font-family: Tahoma; font-size: 26px; font-weight: normal;margin: 0em 0em 10px -20px; padding-bottom: 8px; padding-left: 30px;padding-top: 16px;} pre { font-size:small; background-color: #e5e5cc; padding: 5px; font-family: Courier New; margin-top: 0px; border: 1px #f0f0e0 solid; white-space: pre-wrap; white-space: -pre-wrap; word-wrap: break-word; } table { border-collapse: collapse; border-spacing: 0px; font-family: Verdana;} table th { border-right: 2px white solid; border-bottom: 2px white solid; font-weight: bold; background-color: #cecf9c;} table td { border-right: 2px white solid; border-bottom: 2px white solid; background-color: #e5e5cc;}</style>\\r\\n  </head>\\r\\n  <body>\\r\\n    <div id="content">\\r\\n      <p class="heading1">Request Error</p>\\r\\n      <p>The server encountered an error processing the request. The exception message is \\\'Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).\\\'. See server logs for more details. The exception stack trace is: </p>\\r\\n      <p>   at System.Guid.GuidResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument, String failureArgumentName, Exception innerException)\\r\\n   at System.Guid.TryParseGuidWithNoStyle(String guidString, GuidResult&amp; result)\\r\\n   at System.Guid.TryParseGuid(String g, GuidStyles flags, GuidResult&amp; result)\\r\\n   at System.Guid..ctor(String g)\\r\\n   at Turbine.Lite.Web.Resources.SessionResource.StartSession(String sessionID) in c:\\\\Users\\\\Administrator\\\\Documents\\\\Visual Studio 2012\\\\Projects\\\\turb_sci_gate\\\\Master\\\\Turbine.Lite.Web.Resources\\\\SessionResource.cs:line 432\\r\\n   at SyncInvokeStartSession(Object , Object[] , Object[] )\\r\\n   at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]&amp; outputs)\\r\\n   at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc&amp; rpc)\\r\\n   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc&amp; rpc)\\r\\n   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage11(MessageRpc&amp; rpc)\\r\\n   at System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet)</p>\\r\\n    </div>\\r\\n  </body>\\r\\n</html>\'')
2022-10-12 16:21:43,970 - ERROR - foqus.foqus_lib.framework.graph.node - Failed start job: 0
Traceback (most recent call last):
File "C:\Users\katherine.hedrick\Anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\sim\turbineConfiguration.py", line 820, in startSession
output = turbine.commands.turbine_session_script.start_jobs(
File "C:\Users\katherine.hedrick\Anaconda3\envs\ccsi-foqus\lib\site-packages\turbine\commands\turbine_session_script.py", line 255, in start_jobs
return post_page(
File "C:\Users\katherine.hedrick\Anaconda3\envs\ccsi-foqus\lib\site-packages\turbine\commands\requests_base.py", line 173, in post_page
raise HTTPStatusCode(r)
turbine.commands.requests_base.HTTPStatusCode: (HTTPStatusCode(...), 'HTTP(400) - b\'\\xef\\xbb\\xbf<?xml version="1.0" encoding="utf-8"?>\\r\\n<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\\r\\n<html xmlns="http://www.w3.org/1999/xhtml">\\r\\n  <head>\\r\\n    <title>Request Error</title>\\r\\n    <style>BODY { color: #000000; background-color: white; font-family: Verdana; margin-left: 0px; margin-top: 0px; } #content { margin-left: 30px; font-size: .70em; padding-bottom: 2em; } A:link { color: #336699; font-weight: bold; text-decoration: underline; } A:visited { color: #6699cc; font-weight: bold; text-decoration: underline; } A:active { color: #336699; font-weight: bold; text-decoration: underline; } .heading1 { background-color: #003366; border-bottom: #336699 6px solid; color: #ffffff; font-family: Tahoma; font-size: 26px; font-weight: normal;margin: 0em 0em 10px -20px; padding-bottom: 8px; padding-left: 30px;padding-top: 16px;} pre { font-size:small; background-color: #e5e5cc; padding: 5px; font-family: Courier New; margin-top: 0px; border: 1px #f0f0e0 solid; white-space: pre-wrap; white-space: -pre-wrap; word-wrap: break-word; } table { border-collapse: collapse; border-spacing: 0px; font-family: Verdana;} table th { border-right: 2px white solid; border-bottom: 2px white solid; font-weight: bold; background-color: #cecf9c;} table td { border-right: 2px white solid; border-bottom: 2px white solid; background-color: #e5e5cc;}</style>\\r\\n  </head>\\r\\n  <body>\\r\\n    <div id="content">\\r\\n      <p class="heading1">Request Error</p>\\r\\n      <p>The server encountered an error processing the request. The exception message is \\\'Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).\\\'. See server logs for more details. The exception stack trace is: </p>\\r\\n      <p>   at System.Guid.GuidResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument, String failureArgumentName, Exception innerException)\\r\\n   at System.Guid.TryParseGuidWithNoStyle(String guidString, GuidResult&amp; result)\\r\\n   at System.Guid.TryParseGuid(String g, GuidStyles flags, GuidResult&amp; result)\\r\\n   at System.Guid..ctor(String g)\\r\\n   at Turbine.Lite.Web.Resources.SessionResource.StartSession(String sessionID) in c:\\\\Users\\\\Administrator\\\\Documents\\\\Visual Studio 2012\\\\Projects\\\\turb_sci_gate\\\\Master\\\\Turbine.Lite.Web.Resources\\\\SessionResource.cs:line 432\\r\\n   at SyncInvokeStartSession(Object , Object[] , Object[] )\\r\\n   at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]&amp; outputs)\\r\\n   at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc&amp; rpc)\\r\\n   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc&amp; rpc)\\r\\n   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage11(MessageRpc&amp; rpc)\\r\\n   at System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet)</p>\\r\\n    </div>\\r\\n  </body>\\r\\n</html>\'')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\katherine.hedrick\Anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\graph\node.py", line 1322, in runTurbineCalc
configProfile.retryFunction(5, 30, 1, configProfile.startSession, sid)
File "C:\Users\katherine.hedrick\Anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\sim\turbineConfiguration.py", line 529, in retryFunction
return function(*args, **kwargs)
File "C:\Users\katherine.hedrick\Anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\sim\turbineConfiguration.py", line 828, in startSession
msg="".join(["Error starting session. ", " Session id: ", sid]),
TypeError: sequence item 2: expected str instance, int found
2022-10-12 16:21:43,976 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - turbine configuration application url="http://localhost:8000/TurbineLite/application/"
2022-10-12 16:21:43,976 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - turbine configuration url="http://localhost:8000/TurbineLite"
```

**Comment by bpaul4** [comment]
Closing as the issue was resolved offline.
