### ISSUE TITLE
Flowsheet errorStat: 19

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/FOQUS#1087]
# Description
- AspenPlus  MEA Model
- Grabbed an old flowsheet to run it with and got this error 
- Problem appears to be missing plugin, but should get an error "19" in the results
- Flowsheet errorStat: 19
- #1070 
## Results
```
[
  {
    "Finished": "2022-11-23T21:18:46.018Z",
    "Input": {},
    "setup": "2022-11-23T21:18:39.074Z",
    "Reset": false,
    "TTL": 1669324726,
    "State": "error",
    "Create": "2022-11-23T21:18:17.840Z",
    "Type": "Job",
    "running": "2022-11-23T21:18:43.677Z",
    "Application": "foqus",
    "Initialize": false,
    "User": "boverhof",
    "submit": "2022-11-23T21:18:38.576Z",
    "Id": "7e24e09b-ca0a-4dde-b6c6-06185e450bea",
    "ConsumerId": "51b668be-dd85-4a5c-81c5-b2e463bbff9f",
    "Simulation": "MEA_SSM_Flowsheet",
    "Output": {
      "solTime": 0,
      "input": {
        "graph": {},
        "MEA_SM": {
          "MEA_UPD.GASABSIN": 2266.099,
          "MEA_UPD.REGEN_PRESSURE": 200,
          "MEA_UPD.SOLVENTABSIN": 4129.2672254507015,
          "X_SOLVENT_CALC.AMINECONC": 0.3,
          "X_SOLVENT_CALC.CO2LOADING": 0.1
        }
      },
      "output": {
        "graph": {
          "error": -1
        },
        "MEA_SM": {
          "MEA_UPD.CO2CAPTURE": 90.00000644743363,
          "MEA_UPD.SRD": 1.0778262824267415
        }
      },
      "graphError": 19,
      "nodeError": {
        "MEA_SM": -1
      },
      "nodeSettings": {
        "MEA_SM": {}
      },
      "turbineMessages": {
        "MEA_SM": "NULL"
      },
      "input_vectorvals": {},
      "output_vectorvals": {
        "MEA_SM": {}
      }
    },
    "Session": "8bf5bd1f-8ebf-425d-afc8-67daf85921f1",
    "Message": "Flowsheet errorStat: 19"
  }
]

```
## Logs
```
2022-11-23 21:18:43,666 - DEBUG - foqus.foqus_lib.service.flowsheet - _sns_notification obj: {'resource': 'job', 'event': 'status', 'rc': 0, 'status': 'running', 'jobid': '7e24e09b-ca0a-4dde-b6c6-06185e450bea', 'instanceid': 'i-07f2e04e3f6ba5ace', 'consumer': '51b668be-dd85-4a5c-81c5-b2e463bbff9f', 'sessionid': '8bf5bd1f-8ebf-425d-afc8-67daf85921f1'}
2022-11-23 21:18:43,666 - DEBUG - foqus.foqus_lib.service.flowsheet - _sns_notification event: job.running
2022-11-23 21:18:43,666 - DEBUG - foqus.foqus_lib.service.flowsheet - MessageAttributes: {'event': {'DataType': 'String', 'StringValue': 'job.running'}, 'username': {'DataType': 'String', 'StringValue': 'boverhof'}}
2022-11-23 21:18:43,682 - DEBUG - foqus.foqus_lib.framework.graph.graph - run: Running flowsheet(s) locally
2022-11-23 21:18:43,682 - ERROR - foqus.foqus_lib.framework.graph.graph - Exception in graph thread
Traceback (most recent call last):
  File "c:\users\administrator\desktop\foqus\foqus_lib\framework\graph\graph.py", line 873, in run
    self.solve()
  File "c:\users\administrator\desktop\foqus\foqus_lib\framework\graph\graph.py", line 1034, in solve
    self.runGraph(order)
  File "c:\users\administrator\desktop\foqus\foqus_lib\framework\graph\graph.py", line 1345, in runGraph
    elif self.runNode(name) != 0:
  File "c:\users\administrator\desktop\foqus\foqus_lib\framework\graph\graph.py", line 1357, in runNode
    node.runCalc()
  File "c:\users\administrator\desktop\foqus\foqus_lib\framework\graph\node.py", line 1149, in runCalc
    self.runModel()
  File "c:\users\administrator\desktop\foqus\foqus_lib\framework\graph\node.py", line 1170, in runModel
    self.runPymodelPlugin()
  File "c:\users\administrator\desktop\foqus\foqus_lib\framework\graph\node.py", line 1211, in runPymodelPlugin
    self.pyModel = self.gr.pymodels.plugins[self.modelName].pymodel_pg()
KeyError: 'alamo_surrogate_fs'
```
```

**Comment by boverhof** [comment]
# Capture the Ex sys_info 
Throw entire traceback into result
```
    "Message": "Flowsheet Error: ['Traceback (most recent call last):\\n', '  File \"c:\\\\users\\\\administrator\\\\desktop\\\\foqus\\\\foqus_lib\\\\framework\\\\graph\\\\graph.py\", line 873, in run\\n    self.solve()\\n', '  File \"c:\\\\users\\\\administrator\\\\desktop\\\\foqus\\\\foqus_lib\\\\framework\\\\graph\\\\graph.py\", line 1034, in solve\\n    self.runGraph(order)\\n', '  File \"c:\\\\users\\\\administrator\\\\desktop\\\\foqus\\\\foqus_lib\\\\framework\\\\graph\\\\graph.py\", line 1345, in runGraph\\n    elif self.runNode(name) != 0:\\n', '  File \"c:\\\\users\\\\administrator\\\\desktop\\\\foqus\\\\foqus_lib\\\\framework\\\\graph\\\\graph.py\", line 1357, in runNode\\n    node.runCalc()\\n', '  File \"c:\\\\users\\\\administrator\\\\desktop\\\\foqus\\\\foqus_lib\\\\framework\\\\graph\\\\node.py\", line 1261, in runCalc\\n    self.runModel()\\n', '  File \"c:\\\\users\\\\administrator\\\\desktop\\\\foqus\\\\foqus_lib\\\\framework\\\\graph\\\\node.py\", line 1282, in runModel\\n    self.runPymodelPlugin()\\n', '  File \"c:\\\\users\\\\administrator\\\\desktop\\\\foqus\\\\foqus_lib\\\\framework\\\\graph\\\\node.py\", line 1323, in runPymodelPlugin\\n    self.pyModel = self.gr.pymodels.plugins[self.modelName].pymodel_pg()\\n', \"KeyError: 'alamo_surrogate_fs'\\n\"]"
  }
]
```
