### ISSUE TITLE
Optimization Run Submission Exceptions

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/FOQUS#1091]
# Detail
When running an Optimization with BFB a few exceptions occur before the session is started.  The jobs are started and do process but not sure why these Exceptions are thrown.

# Logs
```
2022-12-02 21:48:57,303 - DEBUG - foqus.foqus_lib.framework.graph.graph - Created Jobs:
['4e0d080a-147f-4f0d-ac86-07290d7b4767', 'aaccf37b-4e07-4c73-a02c-5d7127930fbc', '87f48b83-937d-42d4-8cda-36a4cfb08798', 'e94bda6f-4eab-4288-bd02-d56b2f385496', 'd390b0a4-81da-47a1-9dad-01a9586a8646', '1f739a24-e233-4e50-b622-b3f69ae4461f', '29727dde-6dc8-4421-a91a-efddbded5105', '5f435c6b-eaf9-4940-a863-1c908aa01ed1', '7641877c-4136-4322-8103-fe6cb8d20470', 'da80b1e3-471b-40e5-852e-433fb744a984', '111b8719-6f09-457c-bfc6-73a690e16f27', '2884d113-a371-4e79-965b-ac04e3c035b8', 'b892dd15-0fe3-42a3-bd6e-30fe61a9a21d', 'a81058bf-0f72-43da-b021-f3139a7aeace', '2082435a-6933-4e8e-afb1-1b9e9f5d8739', '60dca9b9-4e73-4679-ba5b-9ae0e352cd30', '7cb669bd-94f5-44b7-8ba9-a1203168cb7a', '9cbef054-6cbc-4341-bb68-e32ad3542d95', 'aebe8e18-3ce1-4411-bc95-37e547ceeea4', '557b317f-45c8-448b-83f6-5aef69edb9a8']
2022-12-02 21:48:57,303 - DEBUG - foqus.foqus_lib.framework.graph.graph - sleep
2022-12-02 21:49:02,319 - DEBUG - foqus.foqus_lib.framework.graph.graph - Go
2022-12-02 21:49:02,319 - DEBUG - turbine.commands.requests_base - kw {'headers': {'Content-Type': 'application/json; charset=utf-8'}, 'subresource': '5057c129-894b-4bf5-a009-e4a7f701d411/start'}
2022-12-02 21:49:02,319 - DEBUG - turbine.commands.requests_base - read_configuration signed_url: "None"
2022-12-02 21:49:02,319 - DEBUG - turbine.commands.requests_base - post_page: "https://c1tsf1vb9a.execute-api.us-west-2.amazonaws.com/prod/session/5057c129-894b-4bf5-a009-e4a7f701d411/start" "{'headers': {'Content-Type': 'application/json; charset=utf-8'}}"
2022-12-02 21:49:02,319 - DEBUG - turbine.commands.requests_base - _post_page url: "https://c1tsf1vb9a.execute-api.us-west-2.amazonaws.com/prod/session/5057c129-894b-4bf5-a009-e4a7f701d411/start" "{}"
2022-12-02 21:49:06,350 - DEBUG - turbine.commands.requests_base - HTTP POST(502)
2022-12-02 21:49:06,350 - ERROR - foqus.foqus_lib.framework.sim.turbineConfiguration - Error starting session
Traceback (most recent call last):
  File "c:\users\administrator\desktop\foqus\foqus_lib\framework\sim\turbineConfiguration.py", line 807, in startSession
    output = _tsess.start_jobs(self.turbineConfigParse(), sid)
  File "c:\users\administrator\desktop\turb_client\turbine\commands\turbine_session_script.py", line 255, in start_jobs
    return post_page(
  File "c:\users\administrator\desktop\turb_client\turbine\commands\requests_base.py", line 173, in post_page
    raise HTTPStatusCode(r)
turbine.commands.requests_base.HTTPStatusCode: (HTTPStatusCode(...), 'HTTP(502) - b\'{"message": "Internal server error"}\'')
2022-12-02 21:49:06,366 - ERROR - foqus.foqus_lib.framework.sim.turbineConfiguration - Turbine Interface Error: Retry 1 in 20s.
Traceback (most recent call last):
  File "c:\users\administrator\desktop\foqus\foqus_lib\framework\sim\turbineConfiguration.py", line 807, in startSession
    output = _tsess.start_jobs(self.turbineConfigParse(), sid)
  File "c:\users\administrator\desktop\turb_client\turbine\commands\turbine_session_script.py", line 255, in start_jobs
    return post_page(
  File "c:\users\administrator\desktop\turb_client\turbine\commands\requests_base.py", line 173, in post_page
    raise HTTPStatusCode(r)
turbine.commands.requests_base.HTTPStatusCode: (HTTPStatusCode(...), 'HTTP(502) - b\'{"message": "Internal server error"}\'')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\administrator\desktop\foqus\foqus_lib\framework\sim\turbineConfiguration.py", line 530, in retryFunction
    return function(*args, **kwargs)
  File "c:\users\administrator\desktop\foqus\foqus_lib\framework\sim\turbineConfiguration.py", line 811, in startSession
    raise TurbineInterfaceEx(
foqus_lib.framework.sim.turbineConfiguration.TurbineInterfaceEx: 0 - Unknown Error, Error starting session.  Session id: 5057c129-894b-4bf5-a009-e4a7f701d411
Traceback (most recent call last):
  File "c:\users\administrator\desktop\foqus\foqus_lib\framework\sim\turbineConfiguration.py", line 807, in startSession
    output = _tsess.start_jobs(self.turbineConfigParse(), sid)
  File "c:\users\administrator\desktop\turb_client\turbine\commands\turbine_session_script.py", line 255, in start_jobs
    return post_page(
  File "c:\users\administrator\desktop\turb_client\turbine\commands\requests_base.py", line 173, in post_page
    raise HTTPStatusCode(r)
turbine.commands.requests_base.HTTPStatusCode: (HTTPStatusCode(...), 'HTTP(502) - b\'{"message": "Internal server error"}\'')


2022-12-02 21:49:26,382 - DEBUG - turbine.commands.requests_base - kw {'headers': {'Content-Type': 'application/json; charset=utf-8'}, 'subresource': '5057c129-894b-4bf5-a009-e4a7f701d411/start'}
2022-12-02 21:49:26,382 - DEBUG - turbine.commands.requests_base - read_configuration signed_url: "None"
2022-12-02 21:49:26,382 - DEBUG - turbine.commands.requests_base - post_page: "https://c1tsf1vb9a.execute-api.us-west-2.amazonaws.com/prod/session/5057c129-894b-4bf5-a009-e4a7f701d411/start" "{'headers': {'Content-Type': 'application/json; charset=utf-8'}}"
2022-12-02 21:49:26,382 - DEBUG - turbine.commands.requests_base - _post_page url: "https://c1tsf1vb9a.execute-api.us-west-2.amazonaws.com/prod/session/5057c129-894b-4bf5-a009-e4a7f701d411/start" "{}"
2022-12-02 21:49:27,897 - DEBUG - turbine.commands.requests_base - HTTP POST(200)
```

**Comment by boverhof** [comment]
# CloudWatch Logs HTTP 502:  Lambda Timeout
-  Lambda function is configured to time-out in 3 seconds, need to bump this up to 10.
- 
```
2022-12-02T20:54:21.497Z post-session-start Delete : [object Object]
--
2022-12-02T20:54:22.376Z post-session-start handleDelete: DELETED undefined
2022-12-02T20:54:22.495Z 08a86618-d35b-49a5-ad4f-4c12758cbe4a Task timed out after 3.08 seconds
END RequestId: 08a86618-d35b-49a5-ad4f-4c12758cbe4a
REPORT RequestId: 08a86618-d35b-49a5-ad4f-4c12758cbe4a	Duration: 3078.03 ms	Billed Duration: 3000 ms	Memory Size: 128 MB	Max Memory Used: 87 MB	Init Duration: 501.37 ms


```

**Comment by boverhof** [comment]
- Each "Start" happens in two batches ( invocations of POST session/start )
- Previously the first was typically failing ( red ), and the second would complete the submission
- Now it is working after increasing the TO
<img width="1282" alt="Screen Shot 2022-12-02 at 1 22 00 PM" src="https://user-images.githubusercontent.com/738295/205388598-bd2d2924-b67e-4ca8-b2f9-b3510d1b6191.png">
