### ISSUE TITLE
UQ Errors

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/FOQUS#1101]
# Description
- Windows 2016
- most recent GIT FOQUS 

```
2023-01-18 01:21:25,232 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - turbine configuration url="http://localhost:8000/TurbineLite"
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\foqus\lib\site-packages\foqus_lib\gui\uq\uqSetupFrame.py", line 696, in loadSimulation
    data = LocalExecutionModule.readSampleFromPsuadeFile(fileName)
  File "C:\ProgramData\Anaconda3\envs\foqus\lib\site-packages\foqus_lib\framework\uq\LocalExecutionModule.py", line 331, in readSampleFromPsuadeFile
    data.setNumSamples(numSamples)
UnboundLocalError: local variable 'numSamples' referenced before assignment
2023-01-18 01:22:16,590 - CRITICAL - foqus.foqus_lib.foqus - unhandled exception
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\foqus\lib\site-packages\foqus_lib\gui\uq\uqSetupFrame.py", line 696, in loadSimulation
    data = LocalExecutionModule.readSampleFromPsuadeFile(fileName)
  File "C:\ProgramData\Anaconda3\envs\foqus\lib\site-packages\foqus_lib\framework\uq\LocalExecutionModule.py", line 331, in readSampleFromPsuadeFile
    data.setNumSamples(numSamples)
UnboundLocalError: local variable 'numSamples' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\foqus\lib\site-packages\foqus_lib\gui\uq\uqSetupFrame.py", line 701, in loadSimulation
    QtGui.QMessageBox.critical(
AttributeError: module 'PyQt5.QtGui' has no attribute 'QMessageBox'

```

**Comment by boverhof** [comment]
Looks like it's just the wrong module.   Figured it out.

**Comment by boverhof** [comment]
from josh morgan
```
I was able to load in the Sample_6.txt file in the uncertainty tab using the following steps:

- Select 'Add New...'
- Select 'Use flowsheet' and click 'OK'
- For 'Choose how to generate samples...', select 'Load all samples from a single file'
- Navigate to the 'Sample_6.txt' file, select 'Open' and then 'Done'
```

**Comment by boverhof** [comment]
# Steps #568 
- install psuade-lite
```
conda install --yes -c conda-forge -c CCSI-Toolset psuade-lite=1.9
```

**Comment by lbianchi-lbl** [comment]
I'm trying to understand why pylint didn't flag the undefined variable since in principle it should be able to do so.

The line where the error occurs is:

https://github.com/CCSI-Toolset/FOQUS/blob/b764769fe522adf5d82c6f3b5a0d03214e31e90b/foqus_lib/framework/uq/LocalExecutionModule.py#L331

Just by looking at the code before that line, my (unproven) guesses are:

- The if-clause complexity is too high and pylint doesn't manage (or doesn't even try) to keep track of which variables are defined
- pylint (erroneously) assumes that `numSamples` will be available in the `readSampleFromPsuadeFile` scope since it's defined in the `LocalExecutionModule` class definition scope
