### ISSUE TITLE
matplotlib 3.8 errors

### ISSUE THREAD

**Issue by lbianchi-lbl** [CCSI-Toolset/FOQUS#1211]
The error was reported by @kbuma in https://github.com/CCSI-Toolset/FOQUS/pull/1210#issuecomment-2021358501

```txt
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\ccsi-foqus-rc\lib\site-packages\foqus_lib\gui\sdoe\sdoePreview.py", line 149, in plotSdoe
    fig1, fig2 = plot_utils.plot(
  File "C:\ProgramData\anaconda3\envs\ccsi-foqus-rc\lib\site-packages\foqus_lib\framework\sdoe\plot_utils.py", line 509, in plot
    fig1 = plot_candidates(
  File "C:\ProgramData\anaconda3\envs\ccsi-foqus-rc\lib\site-packages\foqus_lib\framework\sdoe\plot_utils.py", line 421, in plot_candidates
    lh.set_alpha(1)
  File "C:\ProgramData\anaconda3\envs\ccsi-foqus-rc\lib\site-packages\matplotlib\collections.py", line 848, in set_alpha
    artist.Artist._set_alpha_for_array(self, alpha)
  File "C:\ProgramData\anaconda3\envs\ccsi-foqus-rc\lib\site-packages\matplotlib\artist.py", line 1033, in _set_alpha_for_array
    Artist.set_alpha(self, alpha)
  File "C:\ProgramData\anaconda3\envs\ccsi-foqus-rc\lib\site-packages\matplotlib\artist.py", line 1015, in set_alpha
    if alpha != self._alpha:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()```
```

This seems to be originating from this part of the matplotlib codebase:

https://github.com/matplotlib/matplotlib/blame/975b5849d92cf446f79738a7ba9e0bd2e4792b41/lib/matplotlib/artist.py#L1001-L1041

**Comment by lbianchi-lbl** [comment]
From @sotorrio1:

https://github.com/CCSI-Toolset/FOQUS/blob/1161d04eea5fe477dbf8f58eb1c1db73b218cf25/foqus_lib/framework/sdoe/plot_utils.py#L420-L421

```py
for lh in leg.legend_handles:
    lh.set_alpha(1)
```
