### ISSUE TITLE
New FOQUS Cloud Deployment

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/FOQUS#1224]
# Description
Using the newly released SimSinter and TurbineLite, deploy FOQUS Cloud in Oregon.

- [x] Create New image
- [x] Deploy Out to Oregon
- [x] Test Fake Simulation
- [x] Test ACM Simulation

# New Image 
- Aspen v14
- Microsoft Server 2022
- python 3.11

# FOQUS Code branch
- foqus_cloud

**Comment by boverhof** [comment]
# Problem 1
- Executable for AspenSinterConsumer moved to `\Program Files\`
```
2024-05-30 16:52:05,092 - ERROR - foqus.foqus_lib.framework.graph.node - Error in node python code
Traceback (most recent call last):
  File "c:\users\administrator\desktop\foqus\foqus_lib\framework\graph\node.py", line 1392, in runPython
    exec(self.pythonCode)
  File "<string>", line 4, in <module>
  File "c:\users\administrator\desktop\foqus\foqus_lib\framework\graph\node.py", line 1325, in runModel
    self.runTurbineCalc(retry=self.options["Retry"].value)
  File "c:\users\administrator\desktop\foqus\foqus_lib\framework\graph\node.py", line 1515, in runTurbineCalc
    configProfile.startConsumer(self.name, self.modelName)
  File "c:\users\administrator\desktop\foqus\foqus_lib\framework\sim\turbineConfiguration.py", line 367, in startConsumer
    proc = subprocess.Popen(
  File "C:\tools\Anaconda3\envs\foqus\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\tools\Anaconda3\envs\foqus\lib\subprocess.py", line 1436, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by boverhof** [comment]
# Problem 2:  AspenSinterConsumerConsole hangs
- might need DEBUG turned on for the executables hard to tell what's the problem
```
Failed to open Simulation (1: The RPC server is unavailable. (Exception from HRESULT: 0x800706BA)
```
<img width="1240" alt="Screenshot 2024-06-01 at 2 38 30 PM" src="https://github.com/CCSI-Toolset/FOQUS/assets/738295/5b51b388-e2cd-4a65-b16d-9d1fbd382ee8">

**Comment by boverhof** [comment]
# Example/test BFB OUU Fails to load in AspenV14
- Aspen Properties has an error

<img width="519" alt="Screenshot 2024-06-03 at 6 00 02 PM" src="https://github.com/CCSI-Toolset/FOQUS/assets/738295/98557a55-c42d-4f0d-9aff-543c50f50df6">
<img width="546" alt="Screenshot 2024-06-03 at 5 59 44 PM" src="https://github.com/CCSI-Toolset/FOQUS/assets/738295/7e83511a-1699-4f6b-b88e-f0b9957b343c">
<img width="848" alt="Screenshot 2024-06-03 at 5 57 22 PM" src="https://github.com/CCSI-Toolset/FOQUS/assets/738295/d71317a8-6a7e-472e-8778-faa2fee75a5b">

**Comment by boverhof** [comment]
# OUU_Remote_Turbine_BFB
successfully ran the `foqus/examples/test_files/OUU_Remote_Turbine_BFB/BFB_OUU_06_09_2020.foqus` with defaults
## Output
```python
{'solTime': 110.33983993530273, 
'input': {'graph': {}, 'BFB': {'BFBadsB.Dt': 11.897, 'BFBadsB.dx': 0.0127, 'BFBadsB.Lb': 2.085, 'BFBadsM.Dt': 15, 'BFBadsM.dx': 0.06695, 'BFBadsM.Lb': 1.972, 'BFBadsT.Dt': 15, 'BFBadsT.dx': 0.062397, 'BFBadsT.Lb': 2.203, 'BFBRGN.Dt': 9.041, 'BFBRGN.Lb': 8.886, 'BFBRGNTop.Dt': 9.195, 'BFBRGNTop.Lb': 7.1926, 'GHXfg.A_exch': 16358, 'Kd': 100, 'BFBadsB.Cr': 1, 'BFBadsM.Cr': 1, 'BFBadsT.Cr': 1, 'BFBRGN.Cr': 1, 'BFBRGNTop.Cr': 1, 'dp': 0.00015, 'GHXfg.GasIn.P': 1.01325, 'GHXfg.GasIn.T': 54, 'fg_flow': 100377}}, 
'output': {'graph': {'error': 0}, 'BFB': {'Cost_coe': 138.82425739884636, 'Cost_coe_obj': 138.82425739884636, 'Cost_ads': 34832226.20639935, 'Cost_aux_power': 23385.503427224277, 'Cost_op_cooling_water': 12562503.664959071, 'Cost_op_cooling_water_flow': 2923843.78423705, 'Cost_op_fixed': 54527170.10507197, 'Cost_op_var': 172522109.68218017, 'Cost_rgn': 16323489.589995965, 'Cost_shx': 39020395.75661277, 'Cost_steam_power': 178992.8400843956, 'Cost_steam_tot': 695217.1196293447, 'Cost_toc': 2111605826.971341, 'Cost_toc_sorb': 84011457.36869758, 'removalCO2': 0.8996801078092209, 'SHX.CWFR': 26470.78926712216, 'SHX.LeanIn.T': 146.3976529163801, 'SHX.RichIn.T': 84.06464787557616, 'SHX.SteamFR': 37652.63814666193, 'removalCO2_slack': 0, 'slugab_slack': 0, 'slugam_slack': 0, 'slugat_slack': 0, 'slugrb_slack': 0, 'slugrt_slack': 0, 'BFBRGN.GasIn.F': 1357.089941010187, 'F_solids': 12702449.02608155, 'GHXfg.HXIn.F': 135603.6604814625, 'SHX.LeanOut.T': 71.01606811426312, 'SHX.RichOut.T': 170, 'status': 0}}, 
'graphError': 0, 
'nodeError': {'BFB': 0}, 
'nodeSettings': {'BFB': {'Visible': False, 'Initialize Model': False, 'Reset': False, 'Reset on Fail': True, 'Retry': False, 'Allow Simulation Warnings': True, 'Max consumer reuse': 90, 'Maximum Wait Time (s)': 1440, 'Maximum Run Time (s)': 840, 'Min Status Check Interval': 4, 'Max Status Check Interval': 5, 'Override Turbine Configuration': 'NULL', 'RunMode': 'Steady State', 'printlevel': 0, 'homotopy': 0, 'Snapshot': 'NULL', 'TimeSeries': [0], 'Script': 'NULL', 'MinStepSize': 0.001, 'TimeUnits': 'Hours'}}, 
'turbineMessages': {'BFB': '["event=setup,consumer=c687381f-5d6a-4715-8f2b-1158c779f30e", "Setup: Reusing Sinter ACM", "event=running,consumer=c687381f-5d6a-4715-8f2b-1158c779f30e", "sinter inputs sent, running simulation", "Real Run was complete and successful.", "event=sucess,consumer=c687381f-5d6a-4715-8f2b-1158c779f30e"]'}, 'input_vectorvals': {'BFB': {}}, 'output_vectorvals': {'BFB': {}}, 'session': 'bbabbfda-8aea-4e0a-ab65-b8ce1f333407', 'Id': 'e3626a36-d7a3-4c0e-b8d0-f2899a72871e', 'resub': 0}
```
