### ISSUE TITLE
Flowsheet: Problem Running Surrogate Plugin

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#198]
- I opened a FOQUS file, where I am running a node that uses a previously-generated ALAMO surrogate model
- I ran the Flowsheet simulation, and I got this error message: "The simulation completed with an error 20, Flowsheet thread terminated"
- I went to the Node Editor to specify the "Type" and "Model" under the "Model" heading
- I specified "Plugin" as the "Type"
- I specified "alamo_surrogate_fsBY_rS" as the "Model"
- I got this error message:

<img width="446" alt="alamo_05_09_2018" src="https://user-images.githubusercontent.com/30811140/39836407-43f7e708-53a1-11e8-8a01-0a4e09d16cb1.png">

**Comment by fsoepyan** [comment]
- I followed the Alamo tutorial in the FOQUS user's manual
- After I clicked "Run" under "Execution", I got this error message:

Traceback (most recent call last):

  File "C:\Users\fsoepyan\Desktop\Research Files\GitHub_Downloads\FOQUS-master-05.09.2018\foqus_lib\framework\surrogate\ALAMO.py", line 500, in run
    self.writeAlamoInputFile(adaptiveExe=adpexe)

  File "C:\Users\fsoepyan\Desktop\Research Files\GitHub_Downloads\FOQUS-master-05.09.2018\foqus_lib\framework\surrogate\ALAMO.py", line 584, in writeAlamoInputFile
    self.graph.results.set_filter(dataFilter)

  File "C:\Users\fsoepyan\Desktop\Research Files\GitHub_Downloads\FOQUS-master-05.09.2018\foqus_lib\framework\sampleResults\results.py", line 185, in set_filter
    self.update_filter_indexes()

  File "C:\Users\fsoepyan\Desktop\Research Files\GitHub_Downloads\FOQUS-master-05.09.2018\foqus_lib\framework\sampleResults\results.py", line 192, in update_filter_indexes
    self._filter_indexes, self._filter_mask = self.filter_indexes()

  File "C:\Users\fsoepyan\Desktop\Research Files\GitHub_Downloads\FOQUS-master-05.09.2018\foqus_lib\framework\sampleResults\results.py", line 419, in filter_indexes
    indexes = list(self[mask].index)

  File "C:\Users\fsoepyan\AppData\Local\Continuum\anaconda2\lib\site-packages\pandas\core\frame.py", line 2139, in __getitem__
    return self._getitem_column(key)

  File "C:\Users\fsoepyan\AppData\Local\Continuum\anaconda2\lib\site-packages\pandas\core\frame.py", line 2146, in _getitem_column
    return self._get_item_cache(key)

  File "C:\Users\fsoepyan\AppData\Local\Continuum\anaconda2\lib\site-packages\pandas\core\generic.py", line 1842, in _get_item_cache
    values = self._data.get(item)

  File "C:\Users\fsoepyan\AppData\Local\Continuum\anaconda2\lib\site-packages\pandas\core\internals.py", line 3843, in get
    loc = self.items.get_loc(item)

  File "C:\Users\fsoepyan\AppData\Local\Continuum\anaconda2\lib\site-packages\pandas\core\indexes\base.py", line 2527, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))

  File "pandas/_libs/index.pyx", line 117, in pandas._libs.index.IndexEngine.get_loc

  File "pandas/_libs/index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc

  File "pandas/_libs/hashtable_class_helper.pxi", line 1265, in pandas._libs.hashtable.PyObjectHashTable.get_item

  File "pandas/_libs/hashtable_class_helper.pxi", line 1273, in pandas._libs.hashtable.PyObjectHashTable.get_item

KeyError: NotImplemented

**Comment by fsoepyan** [comment]
- I downloaded FOQUS from the eslickj:fix_surrogate_nodevars branch
- When I tried to open a file from the Surrogate tutorial, I got the same error message as before
- In another file, when I tried to use the "alamo_surrogate_fsBY_rS" ALAMO surrogate model, I got the same error message as before

**Comment by eslickj** [comment]
Yeah.  The problem is not in running the flowsheet plugins, but in generating them.  The "nodeVars" should now be "NodeVars" in the generated code.  Unfortunately to test the fix you have to generate a new plugin.  Also if you have old plugins you like, they can be fixed by manually capitalizing nodeVars.

**Comment by fsoepyan** [comment]
- I redid the ALAMO tutorial
- I managed to generate the surrogate model
- I can use the surrogate model in the flowsheet

**Comment by fsoepyan** [comment]
- I modified the python code for an existing ALAMO surrogate model
- Except for the line that says "from foqus_lib.framework.graph.nodeVars import *", I changed "nodeVars" to "NodeVars"
- I can now use the existing surrogate model in the flowsheet
