### ISSUE TITLE
Test AWS Cloud Submission

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/FOQUS#243]
Tester will attempt to submit a OUU request to the AWS FOQUS Cloud via FOQUS UI.

Likely this will require building out the REST API.

- TURBINE CONFIGURATION FILE

```
[Logging]
fileConfig=logging.conf
[Consumer]
url=https://407osudx4l.execute-api.us-east-1.amazonaws.com/dev/consumer
[Job]
url=https://407osudx4l.execute-api.us-east-1.amazonaws.com/dev/job
[Simulation]
url=https://407osudx4l.execute-api.us-east-1.amazonaws.com/dev/simulation
[Session]
url=https://407osudx4l.execute-api.us-east-1.amazonaws.com/dev/session
[Application]
url=https://407osudx4l.execute-api.us-east-1.amazonaws.com/dev/application
[Authentication]
username=anonymous
password=changeme
```

**Comment by boverhof** [comment]
Group of us tested FOQUS UI with AWS FOQUS Cloud.  Job submission worked correctly but the results apparently are missing a field.

`
Traceback (most recent call last):
  File "/Users/boverhof/Documents/workspace.ccsi2/foqus-boverhof/foqus_lib/gui/main/mainWindow.py", line 1274, in checkSim
    self.stopSim()
  File "/Users/boverhof/Documents/workspace.ccsi2/foqus-boverhof/foqus_lib/gui/main/mainWindow.py", line 1336, in stopSim
    self.dat.flowsheet.loadValues(self.singleRun.res[0])
  File "/Users/boverhof/Documents/workspace.ccsi2/foqus-boverhof/foqus_lib/framework/graph/graph.py", line 335, in loadValues
    raise RuntimeError, 'No input in sd dict: %s' %str(sd)

RuntimeError: No input in sd dict: {u'graph': {u'error': 0}, 'session': 'd2430472-8405-4c3c-9352-b760e25ca5f4', 'Id': u'fdbca3c3-4620-4e53-a7c8-501f21e8fe74', 'resub': 0, u'BFB': {u'removalCO2': 0.8999964373466817, u'removalCO2_slack': 0, u'SHX.SteamFR': 37683.43278161038, u'slugam_slack': 0, u'GHXfg.HXIn.F': 135788.8395015208, u'slugrb_slack': 0, u'Cost_op_fixed': 54526718.57072218, u'BFBRGN.GasIn.F': 1357.0814214980398, u'Cost_ads': 34830765.96283022, u'Cost_steam_power': 179203.44430650023, u'SHX.RichIn.T': 83.99312572585319, u'SHX.CWFR': 26890.328479471482, u'slugab_slack': 0, u'Cost_op_cooling_water': 12577963.846287617, u'Cost_toc_sorb': 83874472.31479213, u'Cost_rgn': 16321781.413333291, u'status': 0, u'SHX.RichOut.T': 170, u'slugrt_slack': 0, u'Cost_toc': 2111440309.1504824, u'F_solids': 12681737.021801885, u'Cost_shx': 39020395.75661277, u'Cost_coe_obj': 138.85964658190665, u'Cost_aux_power': 23378.969592384507, u'Cost_op_var': 172437413.51951027, u'Cost_op_cooling_water_flow': 2927442.0442882474, u'SHX.LeanIn.T': 146.3820219819483, u'SHX.LeanOut.T': 70.57864346590641, u'Cost_steam_tot': 696035.1169336186, u'slugat_slack': 0, u'Cost_coe': 138.85964658190665}}

2018-08-07 12:51:59,464 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - Stopped all running consumers
`
