### ISSUE TITLE
FOQUS Workers not updating running timestamp

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/FOQUS#292]
## Description
SQS consumer update messages are being generated, however, the "running" timestamp in the dynamodb table is NOT being updated.

Not able to quickly see which workers are alive.

**Comment by boverhof** [comment]
Think I saw in CloudWatch logs a problem here:
```
foqus-boverhof % grep instance_id cloud/aws/node/foqus-sns-update/index.js
    var instance_id = message['instanceid'];
```
The updates I don't believe are specifying the 'instanceid' which results in an exception..

**Comment by ksbeattie** [comment]
@boverhof will with on this any/or get Abdel to work on it.

**Comment by boverhof** [comment]
# CloudWatch Logs
== SNS Message
```
2018-11-16T16:43:21.741Z	ba7296b0-e9be-11e8-85f5-13386d52051c	Received event:
{
    "Records": [
        {
            "EventSource": "aws:sns",
            "EventVersion": "1.0",
            "EventSubscriptionArn": "arn:aws:sns:us-east-1:754323349409:FOQUS-Update-Topic:564dd5e2-3bb5-4ad6-85b0-6ec20b5c9dfa",
            "Sns": {
                "Type": "Notification",
                "MessageId": "84cfb94b-3129-5ba3-bf9b-ed23c4c08252",
                "TopicArn": "arn:aws:sns:us-east-1:754323349409:FOQUS-Update-Topic",
                "Subject": null,
                "Message": "[{\"consumer\": \"cf6c8fa2-e70b-438e-b6d5-f201d1d4989c\", \"resource\": \"consumer\", \"event\": \"running\", \"rc\": 0}]",
                "Timestamp": "2018-11-16T16:43:21.542Z",
                "SignatureVersion": "1",
                "Signature": "DosctEeuz2TJ0CKssTRllwE8TR5ElbWtamyiQMqbzS7YfKR7hYkWLwXHRHeBeXqsWZS3F3GXly1f8GWOQw8m9ectottCi66mYU+h/7yVXRNk3bP/Fago+vPc/VQJsTTUz6i8jr4DhYMhKABbkpOZVlRNpmJs34qtISkuGO1fuxHSBtyPe9zMuVxVJGSXxNI231Ff+g+hflMJvmh0Gk43B0XOCRvzg0Yj+jDBBWfTEdi7Kj5zbEjy14XT763xNs9r4shLsbjkFfLO3s2o8tHZzF2/vLoAa3DOWgyQVwiSmfT3bRyQKd361fTpVvo2VBi8IWMj5Ztj4BuwDBGWNufDnQ==",
                "SigningCertUrl": "https://sns.us-east-1.amazonaws.com/SimpleNotificationService-ac565b8b1a6c5d002d285f9598aa1d9b.pem",
                "UnsubscribeUrl": "https://sns.us-east-1.amazonaws.com/?Action=Unsubscribe&SubscriptionArn=arn:aws:sns:us-east-1:754323349409:FOQUS-Update-Topic:564dd5e2-3bb5-4ad6-85b0-6ec20b5c9dfa",
                "MessageAttributes": {}
            }
        }
    ]
}
```
## DynamoDB update
```
2018-11-16T16:43:21.741Z	ba7296b0-e9be-11e8-85f5-13386d52051c
{
    "TableName": "FOQUS_Resources",
    "Key": {
        "Id": "cf6c8fa2-e70b-438e-b6d5-f201d1d4989c",
        "Type": "Consumer"
    },
    "UpdateExpression": "set running =:s, instance=:i",
    "ExpressionAttributeValues": {
        ":s": "2018-11-16T16:43:21.542Z"
    },
    "ReturnValues": "UPDATED_NEW"
}
```
## Lambda:  ValidationException on DynamoDB Update instanceid missing
```
2018-11-16T16:43:21.922Z	ba7296b0-e9be-11e8-85f5-13386d52051c	{ ValidationException: Invalid UpdateExpression: An expression attribute value used in expression is not defined; attribute value: :i
at Request.extractError (/var/task/node_modules/aws-sdk/lib/protocol/json.js:48:27)
at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:685:12)
at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
message: 'Invalid UpdateExpression: An expression attribute value used in expression is not defined; attribute value: :i',
code: 'ValidationException',
time: 2018-11-16T16:43:21.883Z,
requestId: 'TCC025SV41PQ7RQDRCFUDUKSCBVV4KQNSO5AEMVJF66Q9ASUAAJG',
statusCode: 400,
retryable: false,
retryDelay: 26.979455429563426 } 'ValidationException: Invalid UpdateExpression: An expression attribute value used in expression is not defined; attribute value: :i\n at Request.extractError (/var/task/node_modules/aws-sdk/lib/protocol/json.js:48:27)\n at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:105:20)\n at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:77:10)\n at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:683:14)\n at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)\n at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)\n at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10\n at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)\n at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:685:12)\n at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:115:18)'
```

**Comment by boverhof** [comment]
This was fixed in last pull request.
