### ISSUE TITLE
FOQUS Cloud Optimization BFB 

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/FOQUS#293]
## Description
Ran a FOQUS Optimization with BFB with 10 samples on 10 VMs. 
Ran for 1 hour 40 minutes, to Iteration 5 where it seems to have ended in error.

## FOQUS LOG
```
2018-10-04 21:04:24,976 - DEBUG - foqus.foqus_lib.framework.graph.graph - Sending jobs to Turbine in 1 sets
2018-10-04 21:04:25,463 - DEBUG - foqus.foqus_lib.framework.graph.graph - Created Jobs:
[u'6f9b3fc0-1be8-442b-bc6a-7fa4c27cb7a5', u'b9523efa-95bd-4afc-810d-839976eced4c', u'd9b004f7-4201-4cba-be07-01fb2c70740d', u'9ab215b7-d592-4ce6-8127-cba6441f6628', u'63e0f5ba-f1b6-4c94-bd56-4fbadc3c2562', u'4455962b-1a4a-42b8-be80-96deeef1252d', u'7cb91fb7-a918-4dad-8d51-4aa9faf2bed2', u'6e51b46f-9c1f-41c3-9a73-866a4b4daf6d', u'ebd6fe3c-fcf8-49e1-a0dc-6e26fbac5d2c', u'b318d04b-8e44-4447-b255-6da4d11bc984']
2018-10-04 21:04:26,744 - DEBUG - foqus.foqus_lib.framework.graph.graph - Results generator: bf5aad11-7480-4981-a9ba-8493aa26afb1
2018-10-04 21:05:58,505 - DEBUG - foqus.foqus_lib.framework.graph.graph - New results page 1 from bf5aad11-7480-4981-a9ba-8493aa26afb1
2018-10-04 21:05:58,505 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - Getting results from url: https://407osudx4l.execute-api.us-east-1.amazonaws.com/dev/session/6ddcdc85-1a7d-4ea3-a1df-73f4ba5d0ebf/result/bf5aad11-7480-4981-a9ba-8493aa26afb1/1
2018-10-04 21:06:09,311 - DEBUG - foqus.foqus_lib.framework.graph.graph - New results page 2 from bf5aad11-7480-4981-a9ba-8493aa26afb1
2018-10-04 21:06:09,311 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - Getting results from url: https://407osudx4l.execute-api.us-east-1.amazonaws.com/dev/session/6ddcdc85-1a7d-4ea3-a1df-73f4ba5d0ebf/result/bf5aad11-7480-4981-a9ba-8493aa26afb1/2
2018-10-04 21:06:19,959 - DEBUG - foqus.foqus_lib.framework.graph.graph - New results page 3 from bf5aad11-7480-4981-a9ba-8493aa26afb1
2018-10-04 21:06:19,959 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - Getting results from url: https://407osudx4l.execute-api.us-east-1.amazonaws.com/dev/session/6ddcdc85-1a7d-4ea3-a1df-73f4ba5d0ebf/result/bf5aad11-7480-4981-a9ba-8493aa26afb1/3
2018-10-04 21:06:33,276 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - Connecting to turbine, unhandled HTTP code 502
2018-10-04 21:06:33,276 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - Turbine Interface Error: 10.  Retry 1 in 20s. Gateway unknown http error
2018-10-04 21:06:56,319 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - Connecting to turbine, unhandled HTTP code 502
2018-10-04 21:06:56,319 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - Turbine Interface Error: 10.  Retry 2 in 80s. Gateway unknown http error
2018-10-04 21:08:19,404 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - Connecting to turbine, unhandled HTTP code 502
2018-10-04 21:08:19,404 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - Turbine Interface Error: 10.  Retry 3 in 180s. Gateway unknown http error
2018-10-04 21:11:22,479 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - Connecting to turbine, unhandled HTTP code 502
2018-10-04 21:11:22,479 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - Turbine Interface Error: 10.  Retry 4 in 320s. Gateway unknown http error
2018-10-04 21:16:45,536 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - Connecting to turbine, unhandled HTTP code 502
2018-10-04 21:16:45,536 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - Turbine Interface Error: 10.  Retry 5 in 500s. Gateway unknown http error
2018-10-04 21:25:05,546 - ERROR - foqus.foqus_lib.framework.graph.graph - Could not get results page
Traceback (most recent call last):
File "C:\ProgramData\Anaconda2\lib\site-packages\foqus-2017.12.0.0-py2.7.egg\foqus_lib\framework\graph\graph.py", line 541, in solveListValTurbineGetGeneratorPage
self.turbSession, gid)
File "C:\ProgramData\Anaconda2\lib\site-packages\foqus-2017.12.0.0-py2.7.egg\foqus_lib\framework\sim\turbineConfiguration.py", line 549, in retryFunction
raise e
TurbineInterfaceEx: 10 - Gateway unknown http error, HTTPError Failed to get completed job page: https://407osudx4l.execute-api.us-east-1.amazonaws.com/dev/session/6ddcdc85-1a7d-4ea3-a1df-73f4ba5d0ebf/result/bf5aad11-7480-4981-a9ba-8493aa26afb1
Traceback (most recent call last):
File "C:\ProgramData\Anaconda2\lib\site-packages\foqus-2017.12.0.0-py2.7.egg\foqus_lib\framework\sim\turbineConfiguration.py", line 906, in getCompletedJobPage
"")
File "build\bdist.win32\egg\turbine\commands\__init__.py", line 365, in post_page_by_url
d = _urlopen(url, data)
File "build\bdist.win32\egg\turbine\commands\__init__.py", line 92, in _urlopen
result = urllib2.urlopen(url, data)
File "C:\ProgramData\Anaconda2\lib\urllib2.py", line 154, in urlopen
return opener.open(url, data, timeout)
File "C:\ProgramData\Anaconda2\lib\urllib2.py", line 435, in open
response = meth(req, response)
File "C:\ProgramData\Anaconda2\lib\urllib2.py", line 548, in http_response
'http', request, response, code, msg, hdrs)
File "C:\ProgramData\Anaconda2\lib\urllib2.py", line 467, in error
result = self._call_chain(*args)
File "C:\ProgramData\Anaconda2\lib\urllib2.py", line 407, in _call_chain
result = func(*args)
File "build\bdist.win32\egg\turbine\commands\__init__.py", line 213, in http_error_401
return self.retry_http_basic_auth(host, req, realm)
File "C:\ProgramData\Anaconda2\lib\urllib2.py", line 897, in retry_http_basic_auth
return self.parent.open(req, timeout=req.timeout)
File "C:\ProgramData\Anaconda2\lib\urllib2.py", line 435, in open
response = meth(req, response)
File "C:\ProgramData\Anaconda2\lib\urllib2.py", line 548, in http_response
'http', request, response, code, msg, hdrs)
File "C:\ProgramData\Anaconda2\lib\urllib2.py", line 473, in error
return self._call_chain(*args)
File "C:\ProgramData\Anaconda2\lib\urllib2.py", line 407, in _call_chain
result = func(*args)
File "build\bdist.win32\egg\turbine\commands\__init__.py", line 140, in http_error_default
raise urllib2.HTTPDefaultErrorHandler.http_error_default(self, req, fp, code, msg, hdrs)
File "C:\ProgramData\Anaconda2\lib\urllib2.py", line 556, in http_error_default
raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 502: Bad Gateway
{"message": "Internal server error"}


2018-10-04 21:25:05,640 - ERROR - foqus.foqus_lib.framework.optimizer.optimization - Exception in optimization thread
Traceback (most recent call last):
File "C:\ProgramData\Anaconda2\lib\site-packages\foqus-2017.12.0.0-py2.7.egg\foqus_lib\framework\optimizer\optimization.py", line 76, in run
self.optimize()
File "C:\ProgramData\Anaconda2\lib\site-packages\foqus-2017.12.0.0-py2.7.egg\foqus_lib\framework\optimizer\NLopt.py", line 371, in optimize
x = opt.optimize(xinit)
File "C:\ProgramData\Anaconda2\lib\site-packages\nlopt.py", line 400, in optimize
return _nlopt.opt_optimize(self, *args)
File "C:\ProgramData\Anaconda2\lib\site-packages\foqus-2017.12.0.0-py2.7.egg\foqus_lib\framework\optimizer\NLopt.py", line 232, in f
objValues, cv, pv = self.prob.runSamples([x], self)
File "C:\ProgramData\Anaconda2\lib\site-packages\foqus-2017.12.0.0-py2.7.egg\foqus_lib\framework\optimizer\problem.py", line 337, in runSamples
return self.calculateObj(gt.res, nsamples = snum)
File "C:\ProgramData\Anaconda2\lib\site-packages\foqus-2017.12.0.0-py2.7.egg\foqus_lib\framework\optimizer\problem.py", line 393, in calculateObj
(x, f) = self.get_at_dicts(x,f)
File "C:\ProgramData\Anaconda2\lib\site-packages\foqus-2017.12.0.0-py2.7.egg\foqus_lib\framework\optimizer\problem.py", line 405, in get_at_dicts
x[i] = AtDict(x[i])
TypeError: 'int' object is not iterable
```

**Comment by boverhof** [comment]
![screen shot 2018-10-04 at 4 06 08 pm](https://user-images.githubusercontent.com/738295/46508089-a50d7080-c7f0-11e8-8574-270e9a77e954.png)

**Comment by ksbeattie** [comment]
@eslickj will look at this, this week.

**Comment by ksbeattie** [comment]
@eslickj will try this week.

**Comment by ksbeattie** [comment]
@eslickj will try to get to this in 2 weeks!

**Comment by ksbeattie** [comment]
"Gimmie 2, maybe 3 more weeks" - @eslickj
