### ISSUE TITLE
Optimization Run ends in Assertion Error "nodeError"

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/FOQUS#297]
## Description
Assertion error on "nodeError".  NOTE this could be a duplicate bug report..

## Traceback
```
['Traceback (most recent call last):\n',
'  File "C:\\ProgramData\\Anaconda2\\lib\\site-packages\\foqus-2017.12.0.0-py2.7.egg\\foqus_lib\\framework\\optimizer\\optimization.py", line 76, in run
    self.optimize()',
'  File "C:\\ProgramData\\Anaconda2\\lib\\site-packages\\foqus-2017.12.0.0-py2.7.egg\\foqus_lib\\framework\\optimizer\\BFGS.py", line 188, in optimize options={\'ftol\':ftol, \'eps\':eps, \'maxfun\':maxeval})',
'  File "C:\\ProgramData\\Anaconda2\\lib\\site-packages\\scipy\\optimize\\_minimize.py", line 450, in minimize
    \n    callback=callback, **options)\n',
    '  File "C:\\ProgramData\\Anaconda2\\lib\\site-packages\\scipy\\optimize\\lbfgsb.py", line 328, in _minimize_lbfgsb\n    f, g = func_and_grad(x)\n',
    '  File "C:\\ProgramData\\Anaconda2\\lib\\site-packages\\scipy\\optimize\\lbfgsb.py", line 274, in func_and_grad\n    g = _approx_fprime_helper(x, fun, epsilon, args=args, f0=f)\n',
    '  File "C:\\ProgramData\\Anaconda2\\lib\\site-packages\\scipy\\optimize\\optimize.py", line 628, in _approx_fprime_helper\n    grad[k] = (f(*((xk + d,) + args)) - f0) / d[k]\n',
    '  File "C:\\ProgramData\\Anaconda2\\lib\\site-packages\\scipy\\optimize\\optimize.py", line 292, in function_wrapper\n    return function(*(wrapper_args + args))\n',
    '  File "C:\\ProgramData\\Anaconda2\\lib\\site-packages\\foqus-2017.12.0.0-py2.7.egg\\foqus_lib\\framework\\optimizer\\BFGS.py", line 113, in f\n    objValues, cv, pv = self.prob.runSamples([x], self)\n',
    '  File "C:\\ProgramData\\Anaconda2\\lib\\site-packages\\foqus-2017.12.0.0-py2.7.egg\\foqus_lib\\framework\\optimizer\\problem.py", line 330, in runSamples\n    gt.res[i])\n',
    '  File "C:\\ProgramData\\Anaconda2\\lib\\site-packages\\foqus-2017.12.0.0-py2.7.egg\\foqus_lib\\framework\\sampleResults\\results.py", line 316, in addFromSavedValues\n    self.add_result(valDict, set_name=setName, result_name=name, time=time)\n',
    '  File "C:\\ProgramData\\Anaconda2\\lib\\site-packages\\foqus-2017.12.0.0-py2.7.egg\\foqus_lib\\framework\\sampleResults\\results.py", line 327, in add_result\n    columns, dat = sd_col_list(sd, time=time)\n',
    '  File "C:\\ProgramData\\Anaconda2\\lib\\site-packages\\foqus-2017.12.0.0-py2.7.egg\\foqus_lib\\framework\\sampleResults\\results.py", line 90, in sd_col_list\n    assert sd.has_key("nodeError")\n', 'AssertionError\n']
```

**Comment by boverhof** [comment]
<img width="1036" alt="screen shot 2018-10-09 at 7 25 02 pm" src="https://user-images.githubusercontent.com/738295/46709819-3b2f0580-cbfa-11e8-9b06-a3acfa2957eb.png">

**Comment by boverhof** [comment]
## First plan of action create a unittest for result object with results from last Optimization run
```
test/system_test/foqus/framework/sampleResult/result_test.py
```

**Comment by eslickj** [comment]
Partly addressed in PR #298

**Comment by ksbeattie** [comment]
@eslickj thinks this is mostly fixed but would like to add logging, to get info if it happens again.

**Comment by ksbeattie** [comment]
@eslickj believes this might be related to #321 ...

**Comment by ksbeattie** [comment]
@eslickj will look at this (possibly after py3 is merged in).

**Comment by eslickj** [comment]
I think this may be fixed, and this doesn't contain much useful additional information.  I'm going to close it, and we can open a new issue if it turns out to not be fixed.
