### ISSUE TITLE
ERROR - foqus.foqus_lib.framework.graph.graph - Failed to get 'input' from results

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/FOQUS#321]
## Description
When a job result is in "error" status some of the fields are not available.  FOQUS doesn't check to see if a job is in "error" and therefore may not contain all the same information as a successful job run.

## Detail
```
2018-11-14 16:57:52,145 - INFO - turbine.commands - HTTP GET(200) OK: https://407osudx4l.execute-api.us-east-1.amazonaws.com/dev/session/ece56569-a655-4040-8118-0b6f251c90dd/result/10b76c7f-0206-4893-a980-61f808c41758/1?rpp=2000
2018-11-14 16:57:52,146 - DEBUG - turbine.commands - HTTP RESPONSE: 
[{"Id":"827b85e3-2ca6-4b01-9bcd-fdc2688226d2","Guid":"827b85e3-2ca6-4b01-9bcd-fdc2688226d2","Simulation":"zzfoqus_BFB","State":"error","Messages":null,"Input":{"graph":{},"BFB":{"BFBadsM.Lb":1.972,"fg_flow":100377,"BFBadsB.Dt":11.897,"GHXfg.GasIn.T":54,"BFBadsM.dx":0.06695,"GHXfg.A_exch":16358,"dp":0.00015,"BFBadsM.Cr":1,"GHXfg.GasIn.P":1.01325,"BFBRGN.Dt":9.041,"BFBRGNTop.Cr":1,"BFBadsT.Cr":1,"BFBRGNTop.Lb":7.1926,"BFBRGN.Lb":8.886,"BFBadsB.Cr":1,"BFBadsT.Lb":2.203,"BFBRGN.Cr":1,"BFBadsM.Dt":15,"BFBadsT.dx":0.062397,"BFBadsB.Lb":2.085,"BFBadsT.Dt":15,"BFBRGNTop.Dt":9.195,"BFBadsB.dx":0.0127,"Kd":100}},"Session":"ece56569-a655-4040-8118-0b6f251c90dd","Reset":false,"Visible":false,"Consumer":"343f721c-61f0-4dd8-ab19-562ee3910fdf","Create":"2018-11-15T00:57:06.160Z","Setup":"2018-11-15T00:57:12.398Z","Finished":"2018-11-15T00:57:42.355Z"}]
2018-11-14 16:57:52,146 - DEBUG - foqus.foqus_lib.framework.graph.graph - JRES: 1
2018-11-14 16:57:52,146 - DEBUG - foqus.foqus_lib.framework.graph.graph - Turbine Result Generator Results LEN: 1
2018-11-14 16:57:52,146 - DEBUG - turbine.commands - passman "https://407osudx4l.execute-api.us-east-1.amazonaws.com/dev/session/" password already registered
2018-11-14 16:57:52,147 - DEBUG - turbine.commands - DELETE URL: https://407osudx4l.execute-api.us-east-1.amazonaws.com/dev/session/ece56569-a655-4040-8118-0b6f251c90dd/result/10b76c7f-0206-4893-a980-61f808c41758
2018-11-14 16:57:52,147 - DEBUG - turbine.commands - HTTPS OPEN
2018-11-14 16:57:53,073 - DEBUG - turbine.commands - HTTPS OPEN
2018-11-14 16:57:53,718 - ERROR - foqus.foqus_lib.framework.graph.graph - Failed to get 'input' from results: sd={'session': 'ece56569-a655-4040-8118-0b6f251c90dd', 'graphError': -3, 'Id': u'827b85e3-2ca6-4b01-9bcd-fdc2688226d2', 'resub': 0}
2018-11-14 16:57:53,719 - CRITICAL - foqus.__main__ - unhandled exception
Traceback (most recent call last):
  File "/Users/boverhof/Documents/workspace.ccsi2/foqus-boverhof/foqus_lib/gui/main/mainWindow.py", line 1268, in checkSim
    self.stopSim()
  File "/Users/boverhof/Documents/workspace.ccsi2/foqus-boverhof/foqus_lib/gui/main/mainWindow.py", line 1341, in stopSim
    sd=self.singleRun.res[0])
  File "/Users/boverhof/Documents/workspace.ccsi2/foqus-boverhof/foqus_lib/framework/sampleResults/results.py", line 333, in add_result
    columns, dat = sd_col_list(sd, time=time)
  File "/Users/boverhof/Documents/workspace.ccsi2/foqus-boverhof/foqus_lib/framework/sampleResults/results.py", line 105, in sd_col_list
    dat = [time, sd["solTime"], sd["graphError"]]
KeyError: 'solTime'


```

**Comment by eslickj** [comment]
I can fix this.  The bigger problem though is that it indicates that the foqus client didn't produce the expected output or it didn't get picked up somehow.  Does it happen all the time or just rarely?

**Comment by eslickj** [comment]
Should be fixed in PR #322, but I think this could be a symptom of a bigger problem.

**Comment by boverhof** [comment]
# Unit test
Printed out the sd structure and put it into a unittest and produces the above error.  Not sure why this is now failing.
```
def test_add_result_single():
    """ BROKEN...
    blows up in Results.sd_col_list
    """
    obj = results.Results()
    setName = 's3test'
    name = 'whatever'
    # sd = self.singleRun.res[0]
    sd = {
        'resub': 0,
        'nodeError': {},
        'session': '9f4def1c-d033-4761-9e8d-7ae979d230ae',
        'turbineMessages': {},
        'graphError': -3,
        'Id': u'08e6bf2d-e6e2-4e75-8ce2-8e86a6a0db83'
    }
    obj.add_result(set_name='Single_runs',
                    result_name='single_{}'.format(0),
                    time=None,
                    sd=sd)

    assert 5 == obj.count_cols()
```
# Required key fields
test results empty demonstrates all the required fields ( results_s3_test.py )
```
def test_results_empty():
    """ Paging results from session results generator
    solTime -- Amount of time used to solve graph outputs
    """
    sd = {
        'solTime':None,
        'input':dict(),
        'output':dict(),
        'graphError':None,
        'nodeError':{},
        'nodeSettings':{},
        'turbineMessages':{}
    }
    obj = results.Results()
    setName = 's3test'
    name = 'whatever'
    obj.addFromSavedValues(setName, name, valDict=sd)

    assert 5 == obj.count_cols()
```

**Comment by boverhof** [comment]
# Job was in error status
```
[
  {
    "Id": "08e6bf2d-e6e2-4e75-8ce2-8e86a6a0db83",
    "Guid": "08e6bf2d-e6e2-4e75-8ce2-8e86a6a0db83",
    "Simulation": "zzfoqus_BFB",
    "State": "error",
    "Messages": null,
    "Input": {
      "graph": {},
      "BFB": {
        "BFBadsM.Lb": 1.972,
        "fg_flow": 100377,
        "BFBadsB.Dt": 11.897,
        "GHXfg.GasIn.T": 54,
        "BFBadsM.dx": 0.06695,
        "GHXfg.A_exch": 16358,
        "dp": 0.00015,
        "BFBadsM.Cr": 1,
        "GHXfg.GasIn.P": 1.01325,
        "BFBRGN.Dt": 9.041,
        "BFBRGNTop.Cr": 1,
        "BFBadsT.Cr": 1,
        "BFBRGNTop.Lb": 7.1926,
        "BFBRGN.Lb": 8.886,
        "BFBadsB.Cr": 1,
        "BFBadsT.Lb": 2.203,
        "BFBRGN.Cr": 1,
        "BFBadsM.Dt": 15,
        "BFBadsT.dx": 0.062397,
        "BFBadsB.Lb": 2.085,
        "BFBadsT.Dt": 15,
        "BFBRGNTop.Dt": 9.195,
        "BFBadsB.dx": 0.0127,
        "Kd": 100
      }
    },
    "Session": "9f4def1c-d033-4761-9e8d-7ae979d230ae",
    "Reset": false,
    "Visible": false,
    "Consumer": "bd78c94f-4137-41b1-ad34-4190afb4b19c",
    "Create": "2018-11-15T04:19:12.645Z",
    "Setup": "2018-11-15T04:19:15.282Z",
    "Finished": "2018-11-15T04:19:17.662Z"
  }
]
```

**Comment by boverhof** [comment]
# TurbineWeb API wasn't on but error doesn't have this information

## FROM C:\ProgramData\foqus_service\logs\FOQUS-Cloud-Service.log
```
DEBUG:root:Process Flowsheet nodes
ERROR:root:setup foqus URLError: <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\Scripts\foqus_service.py", line 227, in SvcDoRun
    dat = self.setup_foqus(db, job_desc)
  File "C:\ProgramData\Anaconda2\Scripts\foqus_service.py", line 383, in setup_foqus
    sim_list = turbine_simulation_script.main_list([node.gr.turbConfig.getFile()])
  File "C:\ProgramData\Anaconda2\lib\site-packages\turbine\commands\turbine_simulation_script.py", line 196, in main_list
    content = get_page(configFile, SECTION, **query)
  File "C:\ProgramData\Anaconda2\lib\site-packages\turbine\commands\__init__.py", line 394, in get_page
    return get_page_by_url(url, configFile, **extra_query)
  File "C:\ProgramData\Anaconda2\lib\site-packages\turbine\commands\__init__.py", line 390, in get_page_by_url
    return _do_get(page_url)
  File "C:\ProgramData\Anaconda2\lib\site-packages\turbine\commands\__init__.py", line 98, in _do_get
    d = _urlopen(url)
  File "C:\ProgramData\Anaconda2\lib\site-packages\turbine\commands\__init__.py", line 92, in _urlopen
    result = urllib2.urlopen(url, data)
  File "C:\ProgramData\Anaconda2\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\ProgramData\Anaconda2\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "C:\ProgramData\Anaconda2\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "C:\ProgramData\Anaconda2\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\ProgramData\Anaconda2\lib\urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "C:\ProgramData\Anaconda2\lib\urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
INFO:root:foqus_service.TurbineLiteDB.job_change_status error
```

**Comment by boverhof** [comment]
@boverhof will get a unittest working that dumps the job description in using mocks and results in the exception, then @eslickj will figure out what needs to happen in the FOQUS UI.

**Comment by ksbeattie** [comment]
@boverhof did PR #322 fix this?

**Comment by ksbeattie** [comment]
@boverhof and @fsoepyan confirm this after the py3 branch is merge in #324 .

**Comment by ksbeattie** [comment]
@boverhof & @fsoepyan the branch is now merge.  Let's confirm!

**Comment by fsoepyan** [comment]
I will test this after I can confirm that I can upload a simulation into Turbine, and run FOQUS for that simulation.

**Comment by ksbeattie** [comment]
@fsoepyan & @eslickj will be working together on remote turbine, and so will attempt to test this after that.

**Comment by fsoepyan** [comment]
- @eslickj and I tested remote turbine today
- I used the Simple_flow example under "examples\Smoke Tests", which does not require any Aspen or Excel simulations
- When I ran this example using remote turbine, sometimes it works, sometimes it doesn't work
- I will investigate further

**Comment by fsoepyan** [comment]
- I tested remote turbine again today using the Simple_flow example from the "examples\Smoke Tests" folder
- Today, it worked, even after I changed the values of the input variables
- I will close this issue
