### ISSUE TITLE
Turbine in Py3: Problem uploading model to Turbine

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#362]
- I downloaded the latest version of turb_client from: https://github.com/CCSI-Toolset/turb_client
- I went to Anaconda (for Python 3), and typed: python setup.py install
- The installation was successful
- I opened FOQUS
- When I tried to upload an Aspen model to Turbine, I got the following error message:

<img width="800" alt="turbine_01_28_2019" src="https://user-images.githubusercontent.com/30811140/51847609-0dc1b100-22ea-11e9-98ea-452832d105d1.png">

**Comment by fsoepyan** [comment]
@jmorgan29 also ran into this issue.

**Comment by fsoepyan** [comment]
- I tried to get the log file, but when I clicked the "Help" button and went to "Log Viewer", it's not there.
- Instead, I will show the log message that @jmorgan29 got for this issue:

2019-01-28 09:58:50,485 - ERROR - foqus.foqus_lib.gui.model.gatewayUploadDialog - Error reading sinter config
Traceback (most recent call last):
  File "C:\Users\jmorgan\Desktop\FOQUS-master-24Jan2019\foqus_lib\gui\model\gatewayUploadDialog.py", line 314, in browseSinter
    for f in oth:
TypeError: 'NoneType' object is not iterable
2019-01-28 09:58:55,393 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - Unhanded exception type <class 'AttributeError'> 'NoneType' object has no attribute 'open' type: <class 'AttributeError'> trace:
Traceback (most recent call last):
  File "C:\Users\jmorgan\Desktop\FOQUS-master-24Jan2019\foqus_lib\framework\sim\turbineConfiguration.py", line 689, in deleteSimulation
    main_delete([simName, self.getFile()], None)
  File "C:\Users\jmorgan\AppData\Local\Continuum\anaconda3\lib\site-packages\turbineclient-2016.04.00_41_g3892a66-py3.6.egg\turbine\commands\turbine_simulation_script.py", line 223, in main_delete
    page = delete_page(configFile, SECTION, subresource='%s' %simulationName)
  File "C:\Users\jmorgan\AppData\Local\Continuum\anaconda3\lib\site-packages\turbineclient-2016.04.00_41_g3892a66-py3.6.egg\turbine\commands\__init__.py", line 321, in delete_page
    p = _opener.open(request)
AttributeError: 'NoneType' object has no attribute 'open'

**Comment by boverhof** [comment]
I'm currently looking at it.  In python3 the urllibs are not automatically encoding/decoding to "latin-1".  So likely that is the issue here.

**Comment by boverhof** [comment]
@eslickj First thing I notice that seems wrong is the "turbine.cfg" file generated by FOQUS is empty.  So I'm getting no section "Authorization" errors from the ConfigParser.get operations.

I'm almost certain FOQUS generated a "default" TurbineLite configuration, not an empty one.

**Comment by boverhof** [comment]
First problem, can't open files as "binary" as write strings:

```diff --git a/foqus_lib/framework/sim/turbineConfiguration.py b/foqus_lib/framewo
rk/sim/turbineConfiguration.py
index c87a34d..69438c0 100644
--- a/foqus_lib/framework/sim/turbineConfiguration.py
+++ b/foqus_lib/framework/sim/turbineConfiguration.py
@@ -613,7 +613,7 @@ class turbineConfiguration():
         if overwrite == True or not os.path.isfile(path):
             try:
                 config = self.turbineConfigParse()
-                with open(path, 'wb') as configfile:
+                with open(path, 'w') as configfile:
                     config.write(configfile)
             except Exception as e:
                 raise TurbineInterfaceEx(```

**Comment by boverhof** [comment]
## Issue
More binary/string comparison issues..
Attempt to upload FOQUS session to Turbine
## Traceback
```
2019-01-28 18:19:21,998 - CRITICAL - foqus.__main__ - unhandled exception
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\FOQUS\foqus_lib\gui\main\mainWindow.py", line 1225, in uploadSession
    self.dat.flowsheet.uploadFlowseetToTurbine(dat=self.dat, reset=False)
  File "C:\Users\Administrator\Desktop\FOQUS\foqus_lib\framework\graph\graph.py", line 455, in uploadFlowseetToTurbine
    update=True)
  File "C:\Users\Administrator\Desktop\FOQUS\foqus_lib\framework\sim\turbineConfiguration.py", line 1400, in uploadSimulation
    if not re.match("^([A-Za-z0-9_]+$)", name):
  File "C:\ProgramData\Anaconda3\lib\re.py", line 173, in match
    return _compile(pattern, flags).match(string)
TypeError: cannot use a string pattern on a bytes-like object
```
## Partial fix
```
diff --git a/foqus_lib/framework/sim/turbineConfiguration.py b/foqus_lib/framewo
rk/sim/turbineConfiguration.py
index c87a34d..c49699c 100644
--- a/foqus_lib/framework/sim/turbineConfiguration.py
+++ b/foqus_lib/framework/sim/turbineConfiguration.py
@@ -613,7 +613,7 @@ class turbineConfiguration():
         if overwrite == True or not os.path.isfile(path):
             try:
                 config = self.turbineConfigParse()
-                with open(path, 'wb') as configfile:
+                with open(path, 'w') as configfile:
                     config.write(configfile)
             except Exception as e:
                 raise TurbineInterfaceEx(
@@ -1396,7 +1396,7 @@ class turbineConfiguration():
         '''
         # Check that the simulation name only contains:
         # letters, numbers, and _
-        name = simName.encode('utf-8')
+        name = simName
         if not re.match("^([A-Za-z0-9_]+$)", name):
             raise TurbineInterfaceEx(
                 code = 301,
diff --git a/foqus_lib/version/version.py b/foqus_lib/version/version.py
index 4f92187..ddc2c50 100644
--- a/foqus_lib/version/version.py
+++ b/foqus_lib/version/version.py
@@ -8,7 +8,7 @@ See LICENSE.md for license and copyright details.
 from __future__ import absolute_import, division, print_function
 import argparse, sys

-version = "2017.12.0.0" #Build in Jenkins inserts build number
+version = "3.0.0.0" #Build in Jenkins inserts build number
 copyright = "See LICENSE.md for license and copyright details."
 license = "See LICENSE.md for license and copyright details."
 author = "CCSI FOQUS Team"
```

**Comment by ksbeattie** [comment]
@eslickj will take a whack at this.

**Comment by eslickj** [comment]
Should be fixed in PR #367
