### ISSUE TITLE
Problem Running Turbine Model in Flowsheet

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#370]
- I managed to upload a model into Turbine in the Py3 version of FOQUS.
- But when I tried to run the model, FOQUS reported a failure.
- Below is the log message from FOQUS:

2019-02-05 11:49:29,963 - DEBUG - foqus.foqus_lib.framework.graph.graph - Running flowsheet(s) locally
2019-02-05 11:49:30,150 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - Starting simulation consumer...
2019-02-05 11:49:30,275 - ERROR - foqus.foqus_lib.framework.graph.graph - Exception in graph thread
Traceback (most recent call last):
File "C:\Users\fsoepyan\Desktop\Research Files\GitHub_Downloads\FOQUS-master-py3-02.05.2019\foqus_lib\framework\graph\graph.py", line 817, in run
self.solve()
File "C:\Users\fsoepyan\Desktop\Research Files\GitHub_Downloads\FOQUS-master-py3-02.05.2019\foqus_lib\framework\graph\graph.py", line 985, in solve
self.runGraph(order)
File "C:\Users\fsoepyan\Desktop\Research Files\GitHub_Downloads\FOQUS-master-py3-02.05.2019\foqus_lib\framework\graph\graph.py", line 1252, in runGraph
elif self.runNode(name) != 0:
File "C:\Users\fsoepyan\Desktop\Research Files\GitHub_Downloads\FOQUS-master-py3-02.05.2019\foqus_lib\framework\graph\graph.py", line 1264, in runNode
node.runCalc()
File "C:\Users\fsoepyan\Desktop\Research Files\GitHub_Downloads\FOQUS-master-py3-02.05.2019\foqus_lib\framework\graph\node.py", line 447, in runCalc
self.runModel()
File "C:\Users\fsoepyan\Desktop\Research Files\GitHub_Downloads\FOQUS-master-py3-02.05.2019\foqus_lib\framework\graph\node.py", line 467, in runModel
self.runTurbineCalc(retry=self.options["Retry"].value)
File "C:\Users\fsoepyan\Desktop\Research Files\GitHub_Downloads\FOQUS-master-py3-02.05.2019\foqus_lib\framework\graph\node.py", line 639, in runTurbineCalc
configProfile.startConsumer(self.name, self.modelName)
File "C:\Users\fsoepyan\Desktop\Research Files\GitHub_Downloads\FOQUS-master-py3-02.05.2019\foqus_lib\framework\sim\turbineConfiguration.py", line 327, in startConsumer
db = self.getTurbineLiteDB()
File "C:\Users\fsoepyan\Desktop\Research Files\GitHub_Downloads\FOQUS-master-py3-02.05.2019\foqus_lib\framework\sim\turbineConfiguration.py", line 222, in getTurbineLiteDB
db = turbineLiteDB.turbineLiteDB()
NameError: name 'turbineLiteDB' is not defined
2019-02-05 11:49:30,696 - ERROR - foqus.foqus_lib.gui.main.mainWindow - to results graph thread was likely terminated

**Comment by fsoepyan** [comment]
I tried the installation instructions, and then running a Turbine model, but I'm still having issues.

I have Anaconda 3 installed in my computer.

Questions:
- Can you please let me know where I need to type in "pip install -r requirements.txt"?
- Do I need to uninstall/install Turbine, adodbapi, etc.?

**Comment by fsoepyan** [comment]
After following the latest installation instructions, I managed to upload a model into Turbine, and run the model in FOQUS.

If nobody else is having this issue, I think we can close this issue.
