### ISSUE TITLE
Problem importing turbineLiteDB

### ISSUE THREAD

**Issue by jmorgan29** [CCSI-Toolset/FOQUS#374]
When opening FOQUS, I notice that the command window states 'Problem importing turbineLiteDB'. I receive an error when attempting to upload a model to Turbine, and the FOQUS log reports the following:

2019-02-05 13:57:01,784 - ERROR - foqus.foqus_lib.framework.sim.turbineConfiguration - Error getting list of simulation from Turbine
Traceback (most recent call last):
  File "c:\users\jmorgan\desktop\foqus-master-2_5_2019\foqus_lib\framework\sim\turbineConfiguration.py", line 618, in getSimulationList
    main_list([self.getFile()], None)
  File "C:\Users\jmorgan\AppData\Local\Continuum\anaconda3\lib\site-packages\turbineclient-2016.04.00_41_g3892a66-py3.6.egg\turbine\commands\turbine_simulation_script.py", line 196, in main_list
    content = get_page(configFile, SECTION, **query)
  File "C:\Users\jmorgan\AppData\Local\Continuum\anaconda3\lib\site-packages\turbineclient-2016.04.00_41_g3892a66-py3.6.egg\turbine\commands\__init__.py", line 394, in get_page
    return get_page_by_url(url, configFile, **extra_query)
  File "C:\Users\jmorgan\AppData\Local\Continuum\anaconda3\lib\site-packages\turbineclient-2016.04.00_41_g3892a66-py3.6.egg\turbine\commands\__init__.py", line 380, in get_page_by_url
    _setup(configFile, url)
  File "C:\Users\jmorgan\AppData\Local\Continuum\anaconda3\lib\site-packages\turbineclient-2016.04.00_41_g3892a66-py3.6.egg\turbine\commands\__init__.py", line 257, in _setup
    urllib.error.HTTPErrorProcessor]
AttributeError: module 'urllib.error' has no attribute 'HTTPErrorProcessor'
2019-02-05 13:57:22,090 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - Uploading simulation to turbine.
modelFile: C:\Users\jmorgan\Documents\ExcelFOQUSExample.xlsx
resourceType: spreadsheet
app: Excel
oth: []

I downloaded the FOQUS source code from the Master branch on 5 Feb. 2019 and the '2018 October FIPS Compliant Release' of TurbineLite. I have verified that replacing the TurbineLite with the '2018 August Release' will not solve the problem.

**Comment by ksbeattie** [comment]
@jmorgan29, just curious, what was the solution to this?

**Comment by jmorgan29** [comment]
@ksbeattie, While installing FOQUS, I was referring the YouTube videos that were intended for the Python 2 version.  I had overlooked Step #8 in the INSTALL.md file "pip install -r requirements.txt", a new requirement for the Python 3 version that was not included in the video.
