### ISSUE TITLE
FOQUS cannot locate files

### ISSUE THREAD

**Issue by jmorgan29** [CCSI-Toolset/FOQUS#396]
I am including two issues here which seem to be related.

In the SDOE tab, I generate a space filling design, and then click 'Plot SDOE', and the following results:

2019-02-19 10:14:39,641 - CRITICAL - foqus.__main__ - unhandled exception
Traceback (most recent call last):
  File "c:\users\jmorgan\desktop\foqus-master - **2\foqus_lib\gui\sdoe\sdoePreview.py",** line 113, in plotSdoe
    sdoe.plot(fname, show=show)
  File "c:\users\jmorgan\desktop\foqus-master - 2\foqus_lib\framework\sdoe\sdoe.py", line 68, in plot
    df = load(fname)
  File "c:\users\jmorgan\desktop\foqus-master - 2\foqus_lib\framework\sdoe\df_utils.py", line 11, in load
    df = pd.read_csv(fname)
  File "C:\Users\jmorgan\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\jmorgan\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\jmorgan\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "C:\Users\jmorgan\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Users\jmorgan\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\parsers.py", line 1708, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas\_libs\parsers.pyx", line 384, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas\_libs\parsers.pyx", line 695, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: File b'C:Users\\jmorgan\\Documents\\FOQUS\\SDOE_files\\20190219T101433\\candidates_d4_n1000_w+G+lldg+L' does not exist****

I have verified that the file named 'candidates_d4_n1000_w+G+lldg+L' has been generated in the directory C:\Users\jmorgan\Documents\FOQUS\SDOE_files\20190219T101433, which leads me to believe that the letter 'b' appearing at the beginning of the path that is being searched for may be the issue.

I have also noticed something similar in an example in which I am working in the FOQUS Flowsheet. I have a node containing Python code, and I am trying to read a .csv file (named 'fit.csv') located in a local directory. I get the following error:

2019-02-19 10:22:30,231 - ERROR - foqus.foqus_lib.framework.graph.node - Error in node python code
Traceback (most recent call last):
  File "c:\users\jmorgan\desktop\foqus-master - 2\foqus_lib\framework\graph\node.py", line 528, in runPython
    exec(self.pythonCode)
  File "<string>", line 24, in <module>
  File "C:\Users\jmorgan\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\jmorgan\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\jmorgan\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "C:\Users\jmorgan\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Users\jmorgan\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\parsers.py", line 1708, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas\_libs\parsers.pyx", line 384, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas\_libs\parsers.pyx", line 695, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: File b'fit.csv' does not exist

The 'b' appearing at the beginning of the file name leads me to believe that this may be related to the issue encountered in the SDOE module.

**Comment by sotorrio1** [comment]
Hi @jmorgan29 
I just created PR #397 to try to fix SDOE's part of the issue. It was working in Mac but it looks like Windows has a concept of current directory for each drive. Because of that, "c:sourcedir" means "sourcedir" inside the current C: directory, and you'll need to specify an absolute directory. There might be a better fix for this, but for now try it out and let me know if it works.
Thanks!

**Comment by eslickj** [comment]
@jmorgan29, for the flowsheet error, is it your node code, or are you trying to load the csv file somewhere else?  Can you attach or send me the example?

**Comment by sotorrio1** [comment]
@jmorgan29 PR #409 should take care of the SDOE issue

**Comment by ksbeattie** [comment]
@jmorgan29, did PR #409 fix both parts of this issue?

**Comment by sotorrio1** [comment]
PR #409 fixed only the SDOE side of things. I'm not sure if @eslickj fixed the flowsheet issue

**Comment by jmorgan29** [comment]
I checked and I still get the same error when trying to access a .csv file from within the Node Script for use in a user-defined function. Since this is for a specific project that I am working on rather than an example problem, it might not be likely that another user will encounter this same problem. I think it would be fine to close issue #397 and I can create another one specific to the Flowsheet to be considered in the next release.

**Comment by eslickj** [comment]
@jmorgan29, what's the node script code you are running?  I'm still not clear on where the error is coming from.

**Comment by jmorgan29** [comment]
@eslickj, here is the node script code:

![foqus_findfileerror](https://user-images.githubusercontent.com/11306727/53817924-08810300-3f35-11e9-94f4-22a2bf93ddf7.jpg)


I am adding a folder called 'JCM_Library' to the path for use in the node. I am able to import the function 'Hvap_interp' from the file 'jcm_functions.py', but get the error when trying to use 'fit.csv', which is also located in the 'JCM_Library' folder. I think the issues is that the 'b' is added to the beginning of the file name in FOQUS.

**Comment by sotorrio1** [comment]
@jmorgan29 I think the issue here is that using sys.path python will find the modules but not the .csv files. For the csv file you will need to provide and absolute path, something like:

Table = np.array(pd.read_csv(os.path.join(r'C:\Users\jmorgan\Documents\Python Scripts\JCM_Library', 'fit.csv')))

**Comment by jmorgan29** [comment]
@sotorrio1, I was able to run the node when making this modification. Thank you for clarifying this. I will go ahead and close this issue.
