### ISSUE TITLE
FOQUS examples/Optimization/Opt_Test_02.foqus:  ERROR on load

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/FOQUS#421]
### Opt_Test_02:  ERROR
```
2019-03-05 19:23:19,345 - ERROR - foqus.foqus_lib.framework.sampleResults.results - Error loading stored results
Traceback (most recent call last):
  File "c:\users\administrator\desktop\foqus\foqus_lib\framework\sampleResults\results.py", line 259, in loadDict
    columns = sd["__columns"]
KeyError: '__columns'
2019-03-05 19:23:19,345 - CRITICAL - foqus.__main__ - unhandled exception
Traceback (most recent call last):
  File "c:\users\administrator\desktop\foqus\foqus_lib\gui\main\mainWindow.py", line 1070, in loadData
    self.dat.load(fileName)
  File "c:\users\administrator\desktop\foqus\foqus_lib\framework\session\session.py", line 498, in load
    self.loadDict(sd, filename, stopConsumers=stopConsumers)
  File "c:\users\administrator\desktop\foqus\foqus_lib\framework\session\session.py", line 535, in loadDict
    self.flowsheet.loadDict(sd["flowsheet"])
  File "c:\users\administrator\desktop\foqus\foqus_lib\framework\graph\graph.py", line 268, in loadDict
    self.input.loadDict(temp)
  File "c:\users\administrator\desktop\foqus\foqus_lib\framework\graph\nodeVars.py", line 199, in loadDict
    self.addVariable(node, var).loadDict(sd[node][var])
  File "c:\users\administrator\desktop\foqus\foqus_lib\framework\graph\nodeVars.py", line 555, in loadDict
    self.value = hist[0]
  File "c:\users\administrator\desktop\foqus\foqus_lib\framework\graph\nodeVars.py", line 410, in __setattr__
    self.setValue(val)
  File "c:\users\administrator\desktop\foqus\foqus_lib\framework\graph\nodeVars.py", line 387, in setValue
    self.__value = self.dtype(val)
TypeError: float() argument must be a string or a number, not 'list'

```
###

**Comment by eslickj** [comment]
Its and outdated example will remove.  I'll add it to PR #425 momentarily.
