### ISSUE TITLE
Surrogates: Problem generating ACOSSO

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#433]
When I tried to generate an ACOSSO surrogate model, I got these error messages:

Starting ACOSSO
Model File: acosso_fit.rds
Py File (UQ): acosso_example_uq.py
RScript Path: C:\Program Files\R\R-3.5.1\bin\Rscript.exe
Sub-directory: acosso
X data file: acosso\xdat.csv
Y data file: acosso\ydat.csv
Order: 2
CV: bic

Exporting Data...
Inputs: ["stupid.x1", "stupid.x2", "stupid.x3"]
Traceback (most recent call last):

File "C:\Users\fsoepyan\Desktop\Research Files\GitHub_Downloads\foqus-eslickj-fix_alamo-03.07.2019\foqus_lib\framework\surrogate\ACOSSO.py", line 202, in run
self.dat.flowsheet.results.exportVarsCVS(

File "C:\Users\fsoepyan\AppData\Local\Continuum\anaconda3\envs\foqus\lib\site-packages\pandas\core\generic.py", line 5067, in getattr
return object.getattribute(self, name)

AttributeError: 'Results' object has no attribute 'exportVarsCVS'

**Comment by eslickj** [comment]
this is fixed and tested in PR #437
