### ISSUE TITLE
Surrogates: Problem generating BSS-ANOVA

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#434]
When I tried to generate a BSS-ANOVA surrogate model, I got these error messages:

Starting BSS-ANOVA
Model File: bssanova_fit.rds
Py File (UQ): bssanova_example_uq.py
RScript Path: C:\Program Files\R\R-3.5.1\bin\Rscript.exe
Sub-directory: bssanova
X data file: bssanova\xdat.csv
Y data file: bssanova\ydat.csv
Burn In: 0
MCMC Iterations: 1000
Record Interval: 1
N. Terms: 25
Order: 2
Prior Prob.: 0.5
bte: [0, 1000, 1]

Exporting Data...
Inputs: ["stupid.x1", "stupid.x2", "stupid.x3"]
Traceback (most recent call last):

File "C:\Users\fsoepyan\Desktop\Research Files\GitHub_Downloads\foqus-eslickj-fix_alamo-03.07.2019\foqus_lib\framework\surrogate\BSS-ANOVA.py", line 230, in run
self.dat.flowsheet.results.exportVarsCVS(

File "C:\Users\fsoepyan\AppData\Local\Continuum\anaconda3\envs\foqus\lib\site-packages\pandas\core\generic.py", line 5067, in getattr
return object.getattribute(self, name)

AttributeError: 'Results' object has no attribute 'exportVarsCVS'

**Comment by eslickj** [comment]
This is fixed and tested in PR #437
