### ISSUE TITLE
AWS testing with OUU and BFB file

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#561]
BFB example that we plan on using for testing AWS into GitHub: 
     https://github.com/fsoepyan/FOQUS/tree/reorganization/examples

The files include:
- The FOQUS file (BFB_OUU_08_20_2019)
- The Aspen Custom Modeler (ACM) file (BFB_v11_FBS_01_26_2018)
- The SimSinter json file (BFB_v11_FBS_01_26_2018)

Testing on the AWS FOQUS Cloud will be documented here.

Related Pull Requests:
- FOQUS
-- https://github.com/CCSI-Toolset/FOQUS/pull/563
- TurbineClient
-- https://github.com/CCSI-Toolset/turb_client/pull/14

**Comment by boverhof** [comment]
## Successfully ran the flowsheet from my MAC to the FOQUS cloud.
## Turbine configuration
```
(py3) joshuas-mbp:foqus_working_dir boverhof$ cat turbine.cfg 
[Simulation]
url = https://b7x9ucxadg.execute-api.us-east-1.amazonaws.com/development/simulation
SignedUrl = True
[Session]
url = https://b7x9ucxadg.execute-api.us-east-1.amazonaws.com/development/session
[Job]
url = https://b7x9ucxadg.execute-api.us-east-1.amazonaws.com/development/job
[Application]
url = https://b7x9ucxadg.execute-api.us-east-1.amazonaws.com/development/application
[Consumer]
url =
[Authentication]
username = test
password = changeme
```

**Comment by boverhof** [comment]
## Optimization Run
Using NLOpt for solver and 
## Need to use new turb_client with support for S3 SignedURLs

**Comment by fsoepyan** [comment]
2019-08-23 13:05:33,177 - DEBUG - turbine.commands - HTTPS OPEN
2019-08-23 13:06:53,260 - DEBUG - turbine.commands - passman "https://b7x9ucxadg.execute-api.us-east-1.amazonaws.com/developmen/session/" password already registered
2019-08-23 13:06:53,260 - INFO - turbine.commands - post_page_by_url: url="https://b7x9ucxadg.execute-api.us-east-1.amazonaws.com/developmen/session/"
2019-08-23 13:06:53,261 - DEBUG - turbine.commands - HTTPS OPEN

**Comment by fsoepyan** [comment]
I moved the BFB example that we plan on using for testing AWS into GitHub into a different folder:
https://github.com/fsoepyan/FOQUS/tree/reorganization/examples/test_files/OUU_Remote_Turbine_BFB

The files (the same as the previous ones) include:
- The FOQUS file (BFB_OUU_08_20_2019)
- The Aspen Custom Modeler (ACM) file (BFB_v11_FBS_01_26_2018)
- The SimSinter json file (BFB_v11_FBS_01_26_2018)

**Comment by boverhof** [comment]
# Testing FOQUS/TurbineLite master
-- windows 2008 server
-- python 3.7.3
-- flowsheet: BFB_OUU_08_20_2019 ( from above )

# Error
```2019-09-11 19:25:56,211 - DEBUG - foqus.foqus_lib.framework.graph.graph - Running flowsheet(s) locally
2019-09-11 19:25:56,211 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - turbine configuration application
 url="http://localhost:8000/TurbineLite/application/"
2019-09-11 19:25:56,211 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - turbine configuration url="http:/
/localhost:8000/TurbineLite"
2019-09-11 19:25:56,226 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - Starting simulation consumer...
2019-09-11 19:25:56,711 - ERROR - foqus.foqus_lib.framework.sim.turbineConfiguration - Error getting simulation applicat
ion
Traceback (most recent call last):
  File "c:\users\administrator\desktop\foqus\foqus_lib\framework\sim\turbineConfiguration.py", line 283, in getSimApplic
ation
    tb=traceback.format_exc())
foqus_lib.framework.sim.turbineConfiguration.TurbineInterfaceEx: 360 - Could not find simulation, Could not find simulat
ion: BFB_v11_FBS_01_26_2018


2019-09-11 19:25:56,726 - ERROR - foqus.foqus_lib.framework.graph.node - Error in node python code
Traceback (most recent call last):
  File "c:\users\administrator\desktop\foqus\foqus_lib\framework\sim\turbineConfiguration.py", line 283, in getSimApplic
ation
    tb=traceback.format_exc())
foqus_lib.framework.sim.turbineConfiguration.TurbineInterfaceEx: 360 - Could not find simulation, Could not find simulat
ion: BFB_v11_FBS_01_26_2018



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\administrator\desktop\foqus\foqus_lib\framework\graph\node.py", line 528, in runPython
    exec(self.pythonCode)
  File "<string>", line 3, in <module>
  File "c:\users\administrator\desktop\foqus\foqus_lib\framework\graph\node.py", line 467, in runModel
    self.runTurbineCalc(retry=self.options["Retry"].value)
  File "c:\users\administrator\desktop\foqus\foqus_lib\framework\graph\node.py", line 639, in runTurbineCalc
    configProfile.startConsumer(self.name, self.modelName)
  File "c:\users\administrator\desktop\foqus\foqus_lib\framework\sim\turbineConfiguration.py", line 303, in startConsume
r
    app = self.getSimApplication(simName)
  File "c:\users\administrator\desktop\foqus\foqus_lib\framework\sim\turbineConfiguration.py", line 290, in getSimApplic
ation
    tb=traceback.format_exc())
foqus_lib.framework.sim.turbineConfiguration.TurbineInterfaceEx: 0 - Unknown Error, Error getting simulation application

Traceback (most recent call last):
  File "c:\users\administrator\desktop\foqus\foqus_lib\framework\sim\turbineConfiguration.py", line 283, in getSimApplic
ation
    tb=traceback.format_exc())
foqus_lib.framework.sim.turbineConfiguration.TurbineInterfaceEx: 360 - Could not find simulation, Could not find simulat
ion: BFB_v11_FBS_01_26_2018

```

**Comment by ksbeattie** [comment]
@fsoepyan will schedule some testing time with @boverhof on this.

**Comment by boverhof** [comment]
@fsoepyan and @boverhof used the FOQUS Cloud to run a cost Optimization with BFB, seems like it worked.  It was taking a while, but I've since noticed four? iterations have completed with a single job error.  So I think the system is generally working.  

I'm not sure about "reset=False" working.  I'd also like @fsoepyan to run this optimization or a smaller one on a FOQUS/TurbineLite setup and use the results from that run to validate a FOQUS Cloud run.
