### ISSUE TITLE
Test Release 3.3.0:  Windows 2008 server client

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/FOQUS#601]
# Download Release POWERSHELL
```
PS C:\Users\Administrator> [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
PS C:\Users\Administrator> Invoke-WebRequest -Uri https://github.com/CCSI-Toolset/FOQUS/archive/3.3.0.tar.gz -OutFile  f
oqus-3.3.0.tar.gz
PS C:\Users\Administrator>
```
# Anaconda 3
```
% pip install foqus-3.3.0.tar.gz
(foqus) C:\Users\Administrator\Desktop>pip install foqus-3.3.0.tar.gz
Processing c:\users\administrator\desktop\foqus-3.3.0.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'C:\ProgramData\Anaconda3\envs\foqus\python.exe' -c 'import sys, s
etuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Tem
p\\2\\pip-req-build-vjvlwdeg\\setup.py'"'"'; __file__='"'"'C:\\Users\\ADMINI~1\\
AppData\\Local\\Temp\\2\\pip-req-build-vjvlwdeg\\setup.py'"'"';f=getattr(tokeniz
e, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n
'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-b
ase 'C:\Users\ADMINI~1\AppData\Local\Temp\2\pip-req-build-vjvlwdeg\pip-egg-info'

         cwd: C:\Users\ADMINI~1\AppData\Local\Temp\2\pip-req-build-vjvlwdeg\
    Complete output (22 lines):
    Setting version as 3.3.0
    running egg_info
    creating C:\Users\ADMINI~1\AppData\Local\Temp\2\pip-req-build-vjvlwdeg\pip-e
gg-info\foqus.egg-info
    writing C:\Users\ADMINI~1\AppData\Local\Temp\2\pip-req-build-vjvlwdeg\pip-eg
g-info\foqus.egg-info\PKG-INFO
    writing dependency_links to C:\Users\ADMINI~1\AppData\Local\Temp\2\pip-req-b
uild-vjvlwdeg\pip-egg-info\foqus.egg-info\dependency_links.txt
    writing top-level names to C:\Users\ADMINI~1\AppData\Local\Temp\2\pip-req-bu
ild-vjvlwdeg\pip-egg-info\foqus.egg-info\top_level.txt
    writing manifest file 'C:\Users\ADMINI~1\AppData\Local\Temp\2\pip-req-build-
vjvlwdeg\pip-egg-info\foqus.egg-info\SOURCES.txt'
    reading manifest file 'C:\Users\ADMINI~1\AppData\Local\Temp\2\pip-req-build-
vjvlwdeg\pip-egg-info\foqus.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.ui' under directory 'dmf_lib'
    warning: no files found matching '*.txt' under directory 'foqus_lib\help'
    writing manifest file 'C:\Users\ADMINI~1\AppData\Local\Temp\2\pip-req-build-
vjvlwdeg\pip-egg-info\foqus.egg-info\SOURCES.txt'
    INFO: Could not find files for the given pattern(s).
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ADMINI~1\AppData\Local\Temp\2\pip-req-build-vjvlwdeg\setup.
py", line 70, in <module>
        ["where", "$PATH:foqus.py"]).decode('utf-8').split("\n")[0].strip()
      File "C:\ProgramData\Anaconda3\envs\foqus\lib\subprocess.py", line 395, in
 check_output
        **kwargs).stdout
      File "C:\ProgramData\Anaconda3\envs\foqus\lib\subprocess.py", line 487, in
 run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['where', '$PATH:foqus.py']' returne
d non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check th
e logs for full command output.

(foqus) C:\Users\Administrator\Desktop>
```

## pytest version
Note if you run this in the foqus environment it will give same traceback as above no matter what directory you run it in..

```
(base) C:\Users\Administrator>pytest --version
This is pytest version 4.0.2, imported from C:\ProgramData\Anaconda3\lib\site-pa
ckages\pytest.py
setuptools registered plugins:
  pytest-remotedata-0.3.1 at C:\ProgramData\Anaconda3\lib\site-packages\pytest_r
emotedata\plugin.py
  pytest-openfiles-0.3.1 at C:\ProgramData\Anaconda3\lib\site-packages\pytest_op
enfiles\plugin.py
  pytest-doctestplus-0.2.0 at C:\ProgramData\Anaconda3\lib\site-packages\pytest_
doctestplus\plugin.py
  pytest-arraydiff-0.3 at C:\ProgramData\Anaconda3\lib\site-packages\pytest_arra
ydiff\plugin.py

```

**Comment by boverhof** [comment]
# Second Try ( manually untar )
```
(foqus) C:\Users\Administrator\Desktop>python -c "import tarfile; tar = tarfile.
open('foqus-3.3.0.tar.gz'); tar.extractall() ; tar.close()"

(foqus) C:\Users\Administrator\Desktop>dir FOQUS-3.3.0
 Volume in drive C has no label.
 Volume Serial Number is 6249-70C2

 Directory of C:\Users\Administrator\Desktop\FOQUS-3.3.0

10/09/2019  11:43 PM    <DIR>          .
10/09/2019  11:43 PM    <DIR>          ..
10/09/2019  11:43 PM    <DIR>          .circleci
10/09/2019  11:43 PM               505 .gitignore
10/09/2019  11:43 PM                 0 .gitmodules
10/09/2019  11:43 PM    <DIR>          cloud
10/09/2019  11:43 PM    <DIR>          docs
10/09/2019  11:43 PM    <DIR>          examples
10/09/2019  11:43 PM             1,259 FAQs.md
10/09/2019  11:43 PM            88,204 foqus.ico
10/09/2019  11:43 PM            32,469 foqus.py
10/09/2019  11:43 PM               380 foqus_env.yml
10/09/2019  11:43 PM               357 foqus_env_ssh.yml
10/09/2019  11:43 PM    <DIR>          foqus_lib
10/09/2019  11:43 PM               422 foqus_sinter_configure.py
10/09/2019  11:43 PM                42 icons_rc.py
10/09/2019  11:43 PM             4,506 LICENSE.md
10/09/2019  11:43 PM               833 Makefile
10/09/2019  11:43 PM               148 MANIFEST.in
10/09/2019  11:43 PM               261 pytest.ini
10/09/2019  11:43 PM             3,528 README.md
10/09/2019  11:43 PM               181 requirements.txt
10/09/2019  11:43 PM             5,178 setup.py
10/09/2019  11:43 PM    <DIR>          test
              16 File(s)        138,273 bytes
               8 Dir(s)  37,071,958,016 bytes free

(foqus) C:\Users\Administrator\Desktop>
```

**Comment by boverhof** [comment]
# FOQUS Remote Turbine Simulation Upload failed..



<img width="529" alt="Screen Shot 2019-10-22 at 2 37 13 PM" src="https://user-images.githubusercontent.com/738295/67336010-7b95b480-f4d9-11e9-8068-4edd0303835e.png">

**Comment by boverhof** [comment]
## GIt repo boverhof-patch1 
Failed in same way..
