### ISSUE TITLE
Supported python3 versions

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/FOQUS#616]
# Description
## python 3.7
- Bug:  https://bugs.python.org/issue37549 
- Must use python 3.7.3 because 3.7.4 has a bug
- Windows 2016 Server

```
(foqus) C:\Users\Administrator\Desktop\FOQUS>pytest --version
Traceback (most recent call last):
  File "c:\programdata\anaconda3\envs\foqus\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
   ...
    sys.stdin = _reopen_stdio(sys.stdin, "rb")
  File "c:\programdata\anaconda3\envs\foqus\lib\site-packages\_pytest\capture.py", line 812, in _reopen_stdio
    open(os.dup(f.fileno()), mode, buffering),
OSError: [WinError 87] The parameter is incorrect
```
- workaround
```
conda create -n foqus python=3.7.3 pip
```

**Comment by boverhof** [comment]
python 3.7.5 works

```
(foqus) C:\Users\Administrator\Desktop\FOQUS>python --version
Python 3.7.5

(foqus) C:\Users\Administrator\Desktop\FOQUS>
(foqus) C:\Users\Administrator\Desktop\FOQUS>pytest
================================================= test session starts =================================================
platform win32 -- Python 3.7.5, pytest-5.2.2, py-1.8.0, pluggy-0.13.0
rootdir: C:\Users\Administrator\Desktop\FOQUS, inifile: pytest.ini, testpaths: foqus_lib
collected 8 items

foqus_lib\framework\sampleResults\test\results_s3_test.py .....                                                  [ 62%]
foqus_lib\service\test\flowsheet_control_test.py ...                                                             [100%]

================================================== 8 passed in 1.66s ==================================================

(foqus) C:\Users\Administrator\Desktop\FOQUS>
```

**Comment by boverhof** [comment]
@ksbeattie so we can change everything over to python-3.7.5

**Comment by ksbeattie** [comment]
@boverhof I've got that change in PR #629, could you review?
