### ISSUE TITLE
FOQUS Cloud Expired Job Handling

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/FOQUS#666]
# Description
If a `job` entry is missing in `DynamoDB` table it is interpreted as `state=expired`.  This is because TTL is set on table entries requiring liveliness (job, consumers).  Expired Jobs are not handled correctly by the `foqus-sns-update` function.

# CloudWatch Log
```
START RequestId: 88d42fa8-6173-412c-8909-577616e55e91 Version: $LATEST
2020-01-18T04:23:35.807Z foqus-sns-update Received event: [
{
    "resource": "job",
    "event": "status",
    "rc": 0,
    "status": "expired",
    "jobid": "b678ed8e-b410-49e8-8282-8790d2e93596",
    "instanceid": "i-0307ecf4672e6ebd7",
    "consumer": "5c58fba7-be46-440a-9c88-259e74d915d1",
    "sessionid": "9cab11d6-d3fb-42af-8231-ed28f882f2ce",
    "message": "Job b678ed8e-b410-49e8-8282-8790d2e93596 expired:  Not in DynamoDB table FOQUS_Resources"
}
]
2020-01-18T04:23:35.807Z foqus-sns-update.process_job_event_status status=expired username=boverhof,  job=b678ed8e-b410-49e8-8282-8790d2e93596, session=9cab11d6-d3fb-42af-8231-ed28f882f2ce
2020-01-18T04:23:35.809Z	88d42fa8-6173-412c-8909-577616e55e91	ReferenceError: milliseconds is not defined
    at process_job_event_status (/var/task/index.js:289:63)
    at exports.handler (/var/task/index.js:440:19)
END RequestId: 88d42fa8-6173-412c-8909-577616e55e91
```

**Comment by boverhof** [comment]
Fixed.
