### ISSUE TITLE
FOQUS Service exits on job error no simulation

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/FOQUS#677]
# Description
Flowsheet service exits on `job` error if `simulation` is not uploaded.  

# Fix
Handle the exception and look for next `job`.

# Traceback
```
2020-01-28 17:22:39,870 - DEBUG - foqus.foqus_lib.service.flowsheet - Process Flowsheet nodes
2020-01-28 17:22:39,885 - DEBUG - foqus.foqus_lib.service.flowsheet - FOQUSAWSConfig._get: FOQUS-Simulation-Bucket-Name = foqussimulationdev1563311335
2020-01-28 17:22:39,917 - ERROR - foqus.foqus_lib.service.flowsheet - setup foqus exception: Node BFB failure: S3 Bucket foqussimulationdev1563311335 is missing simulation files for "byron/BFB_v11_FBS_01_26_2018/"
Traceback (most recent call last):
  File "c:\users\administrator\desktop\foqus\foqus_lib\service\flowsheet.py", line 495, in run
    dat = self.setup_foqus(db, user_name, job_desc)
  File "c:\users\administrator\desktop\foqus\foqus_lib\service\flowsheet.py", line 716, in setup_foqus
    _setup_flowsheet_turbine_node(dat, nkey, user_name=user_name)
  File "c:\users\administrator\desktop\foqus\foqus_lib\service\flowsheet.py", line 108, in _setup_flowsheet_turbine_node
    assert 'Contents' in l, 'Node %s failure: S3 Bucket %s is missing simulation files for "%s"' %(nkey, bucket_name, prefix)
AssertionError: Node BFB failure: S3 Bucket foqussimulationdev1563311335 is missing simulation files for "byron/BFB_v11_FBS_01_26_2018/"
2020-01-28 17:22:39,932 - INFO - foqus.foqus_lib.service.flowsheet - <class 'foqus_lib.service.flowsheet.TurbineLiteDB'>.job_change_status {'Simulation': 'zzfoqus_BFB', 'Input': {'graph': {}, 'BFB': {'BFBadsB.Dt': 11.897, 'BFBadsB.dx': 0.0127, 'BFBadsB.Lb': 2.085, 'BFBadsM.Dt': 15, 'BFBadsM.dx': 0.06695, 'BFBadsM.Lb': 1.972, 'BFBadsT.Dt': 15, 'BFBadsT.dx': 0.062397, 'BFBadsT.Lb': 2.203, 'BFBRGN.Dt': 9.041, 'BFBRGN.Lb': 8.886, 'BFBRGNTop.Dt': 9.195, 'BFBRGNTop.Lb': 7.1926, 'GHXfg.A_exch': 16358, 'Kd': 100, 'BFBadsB.Cr': 1, 'BFBadsM.Cr': 1, 'BFBadsT.Cr': 1, 'BFBRGN.Cr': 1, 'BFBRGNTop.Cr': 1, 'dp': 0.00015, 'GHXfg.GasIn.P': 1.01325, 'GHXfg.GasIn.T': 54, 'fg_flow': 100377}}, 'Reset': False, 'Id': '96946b1a-4c92-4535-8dd2-b6525a6a09ab', 'resource': 'job', 'status': 'submit', 'jobid': '96946b1a-4c92-4535-8dd2-b6525a6a09ab', 'sessionid': '69a0bd0b-0cf6-4607-b8b9-80ae1d727bdd', 'event': 'status'}
2020-01-28 17:22:39,932 - DEBUG - foqus.foqus_lib.service.flowsheet - _sns_notification obj: {'resource': 'job', 'event': 'status', 'rc': 0, 'status': 'error', 'jobid': '96946b1a-4c92-4535-8dd2-b6525a6a09ab', 'instanceid': 'i-0110e4d89e1c7ba1b', 'consumer': '5fd2453f-3ca0-4072-995a-3517f935a66d', 'sessionid': '69a0bd0b-0cf6-4607-b8b9-80ae1d727bdd', 'message': 'Traceback (most recent call last):\n  File "c:\\users\\administrator\\desktop\\foqus\\foqus_lib\\service\\flowsheet.py", line 495, in run\n    dat = self.setup_foqus(db, user_name, job_desc)\n  File "c:\\users\\administrator\\desktop\\foqus\\foqus_lib\\service\\flowsheet.py", line 716, in setup_foqus\n    _setup_flowsheet_turbine_node(dat, nkey, user_name=user_name)\n  File "c:\\users\\administrator\\desktop\\foqus\\foqus_lib\\service\\flowsheet.py", line 108, in _setup_flowsheet_turbine_node\n    assert \'Contents\' in l, \'Node %s failure: S3 Bucket %s is missing simulation files for "%s"\' %(nkey, bucket_name, prefix)\nAssertionError: Node BFB failure: S3 Bucket foqussimulationdev1563311335 is missing simulation files for "byron/BFB_v11_FBS_01_26_2018/"\n'}
2020-01-28 17:22:39,932 - DEBUG - foqus.foqus_lib.service.flowsheet - _sns_notification event: job.error
2020-01-28 17:22:39,932 - DEBUG - foqus.foqus_lib.service.flowsheet - MessageAttributes: {'event': {'DataType': 'String', 'StringValue': 'job.error'}, 'username': {'DataType': 'String', 'StringValue': 'byron'}}
2020-01-28 17:22:39,948 - DEBUG - foqus.foqus_lib.service.flowsheet - <class 'foqus_lib.service.flowsheet.TurbineLiteDB'>.add_message: {"job": "96946b1a-4c92-4535-8dd2-b6525a6a09ab", "message": "job failed in setup: AssertionError('Node BFB failure: S3 Bucket foqussimulationdev1563311335 is missing simulation files for \"byron/BFB_v11_FBS_01_26_2018/\"')", "consumer": "5fd2453f-3ca0-4072-995a-3517f935a66d", "instanceid": "i-0110e4d89e1c7ba1b", "resource": "job", "exception": "Traceback (most recent call last):\n  File \"c:\\users\\administrator\\desktop\\foqus\\foqus_lib\\service\\flowsheet.py\", line 495, in run\n    dat = self.setup_foqus(db, user_name, job_desc)\n  File \"c:\\users\\administrator\\desktop\\foqus\\foqus_lib\\service\\flowsheet.py\", line 716, in setup_foqus\n    _setup_flowsheet_turbine_node(dat, nkey, user_name=user_name)\n  File \"c:\\users\\administrator\\desktop\\foqus\\foqus_lib\\service\\flowsheet.py\", line 108, in _setup_flowsheet_turbine_node\n    assert 'Contents' in l, 'Node %s failure: S3 Bucket %s is missing simulation files for \"%s\"' %(nkey, bucket_name, prefix)\nAssertionError: Node BFB failure: S3 Bucket foqussimulationdev1563311335 is missing simulation files for \"byron/BFB_v11_FBS_01_26_2018/\"\n"}
```

**Comment by boverhof** [comment]
Tested, Fixed.
