### ISSUE TITLE
3.6.0rc0 broken on Windows

### ISSUE THREAD

**Issue by ksbeattie** [CCSI-Toolset/FOQUS#760]
The 3.6.0rc0 release is broken on Windows:
```
(ccsi-foqus) C:\Users\ksbea\Projects\CCSI\github\CCSI-Toolset\FOQUS>foqus
2020-06-29 20:29:35,468 - DEBUG - foqus.foqus_lib.foqus - Working directory set to C:\Users\ksbea\Projects\CCSI\github\ksbeattie\FOQUS\ksb_foqus
2020-06-29 20:29:35,514 - DEBUG - foqus.foqus_lib.framework.session.session - Initializing session, Log file: C:\Users\ksbea\Projects\CCSI\github\ksbeattie\FOQUS\ksb_foqus\logs\foqus.log, Position: 104333
2020-06-29 20:29:35,514 - INFO - foqus.foqus_lib.framework.plugins.pluginSearch - Loading Plugin: c:\users\ksbea\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\surrogate\ACOSSO.py
2020-06-29 20:29:35,538 - INFO - foqus.foqus_lib.framework.plugins.pluginSearch - Loading Plugin: c:\users\ksbea\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\surrogate\ALAMO.py
2020-06-29 20:29:35,538 - INFO - foqus.foqus_lib.framework.plugins.pluginSearch - Loading Plugin: c:\users\ksbea\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\surrogate\BSS-ANOVA.py
2020-06-29 20:29:35,561 - INFO - foqus.foqus_lib.framework.plugins.pluginSearch - Loading Plugin: c:\users\ksbea\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\optimizer\BFGS.py
2020-06-29 20:29:36,382 - INFO - foqus.foqus_lib.framework.plugins.pluginSearch - Loading Plugin: c:\users\ksbea\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\optimizer\NLopt.py
2020-06-29 20:29:36,382 - INFO - foqus.foqus_lib.framework.plugins.pluginSearch - Loading Plugin: c:\users\ksbea\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\optimizer\OptCMA.py
2020-06-29 20:29:36,522 - INFO - foqus.foqus_lib.framework.plugins.pluginSearch - Loading Plugin: c:\users\ksbea\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\optimizer\PSUADE.py
2020-06-29 20:29:36,522 - INFO - foqus.foqus_lib.framework.plugins.pluginSearch - Loading Plugin: c:\users\ksbea\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\optimizer\Sample.py
2020-06-29 20:29:36,546 - INFO - foqus.foqus_lib.framework.plugins.pluginSearch - Loading Plugin: c:\users\ksbea\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\optimizer\SLSQP.py
2020-06-29 20:29:36,546 - INFO - foqus.foqus_lib.framework.plugins.pluginSearch - Loading Plugin: c:\users\ksbea\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\optimizer\Snobfit.py
2020-06-29 20:29:36,569 - INFO - foqus.foqus_lib.framework.plugins.pluginSearch - Removing plugin, due to missing dependency: NLopt
2020-06-29 20:29:36,569 - INFO - foqus.foqus_lib.framework.plugins.pluginSearch - Removing plugin, due to missing dependency: Snobfit
2020-06-29 20:29:36,569 - INFO - foqus.foqus_lib.framework.plugins.pluginSearch - Loading Plugin: c:\users\ksbea\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\pymodel\heat_integration.py
2020-06-29 20:29:36,593 - INFO - foqus.foqus_lib.framework.plugins.pluginSearch - Loading Plugin: c:\users\ksbea\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\pymodel\pymodel_test.py
2020-06-29 20:29:36,593 - INFO - foqus.foqus_lib.framework.plugins.pluginSearch - Loading Plugin: c:\users\ksbea\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\pymodel\steam_cycle.py
2020-06-29 20:29:36,616 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - turbine configuration application url="http://localhost:8000/TurbineLite/application/"
2020-06-29 20:29:36,616 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - turbine configuration url="http://localhost:8000/TurbineLite"
2020-06-29 20:29:36,804 - CRITICAL - foqus.foqus_lib.foqus - unhandled exception
Traceback (most recent call last):
  File "c:\users\ksbea\anaconda3\envs\ccsi-foqus\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\ksbea\anaconda3\envs\ccsi-foqus\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\ksbea\Anaconda3\envs\ccsi-foqus\Scripts\foqus.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "c:\users\ksbea\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\foqus.py", line 798, in main
    showUQ=not args.nouq, showBasicData=args.basic_data, ts=ts)
  File "c:\users\ksbea\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\foqus.py", line 158, in startGUI
    import foqus_lib.gui.main.mainWindow as MW
  File "c:\users\ksbea\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\gui\main\mainWindow.py", line 29, in <module>
    from foqus_lib.gui.main.Dash import *
  File "c:\users\ksbea\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\gui\main\Dash.py", line 14, in <module>
    uic.loadUiType(os.path.join(mypath, "Dash_UI.ui"))
  File "c:\users\ksbea\anaconda3\envs\ccsi-foqus\lib\site-packages\PyQt5\uic\__init__.py", line 203, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "<string>", line 276, in <module>
ModuleNotFoundError: No module named 'icons_rc'

(ccsi-foqus) C:\Users\ksbea\Projects\CCSI\github\CCSI-Toolset\FOQUS>
```

This is from a `pip install ccsi-foqus==3.6.0rc0` but I've seen this before when installing from source with `pip install .` but running a `pip install -e .` fixed it!  Similarly `pip install -r requirements.txt` works (because it has "-e ." in it).  So it seems that the "-e" - the equivalent to `python setup.py develop` rather and `python setup.py install` (but using pip not easy_install) for some reason fixes it.

I suspect that this might have something to do with that top-level `icons_rc.py` file that is just a guess at this point.

**Comment by eslickj** [comment]
I'm working on this now.

**Comment by eslickj** [comment]
I'm having issues with pywin32 and adodbapi not working when I install this in a new environment.  We had a heck of a time with those packages before, but I thought new version has the stuff sorted out.  I don't know why this is happening again, but I assume other users will see the same if they do a fresh install.

**Comment by eslickj** [comment]
I'll start a new issue for the pywin32 stuff.
