### ISSUE TITLE
New problems with Windows install

### ISSUE THREAD

**Issue by eslickj** [CCSI-Toolset/FOQUS#762]
Old problems with the windows install have come up again.  When I install foqus on a clean conda environment, I get the error below.

```
(foqus) C:\Users\EslickJ\git\foqus>foqus
Traceback (most recent call last):
  File "C:\Users\EslickJ\Miniconda3\envs\foqus\Scripts\foqus-script.py", line 33, in <module>
    sys.exit(load_entry_point('ccsi-foqus==3.7.0.dev0', 'console_scripts', 'foqus')())
  File "C:\Users\EslickJ\Miniconda3\envs\foqus\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Users\EslickJ\Miniconda3\envs\foqus\lib\site-packages\pkg_resources\__init__.py", line 2861, in load_entry_point
    return ep.load()
  File "C:\Users\EslickJ\Miniconda3\envs\foqus\lib\site-packages\pkg_resources\__init__.py", line 2461, in load
    return self.resolve()
  File "C:\Users\EslickJ\Miniconda3\envs\foqus\lib\site-packages\pkg_resources\__init__.py", line 2467, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\Users\EslickJ\Miniconda3\envs\foqus\lib\site-packages\ccsi_foqus-3.7.0.dev0-py3.7.egg\foqus_lib\foqus.py", line 20, in <module>
    from foqus_lib.framework.session.session import *
  File "C:\Users\EslickJ\Miniconda3\envs\foqus\lib\site-packages\ccsi_foqus-3.7.0.dev0-py3.7.egg\foqus_lib\framework\session\session.py", line 17, in <module>
    from foqus_lib.framework.graph.graph import *
  File "C:\Users\EslickJ\Miniconda3\envs\foqus\lib\site-packages\ccsi_foqus-3.7.0.dev0-py3.7.egg\foqus_lib\framework\graph\graph.py", line 23, in <module>
    from foqus_lib.framework.graph.node import *  # Node, input var and output var classes
  File "C:\Users\EslickJ\Miniconda3\envs\foqus\lib\site-packages\ccsi_foqus-3.7.0.dev0-py3.7.egg\foqus_lib\framework\graph\node.py", line 20, in <module>
    from foqus_lib.framework.sim.turbineConfiguration import TurbineInterfaceEx
  File "C:\Users\EslickJ\Miniconda3\envs\foqus\lib\site-packages\ccsi_foqus-3.7.0.dev0-py3.7.egg\foqus_lib\framework\sim\turbineConfiguration.py", line 30, in <module>
    import win32process
ModuleNotFoundError: No module named 'win32process'
```

I can fix this by uninstalling that reinstalling pywin32 with pip.  If I remove pywin32 from setup.py and install it after foqus setup that also works.

**Comment by eslickj** [comment]
This is getting confusing, but I think uninstalling and reinstalling pywin32 works whether it's pip or conda.  So I don't think there is an issue with the package versions.  Maybe some package requires pywin32, but it gets a bad version before our setup.py gets around to installing it?

**Comment by eslickj** [comment]
Also installing pywin32 before installing foqus works.  It looks like everything works as long as pywin32 doesn't get installed as a requirement from foqus's setup.py.  It's not a version issue.  It's the same version either way.

**Comment by anujad95** [comment]
After i update my local master with the upstream master, i am getting this error when i just type 'foqus' in my anaconda prompt:
C:\Users\deshpana\AppData\Local\Continuum\anaconda3\envs\foqus_02\python.EXE: can't open file 'C:\Users\deshpana\FOQUS3\FOQUS\foqus.py': [Errno 2] No such file or directory

**Comment by eslickj** [comment]
Okay, after I properly installed using ```pip install .```, this is fixed.

@anujad95, that foqus.py has been removed.  Just reinstall FOQUS should fix it.

**Comment by anujad95** [comment]
Ok, i will try this. Thanks
