### ISSUE TITLE
SM Optimizer Error?

### ISSUE THREAD

**Issue by eslickj** [CCSI-Toolset/FOQUS#765]
I think we may be missing a requirement in setup.py.  When I start FOQUS I get this warning (doesn't break anything except I assume the SM_Optimizer doesn't work): 

```
Traceback (most recent call last):
  File "c:\users\eslickj\git\foqus\foqus_lib\framework\plugins\pluginSearch.py", line 63, in importPlugins
    importlib.import_module(mname[0])
  File "C:\Users\EslickJ\miniconda3\envs\foqus\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\eslickj\git\foqus\foqus_lib\framework\optimizer\SM_Optimizer.py", line 37, in <module>
    from pyDOE import *
ModuleNotFoundError: No module named 'pyDOE'
```

**Comment by anujad95** [comment]
Yes, actually pyDOE and smt packages need to be installed to run the SM
optimizer. It's in the documentation but it might be better to have it in
the requirements.

**Comment by eslickj** [comment]
That's like the third time today I've been bitten by not reading the docs.

**Comment by ksbeattie** [comment]
Well, I think that we should avoid stack traces being thrown.

@anujad95, we should either suppress the stacktrace, with a message about needed those packages if that plugin will be used (knowing most users won't see it) or add `smt` into the `install_requires` list in `setup.py`.  I would normally say to do the latter but smt pulls in a ton of other packages, like Sphinx and pyDOE2 (is that needed in addition to pyDOE?) which look like they might conflict with what we already have in `setup.py`.

**Comment by ksbeattie** [comment]
It's looking this is has more do to with how the SM_Optimizer plugin reports if it's available or not.

I'd think that if `pyDOE` and/or `smt` is not available it shouldn't throw a stack trace and should just report unavailable.  But even after I `pip install smt pyDOE` I still get:

    2020-06-30 21:21:04,337 - INFO - foqus.foqus_lib.framework.plugins.pluginSearch - Removing plugin, due to missing dependency: SM_Optimizer

when starting.

@anujad95, is this something you can fix soon?

I'm going to hold off on including PR #757 in the next release candidate.  If you can get a fix in soon (i.e. by tomorrow) we might be able to include it in the release.

**Comment by anujad95** [comment]
I'm sorry, I'll make sure that these packages are included in the
requirements file.

**Comment by anujad95** [comment]
Yes Keith I will look into it and try to fix in sometime. I'm sorry.
