### ISSUE TITLE
Issue using candidate and history file in SDOE

### ISSUE THREAD

**Issue by Daison2102** [CCSI-Toolset/FOQUS#828]
Issues when reproducing Examples USF-1 and USF-2 in the Sequential Design of Experiments.

The generated files for the selected designs for the example USF-1, don’t have the Label column when using the version of FOQUS 3.6.0 (see “usf_d8_n10000_X1+X2.csv” in the attached zip file), while that using FOQUS 3.5.1, the generated files for the selected designs do have the Label column (see “usf_d8_n10000_Label+X1+X2.csv” in the attached zip file). This generates an issue when reproducing example USF-2, which use the “SDOE_Ex1_Candidates.csv” as candidate file and the design from example USF-1 as history file (see the attached picture). The issue arises when clicking on the Confirm button to advance to the Ensemble Aggregation Window. Se details of the issue below. This issue seems to be related to the missing label in the history file, which wasn’t generated by FOQUS 3.6.0. If I use the design file generated by FOQUS 3.5.1 instead, no issue arises.

Error
Traceback (most recent call last):
  File "c:\anaconda3\envs\foqus\lib\site-packages\foqus_lib\gui\sdoe\sdoeSetupFrame.py", line 157, in confirmEnsembles
    self.updateAggTable()
  File "c:\anaconda3\envs\foqus\lib\site-packages\foqus_lib\gui\sdoe\sdoeSetupFrame.py", line 357, in updateAggTable
    self.updateAggTableRow(0)
  File "c:\anaconda3\envs\foqus\lib\site-packages\foqus_lib\gui\sdoe\sdoeSetupFrame.py", line 518, in updateAggTableRow
    candidateData, historyData = self.createAggData()
  File "c:\anaconda3\envs\foqus\lib\site-packages\foqus_lib\gui\sdoe\sdoeSetupFrame.py", line 207, in createAggData
    cand_agg, hist_agg = self.aggregateEnsembleList()  # these are dfs
  File "c:\anaconda3\envs\foqus\lib\site-packages\foqus_lib\gui\sdoe\sdoeSetupFrame.py", line 203, in aggregateEnsembleList
    cand_agg, hist_agg = df_utils.check(cand_csv_list, hist_csv_list)
  File "c:\anaconda3\envs\foqus\lib\site-packages\foqus_lib\framework\sdoe\df_utils.py", line 44, in check
    hist_df = hist_df[cols]
  File "c:\anaconda3\envs\foqus\lib\site-packages\pandas\core\frame.py", line 2908, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]
  File "c:\anaconda3\envs\foqus\lib\site-packages\pandas\core\indexing.py", line 1254, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis, raise_missing=raise_missing)
  File "c:\anaconda3\envs\foqus\lib\site-packages\pandas\core\indexing.py", line 1304, in _validate_read_indexer
    raise KeyError(f"{not_found} not in index")
KeyError: "['Label'] not in index"

- **Files**

![Issue using candidate and history file in SDOE](https://user-images.githubusercontent.com/32642037/95383333-02919780-08b9-11eb-83c3-925efcb6c7d4.png)
[Selected design files.zip](https://github.com/CCSI-Toolset/FOQUS/files/5343592/Selected.design.files.zip)

**Comment by sotorrio1** [comment]
This issue and issue #829  should get fixed with PR #831

**Comment by Daison2102** [comment]
Fixed
