### ISSUE TITLE
Error calling GAMS solvers within the SM_Optimizer 

### ISSUE THREAD

**Issue by Daison2102** [CCSI-Toolset/FOQUS#839]
1. The firs issue (Error 1) found when calling GAMS solvers was related to the 'Warmstart’ option, which is not defined in the code, so I just changed it to True in line 440

2. Then, I got the Error 2. This is related to the block of lines 450-572 (implementation of the multi-start initialization), which were included only for the else statement (pyomo solver). I temporally fixed this by removing one indentation to include the block of code for the GAMS solver as well

3. Then, I got the Error 3, and I guess this is somehow related to the multi-start approach, but did not look at in detail this. I just unchecked that option from solver options to solve the problem without the multi-start initialization, but then got the Error 4, which i temporally fixed by commenting the lines 562- 991 associated with that error. With these changes, GAMS solvers run properly, but still the multi-start approach does not work, so it would be great to take care of error 3 and 4

4. Another suggestion to improve the SM_Optimizer would be adding an option to provide the user the flexibility to change the solver options, e.g, choose a specific linear solver for ipopt

**Error 1**
2020-10-26 14:50:51,461 - ERROR - foqus.foqus_lib.framework.optimizer.optimization - Exception in optimization thread
Traceback (most recent call last):
  File "d:\anaconda3\envs\foqus-issues\lib\site-packages\foqus_lib\framework\optimizer\optimization.py", line 77, in run
    self.optimize()
  File "d:\anaconda3\envs\foqus-issues\lib\site-packages\foqus_lib\framework\optimizer\SM_Optimizer.py", line 440, in optimize
    kwds['warmstart'] = Warmstart
NameError: name 'Warmstart' is not defined

**Error 2**
2020-10-26 15:01:13,313 - ERROR - foqus.foqus_lib.framework.optimizer.optimization - Exception in optimization thread
Traceback (most recent call last):
  File "d:\anaconda3\envs\foqus-issues\lib\site-packages\foqus_lib\framework\optimizer\optimization.py", line 77, in run
    self.optimize()
  File "d:\anaconda3\envs\foqus-issues\lib\site-packages\foqus_lib\framework\optimizer\SM_Optimizer.py", line 901, in optimize
    for var in decvars:
UnboundLocalError: local variable 'decvars' referenced before assignment

**Error 3**
2020-10-26 15:09:12,318 - ERROR - foqus.foqus_lib.framework.optimizer.optimization - Exception in optimization thread
Traceback (most recent call last):
  File "d:\anaconda3\envs\foqus-issues\lib\site-packages\foqus_lib\framework\optimizer\optimization.py", line 77, in run
    self.optimize()
  File "d:\anaconda3\envs\foqus-issues\lib\site-packages\foqus_lib\framework\optimizer\SM_Optimizer.py", line 549, in optimize
    var.value = input_optim[minobjval_idx][i]
TypeError: 'float' object is not subscriptable

**Error 4**
2020-10-26 15:11:25,865 - ERROR - foqus.foqus_lib.framework.optimizer.optimization - Exception in optimization thread
Traceback (most recent call last):
  File "d:\anaconda3\envs\foqus-issues\lib\site-packages\foqus_lib\framework\optimizer\optimization.py", line 77, in run
    self.optimize()
  File "d:\anaconda3\envs\foqus-issues\lib\site-packages\foqus_lib\framework\optimizer\SM_Optimizer.py", line 562, in optimize
    self.msgQueue.put("Solver Solution Time: {0} s".format(r.solver.time))
  File "d:\anaconda3\envs\foqus-issues\lib\site-packages\pyomo\opt\results\container.py", line 178, in __getattr__
    return getattr(self._list[0], name)
  File "d:\anaconda3\envs\foqus-issues\lib\site-packages\pyomo\opt\results\container.py", line 287, in __getattr__
    raise AttributeError("Unknown attribute `"+str(name)+"' for object with type "+str(type(self)))
AttributeError: Unknown attribute `time' for object with type <class 'pyomo.opt.results.solver.SolverInformation'>

**Comment by anujad95** [comment]
I will look into this Daison. Thanks.
