### ISSUE TITLE
Foqus PyQt5 import error 

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/FOQUS#857]
# Details
- MacOS
- virtualenv
- python 3.8.6

# Error
```
$ . py3/bin/activate
...
$ python setup.py develop
....
Searching for PyQt5_sip<13,>=4.19.14
Reading https://pypi.org/simple/PyQt5_sip/
Downloading https://files.pythonhosted.org/packages/51/92/af676068a945d047fab697adddc82ede4264c98ed82447533ce8ef02622f/PyQt5_sip-12.8.1-cp38-cp38-macosx_10_9_x86_64.whl#sha256=9312ec47cac4e33c11503bc1cbeeb0bdae619620472f38e2078c5a51020a930f
Best match: PyQt5-sip 12.8.1
Processing PyQt5_sip-12.8.1-cp38-cp38-macosx_10_9_x86_64.whl
Installing PyQt5_sip-12.8.1-cp38-cp38-macosx_10_9_x86_64.whl to /Users/boverhof/Documents/workspace.ccsi2/py3/lib/python3.8/site-packages
Adding PyQt5-sip 12.8.1 to easy-install.pth file

Installed /Users/boverhof/Documents/workspace.ccsi2/py3/lib/python3.8/site-packages/PyQt5_sip-12.8.1-py3.8-macosx-10.14-x86_64.egg
...
```
```
$ foqus
2020-12-09 12:14:57,192 - ERROR - foqus.foqus_lib.foqus - Error importing PyQt
Traceback (most recent call last):
  File "/Users/boverhof/Documents/workspace.ccsi2/foqus-boverhof/foqus_lib/foqus.py", line 49, in guiImport
    import PyQt5.QtWidgets
ModuleNotFoundError: No module named 'PyQt5.sip'
2020-12-09 12:14:57,193 - DEBUG - foqus.foqus_lib.foqus - Working directory set to /Users/boverhof/Documents/workspace.ccsi2/foqus_working_dir
2020-12-09 12:14:57,201 - DEBUG - foqus.foqus_lib.framework.session.session - Initializing session, Log file: /Users/boverhof/Documents/workspace.ccsi2/foqus_working_dir/logs/foqus.log, Position: 753786
2020-12-09 12:14:57,202 - INFO - foqus.foqus_lib.framework.plugins.pluginSearch - Loading Plugin: /Users/boverhof/Documents/workspace.ccsi2/foqus-boverhof/foqus_lib/framework/surrogate/BSS-ANOVA.py
2020-12-09 12:14:57,203 - INFO - foqus.foqus_lib.framework.plugins.pluginSearch - Loading Plugin: /Users/boverhof/Documents/workspace.ccsi2/foqus-boverhof/foqus_lib/framework/surrogate/ALAMO.py
2020-12-09 12:14:57,205 - INFO - foqus.foqus_lib.framework.plugins.pluginSearch - Loading Plugin: /Users/boverhof/Documents/workspace.ccsi2/foqus-boverhof/foqus_lib/framework/surrogate/ACOSSO.py
2020-12-09 12:14:57,206 - INFO - foqus.foqus_lib.framework.plugins.pluginSearch - Loading Plugin: /Users/boverhof/Documents/workspace.ccsi2/foqus-boverhof/foqus_lib/framework/optimizer/OptCMA.py
2020-12-09 12:14:57,304 - INFO - foqus.foqus_lib.framework.plugins.pluginSearch - Loading Plugin: /Users/boverhof/Documents/workspace.ccsi2/foqus-boverhof/foqus_lib/framework/optimizer/SM_Optimizer.py
2020-12-09 12:14:57,314 - INFO - foqus.foqus_lib.framework.plugins.pluginSearch - Loading Plugin: /Users/boverhof/Documents/workspace.ccsi2/foqus-boverhof/foqus_lib/framework/optimizer/NLopt.py
2020-12-09 12:14:57,315 - INFO - foqus.foqus_lib.framework.plugins.pluginSearch - Loading Plugin: /Users/boverhof/Documents/workspace.ccsi2/foqus-boverhof/foqus_lib/framework/optimizer/SLSQP.py
2020-12-09 12:14:57,316 - INFO - foqus.foqus_lib.framework.plugins.pluginSearch - Loading Plugin: /Users/boverhof/Documents/workspace.ccsi2/foqus-boverhof/foqus_lib/framework/optimizer/PSUADE.py
2020-12-09 12:14:57,317 - INFO - foqus.foqus_lib.framework.plugins.pluginSearch - Loading Plugin: /Users/boverhof/Documents/workspace.ccsi2/foqus-boverhof/foqus_lib/framework/optimizer/Sample.py
2020-12-09 12:14:57,318 - INFO - foqus.foqus_lib.framework.plugins.pluginSearch - Loading Plugin: /Users/boverhof/Documents/workspace.ccsi2/foqus-boverhof/foqus_lib/framework/optimizer/Snobfit.py
2020-12-09 12:14:57,319 - INFO - foqus.foqus_lib.framework.plugins.pluginSearch - Loading Plugin: /Users/boverhof/Documents/workspace.ccsi2/foqus-boverhof/foqus_lib/framework/optimizer/BFGS.py
2020-12-09 12:14:57,584 - INFO - foqus.foqus_lib.framework.plugins.pluginSearch - Removing plugin, due to missing dependency: SM_Optimizer
2020-12-09 12:14:57,584 - INFO - foqus.foqus_lib.framework.plugins.pluginSearch - Removing plugin, due to missing dependency: NLopt
2020-12-09 12:14:57,584 - INFO - foqus.foqus_lib.framework.plugins.pluginSearch - Removing plugin, due to missing dependency: Snobfit
2020-12-09 12:14:57,585 - INFO - foqus.foqus_lib.framework.plugins.pluginSearch - Loading Plugin: /Users/boverhof/Documents/workspace.ccsi2/foqus-boverhof/foqus_lib/framework/pymodel/steam_cycle.py
2020-12-09 12:14:57,587 - INFO - foqus.foqus_lib.framework.plugins.pluginSearch - Loading Plugin: /Users/boverhof/Documents/workspace.ccsi2/foqus-boverhof/foqus_lib/framework/pymodel/pymodel_test.py
2020-12-09 12:14:57,589 - INFO - foqus.foqus_lib.framework.plugins.pluginSearch - Loading Plugin: /Users/boverhof/Documents/workspace.ccsi2/foqus-boverhof/foqus_lib/framework/pymodel/heat_integration.py
2020-12-09 12:14:57,595 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - turbine configuration application url="https://b7x9ucxadg.execute-api.us-east-1.amazonaws.com/development/application/"
2020-12-09 12:14:57,595 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - turbine configuration url="https://b7x9ucxadg.execute-api.us-east-1.amazonaws.com/development"
2020-12-09 12:14:57,596 - ERROR - foqus.foqus_lib.foqus - PyQt5 or Qt not available
2020-12-09 12:14:57,596 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - Stopped all running consumers
2020-12-09 12:14:57,630 - DEBUG - foqus.foqus_lib.framework.sim.process_management - Found Process: []
```

# Missing Import
```
$ python
Python 3.8.6 (default, Oct  8 2020, 14:07:53) 
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
>>> import PyQt5
>>> PyQt5
<module 'PyQt5' from '/Users/boverhof/Documents/workspace.ccsi2/py3/lib/python3.8/site-packages/PyQt5-5.13.0-py3.8-macosx-10.14-x86_64.egg/PyQt5/__init__.py'>
>>> import PyQt5.QtWidgets
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'PyQt5.sip'
>>> 
```

**Comment by boverhof** [comment]
# Backwards incompatible change in PyQt 5.11 

[pyQt5 backward incompatible change](https://www.riverbankcomputing.com/static/Docs/PyQt5/incompatibilities.html#pyqt-v5-11)

**Comment by lbianchi-lbl** [comment]
Does this happen if FOQUS is installed with pip instead of `setup.py develop`?

If so, and if we aren't already, we should add a note in the docs that `python setup.py develop`/`easy_install` is deprecated.

**Comment by boverhof** [comment]
Although I made a new virtualenv, I'm thinking it may be `brew` installation needs to be updated because of Mac OS X updates.  Let me wait for this to update/etc. 

Shouldn't `python setup.py develop` work for at least developers?

**Comment by lbianchi-lbl** [comment]
> Shouldn't `python setup.py develop` work for at least developers?

In principle, yes; I don't think FOQUS itself would cause problems with that. The (possible) source of issues is in installing the dependencies. PyQt is in my experience (in)famous for being particularly finicky, but mostly works fine with pip.

From what I understand (I've mostly used pip since I started programming in Python), `pip install` is generally recommended over `setup.py install` nowadays, since in any case the functionality is similar between the two; e.g., `pip install --editable` is the pip equivalent of `setup.py develop`.

**Comment by boverhof** [comment]
I think the problem boils down to an issue with PyQt and the sip module.  
```
>>> import PyQt5.QtWidgets
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'PyQt5.sip'
```

### solution
Upgrading to the current PyQt5-5.15 release did away with the problem I was having
```

(py3.9) joshuas-mbp:foqus-boverhof boverhof$ git diff
diff --git a/setup.py b/setup.py
index 0270248..7dd4067 100644
--- a/setup.py
+++ b/setup.py
@@ -68,13 +68,14 @@ dist = setup(
         "numpy",
         "pandas",
         "psutil",
-        "PyQt5==5.13",
+        "PyQt5==5.15",
```

**Comment by ksbeattie** [comment]
@boverhof, I came across this problem a while back, [described here](https://coldfix.de/2019/03/14/no-pip-no-sip/), which is why I now say you should never run `python seutp.py` and only `pip install`.

**Comment by ksbeattie** [comment]
Looks like this was changed in PR #859?

**Comment by boverhof** [comment]
Failures of circleci installation of PyQT==5.15 ( missing attribute ) may be due to PIP version.  Happened with a 19 version, maybe it works with a 20 version pip.

**Comment by ksbeattie** [comment]
will close this for now on the hope that this is fixed by using `pip install` vs `python setup.py`
