### ISSUE TITLE
Error 20 When Running Flow Sheet

### ISSUE THREAD

**Issue by LNemetz** [CCSI-Toolset/FOQUS#864]
![image](https://user-images.githubusercontent.com/76179027/104050400-93c42300-51b4-11eb-8dec-d36c8097059f.png)

I get this error messages in foqus when I try to run the node. I have checked my initial conditions and my Aspen model runs and converges.  I think the problem is from foqus.

**Comment by anujad95** [comment]
@LNemetz could you please provide more details on the error from the FOQUS log?

**Comment by LNemetz** [comment]
![image](https://user-images.githubusercontent.com/76179027/104240731-89ab5a00-542a-11eb-866f-cace9294bc0b.png)
![image](https://user-images.githubusercontent.com/76179027/104240774-9760df80-542a-11eb-8424-571685b325bd.png)
![image](https://user-images.githubusercontent.com/76179027/104240811-a6479200-542a-11eb-887e-3df48604415d.png)

**Comment by lbianchi-lbl** [comment]
A possible cause for this would be the Python version used to run FOQUS. The `time.clock()` function ([link](https://docs.python.org/3.7/library/time.html#time.clock)) was removed in Python 3.8 (it had been deprecated since 3.3), and would cause this error if FOQUS is installed in an environment with Python 3.8 or later.

@LNemetz you should be able to verify this by checking the version of Python you're running, for example, by opening a Python shell in the console (from the directory names in the logs, I'm assuming this is on Windows) and looking at the version number displayed in the header.

This particular error should be straightforward to fix, but we would have to test more carefully to make sure that the rest of the codebase is Python 3.8-compatible. In the meantime, a possible workaround is to use the most recent Python version that's being extensively tested with FOQUS, which is 3.7.

**Comment by LNemetz** [comment]
@lbianchi-lbl I've gone back and installed python 3.7 and gotten the error messages but my log looks different.

`2021-01-12 15:09:33,856 - DEBUG - foqus.foqus_lib.framework.session.session - Initializing session, Log file: C:\Users\LNemetz\OneDrive - University of Toledo\Documents\Foqus Files\logs\foqus.log, Position: 216543
2021-01-12 15:09:33,865 - INFO - foqus.foqus_lib.framework.plugins.pluginSearch - Loading Plugin: c:\users\lnemetz\appdata\local\continuum\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\surrogate\ACOSSO.py
2021-01-12 15:09:33,896 - INFO - foqus.foqus_lib.framework.plugins.pluginSearch - Loading Plugin: c:\users\lnemetz\appdata\local\continuum\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\surrogate\ALAMO.py
2021-01-12 15:09:33,908 - INFO - foqus.foqus_lib.framework.plugins.pluginSearch - Loading Plugin: c:\users\lnemetz\appdata\local\continuum\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\surrogate\BSS-ANOVA.py
2021-01-12 15:09:33,923 - INFO - foqus.foqus_lib.framework.plugins.pluginSearch - Loading Plugin: c:\users\lnemetz\appdata\local\continuum\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\optimizer\BFGS.py
2021-01-12 15:09:34,915 - INFO - foqus.foqus_lib.framework.plugins.pluginSearch - Loading Plugin: c:\users\lnemetz\appdata\local\continuum\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\optimizer\NLopt.py
2021-01-12 15:09:34,918 - INFO - foqus.foqus_lib.framework.plugins.pluginSearch - Loading Plugin: c:\users\lnemetz\appdata\local\continuum\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\optimizer\OptCMA.py
2021-01-12 15:09:34,949 - INFO - foqus.foqus_lib.framework.plugins.pluginSearch - Loading Plugin: c:\users\lnemetz\appdata\local\continuum\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\optimizer\PSUADE.py
2021-01-12 15:09:34,951 - INFO - foqus.foqus_lib.framework.plugins.pluginSearch - Loading Plugin: c:\users\lnemetz\appdata\local\continuum\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\optimizer\Sample.py
2021-01-12 15:09:34,953 - INFO - foqus.foqus_lib.framework.plugins.pluginSearch - Loading Plugin: c:\users\lnemetz\appdata\local\continuum\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\optimizer\SLSQP.py
2021-01-12 15:09:34,955 - INFO - foqus.foqus_lib.framework.plugins.pluginSearch - Loading Plugin: c:\users\lnemetz\appdata\local\continuum\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\optimizer\SM_Optimizer.py
2021-01-12 15:09:34,960 - INFO - foqus.foqus_lib.framework.plugins.pluginSearch - Loading Plugin: c:\users\lnemetz\appdata\local\continuum\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\optimizer\Snobfit.py
2021-01-12 15:09:34,964 - INFO - foqus.foqus_lib.framework.plugins.pluginSearch - Removing plugin, due to missing dependency: NLopt
2021-01-12 15:09:34,964 - INFO - foqus.foqus_lib.framework.plugins.pluginSearch - Removing plugin, due to missing dependency: SM_Optimizer
2021-01-12 15:09:34,964 - INFO - foqus.foqus_lib.framework.plugins.pluginSearch - Removing plugin, due to missing dependency: Snobfit
2021-01-12 15:09:34,966 - INFO - foqus.foqus_lib.framework.plugins.pluginSearch - Loading Plugin: c:\users\lnemetz\appdata\local\continuum\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\pymodel\heat_integration.py
2021-01-12 15:09:34,969 - INFO - foqus.foqus_lib.framework.plugins.pluginSearch - Loading Plugin: c:\users\lnemetz\appdata\local\continuum\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\pymodel\pymodel_test.py
2021-01-12 15:09:34,970 - INFO - foqus.foqus_lib.framework.plugins.pluginSearch - Loading Plugin: c:\users\lnemetz\appdata\local\continuum\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\pymodel\steam_cycle.py
2021-01-12 15:09:34,979 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - turbine configuration application url="http://localhost:8000/TurbineLite/application/"
2021-01-12 15:09:34,980 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - turbine configuration url="http://localhost:8000/TurbineLite"
2021-01-12 15:10:20,198 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - turbine configuration application url="http://localhost:8000/TurbineLite/application/"
2021-01-12 15:10:20,198 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - turbine configuration url="http://localhost:8000/TurbineLite"
2021-01-12 15:10:20,203 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - Uploading simulation to turbine.
modelFile: C:\Users\LNemetz\OneDrive - University of Toledo\Documents\AspenPlus Files\MTR Process.bkp
resourceType: aspenfile
app: AspenPlus
oth: []

2021-01-12 15:10:20,368 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - resourceType aspenfile specified as MTR Process.bkp
2021-01-12 15:10:20,489 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - turbine configuration application url="http://localhost:8000/TurbineLite/application/"
2021-01-12 15:10:20,490 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - turbine configuration url="http://localhost:8000/TurbineLite"
2021-01-12 15:10:39,245 - DEBUG - foqus.foqus_lib.framework.graph.graph - run: Running flowsheet(s) locally
2021-01-12 15:10:39,247 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - turbine configuration application url="http://localhost:8000/TurbineLite/application/"
2021-01-12 15:10:39,252 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - turbine configuration url="http://localhost:8000/TurbineLite"
2021-01-12 15:10:39,318 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - Starting simulation consumer...
2021-01-12 15:10:39,394 - ERROR - foqus.foqus_lib.framework.graph.graph - Exception in graph thread
Traceback (most recent call last):
File "c:\users\lnemetz\appdata\local\continuum\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\graph\graph.py", line 814, in run
self.solve()
File "c:\users\lnemetz\appdata\local\continuum\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\graph\graph.py", line 975, in solve
self.runGraph(order)
File "c:\users\lnemetz\appdata\local\continuum\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\graph\graph.py", line 1286, in runGraph
elif self.runNode(name) != 0:
File "c:\users\lnemetz\appdata\local\continuum\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\graph\graph.py", line 1298, in runNode
node.runCalc()
File "c:\users\lnemetz\appdata\local\continuum\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\graph\node.py", line 474, in runCalc
self.runModel()
File "c:\users\lnemetz\appdata\local\continuum\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\graph\node.py", line 497, in runModel
self.runTurbineCalc(retry=self.options["Retry"].value)
File "c:\users\lnemetz\appdata\local\continuum\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\graph\node.py", line 675, in runTurbineCalc
configProfile.startConsumer(self.name, self.modelName)
File "c:\users\lnemetz\appdata\local\continuum\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\sim\turbineConfiguration.py", line 332, in startConsumer
db = self.getTurbineLiteDB()
File "c:\users\lnemetz\appdata\local\continuum\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\sim\turbineConfiguration.py", line 224, in getTurbineLiteDB
db = turbineLiteDB.turbineLiteDB()
NameError: name 'turbineLiteDB' is not defined
2021-01-12 15:10:39,872 - ERROR - foqus.foqus_lib.gui.main.mainWindow - to results graph thread was likely terminated`

**Comment by lbianchi-lbl** [comment]
@LNemetz thanks for reporting this new problem. I've looked into the `turbineConfiguration.py` code, and I believe that the `NameError: name "turbineLiteDB" is not defined` error occurs because the `turbineLiteDB` module could not be imported. This in turns might be due to the `adodbapi` module that is imported in `turbineLiteDB`.

To check if any of these hypotheses is correct, could you try to run the following Python statements one at a time inside a Python shell using the same environment where FOQUS is installed, and report back the output (including possible errors)?

- `import sys; sys.platform`
- `import foqus_lib.framework.sim.turbineConfiguration`
- `from foqus_lib.framework.sim import turbineLiteDB`
- `import adodbapi`
- `import adodbapi.apibase`
- `print(adodbapi.adodbapi.defaultCursorLocation)`

**Comment by LNemetz** [comment]
The commands return the following:
import sys; sys.platform:
![image](https://user-images.githubusercontent.com/76179027/104494916-167a2300-55a5-11eb-9d42-64bfe81479df.png)

import foqus_lib.framework.sim.turbineConfiguration:
![image](https://user-images.githubusercontent.com/76179027/104494984-2c87e380-55a5-11eb-82a9-d76c03ad83c1.png)

from foqus_lib.framework.sim import turbineLiteDB:
![image](https://user-images.githubusercontent.com/76179027/104495195-6fe25200-55a5-11eb-9c94-263c2eca1d86.png)

**Comment by LNemetz** [comment]
@lbianchi-lbl The Same InentationError: unexpected indent occurs in the adodbapi commands as well and the the last statement doesn't print

**Comment by lbianchi-lbl** [comment]
This seems to be a known problem with some versions of adodbapi, see e.g. https://www.mail-archive.com/python-win32@python.org/msg11288.html. I've tested the commands on a Windows machine and I wasn't able to reproduce the issue.

I can suggest a couple of things to try:

- Run `pip list` in the same environment and report the results here. This could help see if the adodbapi version differs between our environments
- Uninstall and reinstall the adodbapi pip package (if possible, reporting the output of both pip commands)

    ```sh
    pip uninstall adodbapi
    pip install adodbapi
    ```

**Comment by LNemetz** [comment]
@lbianchi-lbl after I've done your suggestions for adodbapi, I've gotten the same error message, and in the log it seems to be NameError: name 'turbineLiteDB' is not defined. 

`2021-01-15 12:57:06,908 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - turbine configuration application url="http://localhost:8000/TurbineLite/application/"
2021-01-15 12:57:06,908 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - turbine configuration url="http://localhost:8000/TurbineLite"
2021-01-15 12:57:10,000 - DEBUG - foqus.foqus_lib.framework.graph.graph - run: Running flowsheet(s) locally
2021-01-15 12:57:10,002 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - turbine configuration application url="http://localhost:8000/TurbineLite/application/"
2021-01-15 12:57:10,003 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - turbine configuration url="http://localhost:8000/TurbineLite"
2021-01-15 12:57:10,047 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - Starting simulation consumer...
2021-01-15 12:57:10,094 - ERROR - foqus.foqus_lib.framework.graph.graph - Exception in graph thread
Traceback (most recent call last):
File "c:\users\lnemetz\appdata\local\continuum\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\graph\graph.py", line 814, in run
self.solve()
File "c:\users\lnemetz\appdata\local\continuum\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\graph\graph.py", line 975, in solve
self.runGraph(order)
File "c:\users\lnemetz\appdata\local\continuum\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\graph\graph.py", line 1286, in runGraph
elif self.runNode(name) != 0:
File "c:\users\lnemetz\appdata\local\continuum\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\graph\graph.py", line 1298, in runNode
node.runCalc()
File "c:\users\lnemetz\appdata\local\continuum\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\graph\node.py", line 474, in runCalc
self.runModel()
File "c:\users\lnemetz\appdata\local\continuum\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\graph\node.py", line 497, in runModel
self.runTurbineCalc(retry=self.options["Retry"].value)
File "c:\users\lnemetz\appdata\local\continuum\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\graph\node.py", line 675, in runTurbineCalc
configProfile.startConsumer(self.name, self.modelName)
File "c:\users\lnemetz\appdata\local\continuum\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\sim\turbineConfiguration.py", line 332, in startConsumer
db = self.getTurbineLiteDB()
File "c:\users\lnemetz\appdata\local\continuum\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\sim\turbineConfiguration.py", line 224, in getTurbineLiteDB
db = turbineLiteDB.turbineLiteDB()
NameError: name 'turbineLiteDB' is not defined
2021-01-15 12:57:10,499 - ERROR - foqus.foqus_lib.gui.main.mainWindow - to results graph thread was likely terminated`

**Comment by LNemetz** [comment]
I also get the same indent errors when trying to run your suggestion from before, the
import sys; sys.platform etc.

**Comment by lbianchi-lbl** [comment]
@LNemetz thanks again for running these checks and reporting the results.
This would seem to confirm our suspicion that the error is caused by the version of `adodbapi` that's installed in your environment. Additionally, there might be some kind of interference between the `adodbapi` PyPI package and the `adodbapi` installed package, since the `adodbapi` package is also included in another one of FOQUS's dependencies on Windows, `pywin32`.

I'd try the following steps (again, reporting the output here if possible), and then try again to run FOQUS and the commands described previously (https://github.com/CCSI-Toolset/FOQUS/issues/864#issuecomment-759031415) to test if importing `adodbapi` works:

```sh
pip uninstall --yes adodbapi pywin32
pip install -vv --no-cache-dir --ignore-installed pywin32
```

**Comment by LNemetz** [comment]
@lbianchi-lbl the uninstall command yielded:
![image](https://user-images.githubusercontent.com/76179027/104953653-cf20d780-5994-11eb-8e40-67222268f789.png)

the second line ran and this error occured
![image](https://user-images.githubusercontent.com/76179027/104953778-11e2af80-5995-11eb-9474-b810a3ed2398.png)
I didn't post the entire command promnt.

I was able to run my foqus file in the flowsheet tab as needed.
