### ISSUE TITLE
Opt_Uncertain_Test_01.foqus  Flowsheet Error

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/FOQUS#931]
# Description
When opening this flowsheet there is an error.

# Detail
```
2021-07-08 17:24:20,702 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - turbine configuration url="http://localhost:8000/TurbineLite"
2021-07-08 17:24:20,702 - ERROR - foqus.foqus_lib.framework.sampleResults.results - Error loading stored results
Traceback (most recent call last):
  File "c:\users\administrator\desktop\foqus\foqus_lib\framework\sampleResults\results.py", line 366, in loadDict
    columns = sd["__columns"]
KeyError: '__columns'
2021-07-08 17:24:20,717 - CRITICAL - foqus.foqus_lib.foqus - unhandled exception
Traceback (most recent call last):
  File "c:\users\administrator\desktop\foqus\foqus_lib\gui\main\mainWindow.py", line 1106, in loadData
    self.dat.load(fileName)
  File "c:\users\administrator\desktop\foqus\foqus_lib\framework\session\session.py", line 541, in load
    self.loadDict(sd, filename, stopConsumers=stopConsumers)
  File "c:\users\administrator\desktop\foqus\foqus_lib\framework\session\session.py", line 578, in loadDict
    self.flowsheet.loadDict(sd["flowsheet"])
  File "c:\users\administrator\desktop\foqus\foqus_lib\framework\graph\graph.py", line 304, in loadDict
    self.input.loadDict(temp)
  File "c:\users\administrator\desktop\foqus\foqus_lib\framework\graph\nodeVars.py", line 245, in loadDict
    self.addVariable(node, var).loadDict(sd[node][var])
  File "c:\users\administrator\desktop\foqus\foqus_lib\framework\graph\nodeVars.py", line 792, in loadDict
    self.value = hist[0]
  File "c:\users\administrator\desktop\foqus\foqus_lib\framework\graph\nodeVars.py", line 631, in __setattr__
    self.setValue(val)
  File "c:\users\administrator\desktop\foqus\foqus_lib\framework\graph\nodeVars.py", line 603, in setValue
    self.__value = self.dtype(val)
TypeError: float() argument must be a string or a number, not 'list'
```

**Comment by anujad95** [comment]
According to the traceback order, I confirmed that this file contains a combination of scalar variables, and the old-format vector variables. The vectors in this file are NodeVar objects that have their value (assigned from hist[0]), min, max and default as a list. Although we have a new vector variable support capability, it works differently, and in the current base code, NodeVar object does not accept lists for any of its attributes. Due to this, the file cannot be opened.

**Comment by ksbeattie** [comment]
This file doesn't appear to be used in any of our documented tutorials.  Perhaps it should just be removed?  @sotorrio1, what do you think?

**Comment by sotorrio1** [comment]
I have no idea what this file is about...

**Comment by ksbeattie** [comment]
@anujad95, can this file be removed?

**Comment by anujad95** [comment]
Yes, i think we can go ahead and remove this file, as it is not being used in any tutorials.
