### ISSUE TITLE
FOQUS Cloud: OUU bugs

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/FOQUS#999]
# Description
When Running OUU via the FOQUS UQ, after hitting start an exception is happening before submission of jobs.

```bash
2022-01-18 11:03:47,752 - CRITICAL - foqus.foqus_lib.foqus - unhandled exception
Traceback (most recent call last):
  File "/Users/boverhof/Documents/workspace.ccsi2/foqus-boverhof/foqus_lib/gui/uq/uqSetupFrame.py", line 570, in simSelected
    self.initUQToolBox()
  File "/Users/boverhof/Documents/workspace.ccsi2/foqus-boverhof/foqus_lib/gui/uq/uqSetupFrame.py", line 1150, in initUQToolBox
    self.initData()
  File "/Users/boverhof/Documents/workspace.ccsi2/foqus-boverhof/foqus_lib/gui/uq/uqSetupFrame.py", line 1177, in initData
    self.initFilter()
  File "/Users/boverhof/Documents/workspace.ccsi2/foqus-boverhof/foqus_lib/gui/uq/uqSetupFrame.py", line 1190, in initFilter
    self.refreshFilterData()
  File "/Users/boverhof/Documents/workspace.ccsi2/foqus-boverhof/foqus_lib/gui/uq/uqSetupFrame.py", line 1236, in refreshFilterData
    self.filterWidget.refreshContents()
  File "/Users/boverhof/Documents/workspace.ccsi2/foqus-boverhof/foqus_lib/gui/flowsheet/dataBrowserFrame.py", line 165, in refreshContents
    if self.results is None or self.results.empty:
AttributeError: 'SampleData' object has no attribute 'empty'
2022-01-18 11:04:31,206 - CRITICAL - foqus.foqus_lib.foqus - unhandled exception
Traceback (most recent call last):
  File "/Users/boverhof/Documents/workspace.ccsi2/foqus-boverhof/foqus_lib/gui/uq/uqSetupFrame.py", line 570, in simSelected
    self.initUQToolBox()
  File "/Users/boverhof/Documents/workspace.ccsi2/foqus-boverhof/foqus_lib/gui/uq/uqSetupFrame.py", line 1150, in initUQToolBox
    self.initData()
  File "/Users/boverhof/Documents/workspace.ccsi2/foqus-boverhof/foqus_lib/gui/uq/uqSetupFrame.py", line 1177, in initData
    self.initFilter()
  File "/Users/boverhof/Documents/workspace.ccsi2/foqus-boverhof/foqus_lib/gui/uq/uqSetupFrame.py", line 1190, in initFilter
    self.refreshFilterData()
  File "/Users/boverhof/Documents/workspace.ccsi2/foqus-boverhof/foqus_lib/gui/uq/uqSetupFrame.py", line 1236, in refreshFilterData
    self.filterWidget.refreshContents()
  File "/Users/boverhof/Documents/workspace.ccsi2/foqus-boverhof/foqus_lib/gui/flowsheet/dataBrowserFrame.py", line 165, in refreshContents
    if self.results is None or self.results.empty:
AttributeError: 'SampleData' object has no attribute 'empty'
2022-01-18 11:04:54,920 - DEBUG - foqus.foqus_lib.gui.uq.uqSetupFrame - Lauch button pressed, launching UQ ensemble
2022-01-18 11:04:55,112 - CRITICAL - foqus.foqus_lib.foqus - unhandled exception
Traceback (most recent call last):
  File "/Users/boverhof/Documents/workspace.ccsi2/foqus-boverhof/foqus_lib/gui/uq/uqSetupFrame.py", line 1002, in launchSim
    self.dat.flowsheet.uploadFlowseetToTurbine(
  File "/Users/boverhof/Documents/workspace.ccsi2/foqus-boverhof/foqus_lib/framework/graph/graph.py", line 507, in uploadFlowseetToTurbine
    dat.save(
  File "/Users/boverhof/Documents/workspace.ccsi2/foqus-boverhof/foqus_lib/framework/session/session.py", line 511, in save
    sd["uqFilterResultsList"].append(filter.saveDict())
AttributeError: 'NoneType' object has no attribute 'saveDict'
2022-01-18 11:05:33,570 - INFO - foqus.foqus_lib.gui.help.helpBrowser - on_message
```

**Comment by sotorrio1** [comment]
@boverhof I think I know what might be going on here. Last time Jeremy modified this script to incorporate @eslickj 's filter he added this line in a bunch of places:

`if self.results is None or self.results.empty`

The problem with that statement is that if self.results is None, then a NoneType object won't have attribute 'empty'. 

I can open a PR with the changes I think would take care of this and you can test it...
